<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo  $this->view->adminConfig->admin->title ?> | 404 Error Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php $this->partial("partials/styles") ?>
</head>

<body class="hold-transition lockscreen">
    <!-- Automatic element centering -->
    <div class="error-page">
        <h2 class="headline text-yellow"> 404</h2>

        <div class="error-content">
            <h3><i class="fa fa-warning text-yellow"></i> Oops! You're lost.</h3>

            <p>

                We can not find the page you're looking for.<br />

            </p>
        </div>
        <!-- /.error-content -->
    </div>

    <!-- /.center -->

    <?php $this->partial("partials/js") ?>
</body>

</html>