<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->

<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->

<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->

<head>

	<meta charset="utf-8" />

	<title>Metronic | 401 Page</title>

	<meta content="width=device-width, initial-scale=1.0" name="viewport" />

	<meta content="" name="description" />

	<meta content="" name="author" />

	<!-- BEGIN GLOBAL MANDATORY STYLES -->

	<link href="<?php echo $this->view->resourceUrl?>media/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/style-metro.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/style.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/style-responsive.css" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>

	<link href="<?php echo $this->view->resourceUrl?>media/css/uniform.default.css" rel="stylesheet" type="text/css"/>

	<!-- END GLOBAL MANDATORY STYLES -->

	<!-- BEGIN PAGE LEVEL STYLES -->

	<link href="<?php echo $this->view->resourceUrl?>media/css/error.css" rel="stylesheet" type="text/css"/>

	<!-- END PAGE LEVEL STYLES -->

	<link rel="shortcut icon" href="<?php echo $this->view->resourceUrl?>media/image/favicon.ico" />

</head>

<!-- END HEAD -->

<!-- BEGIN BODY -->

<body class="page-404-full-page">

	<div class="row-fluid">

		<div class="span12 page-404">

			<div class="number">

				401

			</div>

			<div class="details">

				<h3>Opps, Unauthorized</h3>

				<p>

					You don't have access to this option. Contact an administrator<br />

				</p>

			</div>

		</div>

	</div>

	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

	<!-- BEGIN CORE PLUGINS -->

	<script src="<?php echo $this->view->resourceUrl?>media/js/jquery-1.8.3.min.js" type="text/javascript"></script>   

	<script src="<?php echo $this->view->resourceUrl?>media/js/bootstrap.min.js" type="text/javascript"></script>

	<!--[if lt IE 9]>

	<script src="<?php echo $this->view->resourceUrl?>media/js/excanvas.js"></script>

	<script src="<?php echo $this->view->resourceUrl?>media/js/respond.js"></script>  

	<![endif]-->   

	<script src="<?php echo $this->view->resourceUrl?>media/js/breakpoints.js" type="text/javascript"></script>  

	<script src="<?php echo $this->view->resourceUrl?>media/js/jquery.uniform.min.js" type="text/javascript" ></script> 

	<!-- END CORE PLUGINS -->

	<script src="<?php echo $this->view->resourceUrl?>media/js/app.js"></script>  

	<script>

		jQuery(document).ready(function() {    

		   App.init();

		});

	</script>

	<!-- END JAVASCRIPTS -->

<!-- <script type="text/javascript">  var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-37564768-1']);  _gaq.push(['_setDomainName', 'keenthemes.com']);  _gaq.push(['_setAllowLinker', true]);  _gaq.push(['_trackPageview']);  (function() {    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script> -->
</body>

<!-- END BODY -->

</html>