<a href="<?php echo $this->view->baseUrl . 'admin/index/index' ?>" class="logo">
	<!-- mini logo for sidebar mini 50x50 pixels -->
	<span class="logo-mini"><?php echo !empty($this->view->adminConfig->admin->logo_mini) ? $this->view->adminConfig->admin->logo_mini : $this->view->adminConfig->admin->name ?></span>
	<!-- logo for regular state and mobile devices -->
	<span class="logo-lg"><?php echo !empty($this->view->adminConfig->admin->logo) ? $this->view->adminConfig->admin->logo : $this->view->adminConfig->admin->name ?></span>
</a>