<div class="row">
    <div class="col-md-12">
        <script data-exec-on-popstate>
            $(function() {
                LA.intervalIds = [];
                LA.addIntervalId = function(intervalId, persist) {
                    this.intervalIds.push({
                        id: intervalId,
                        persist: persist
                    });
                };

                LA.clearIntervalId = function(intervalId) {
                    for (var id in this.intervalIds) {
                        if (intervalId == this.intervalIds[id].id && !this.intervalIds[id].persist) {
                            clearInterval(intervalId);
                            this.intervalIds.splice(id, 1);
                        }
                    }
                };

                LA.cleanIntervalId = function() {
                    for (var id in this.intervalIds) {
                        if (!this.intervalIds[id].persist) {
                            clearInterval(this.intervalIds[id].id);
                            this.intervalIds.splice(id, 1);
                        }
                    }
                };

                $(document).on('pjax:complete', function(xhr) {
                    $.admin.cleanIntervalId();
                });

                $('.log-refresh').on('click', function() {
                    $.pjax.reload('#pjax-container');
                });

                var pos = <?php echo $this->view->end; ?>;

                function changePos(offset) {
                    pos = offset;
                }

                function fetch() {
                    $.ajax({
                        url: '<?php echo $this->myTag->getUrl($this->view, 'tail', array('__SHOWBYIFRAME__' => 0, 'file' => $this->view->fileName)); ?>',
                        method: 'post',
                        data: {
                            offset: pos,
                            _token: LA.token
                        },
                        success: function(data) {
                            if (typeof data === 'object') {
                                if (!data.error) {
                                    for (var i in data.logs) {
                                        $('table > tbody > tr:first').before(data.logs[i]);
                                    }
                                    changePos(data.pos);
                                } else {
                                    toastr.error(data.message);
                                }
                            }


                        }
                    });
                }

                var refreshIntervalId = null;

                $('.log-live').click(function() {
                    $("i", this).toggleClass("fa-play fa-pause");

                    if (refreshIntervalId) {
                        $.admin.clearIntervalId(refreshIntervalId);
                        refreshIntervalId = null;
                    } else {
                        refreshIntervalId = setInterval(function() {
                            fetch();
                        }, 2000);
                        $.admin.addIntervalId(refreshIntervalId, false);
                    }
                });

                $('.log-delete').click(function() {
                    $.ajax({
                        url: '<?php echo $this->myTag->getUrl($this->view, 'delete', array('__SHOWBYIFRAME__' => 0, 'file' => $this->view->fileName)); ?>',
                        method: 'post',
                        data: {
                            _token: LA.token
                        },
                        success: function(data) {
                            if (typeof data === 'object') {
                                if (!data.error) {
                                    toastr.success(data.message);
                                    $.pjax.reload('#pjax-container');
                                } else {
                                    toastr.error(data.message);
                                }
                            }
                        }
                    });
                });
                $('.log-delete-all').click(function() {
                    $.ajax({
                        url: '<?php echo $this->myTag->getUrl($this->view, 'deleteall', array('__SHOWBYIFRAME__' => 0)); ?>',
                        method: 'post',
                        data: {
                            _token: LA.token
                        },
                        success: function(data) {
                            if (typeof data === 'object') {
                                if (!data.error) {
                                    toastr.success(data.message);
                                    $.pjax.reload('#pjax-container');
                                } else {
                                    toastr.error(data.message);
                                }
                            }
                        }
                    });
                });
            });
        </script>
        <div class="row">
            <!-- /.col -->
            <div class="col-md-10">
                <div class="box box-primary">
                    <h3><?php echo $this->view->fileName; ?></h3>
                    <div class="box-header with-border">
                        <button type="button" class="btn btn-primary btn-sm log-refresh"><i class="fa fa-refresh"></i> 刷新</button>
                        <a class="btn btn-primary btn-sm log-delete" href="javascript:void(0);">删除此文件</a>
                        <a class="btn btn-primary btn-sm log-delete-all" href="javascript:void(0);">删除所有文件</a>
                        <button type="button" class="btn btn-default btn-sm log-live"><i class="fa fa-play"></i> </button>
                        <div class="pull-right">
                            <div class="btn-group">
                                <?php if (!empty($this->view->prevUrl)) { ?>
                                    <a href="<?php echo $this->myTag->getUrl($this->view, 'list', $this->view->prevUrl); ?>" class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i></a>
                                <?php } ?>
                                <?php if (!empty($this->view->nextUrl)) { ?>
                                    <a href="<?php echo $this->myTag->getUrl($this->view, 'list', $this->view->nextUrl); ?>" class="btn btn-default btn-sm"><i class="fa fa-chevron-right"></i></a>
                                <?php } ?>
                            </div>
                            <!-- /.btn-group -->
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">

                        <div class="table-responsive">
                            <table class="table table-hover">

                                <thead>
                                    <tr>
                                        <th>Level</th>
                                        <th>Env</th>
                                        <th>Time</th>
                                        <th>Message</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <?php foreach ($this->view->logs as $index => $log) { ?>
                                        <tr>
                                            <td><span class="label bg-<?php echo $log['level_color']; ?>"><?php echo $log['level']; ?></span></td>
                                            <td><strong><?php echo $log['env']; ?></strong></td>
                                            <td style="width:150px;"><?php echo $log['time']; ?></td>
                                            <td><code style="word-break: break-all;"><?php echo $log['info']; ?></code></td>
                                            <td>
                                                <?php if (!empty($log['trace'])) { ?>
                                                    <a class="btn btn-primary btn-xs" data-toggle="collapse" data-target=".trace-<?php echo $index; ?>"><i class="fa fa-info"></i>&nbsp;&nbsp;Exception</a>
                                                <?php } ?>
                                            </td>
                                        </tr>

                                        <?php if (!empty($log['trace'])) { ?>
                                            <tr class="collapse trace-<?php echo $index; ?>">
                                                <td colspan="5">
                                                    <div style="white-space: pre-wrap;background: #333;color: #fff; padding: 10px;"><?php echo $log['trace']; ?></div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>

                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->
            </div>

            <div class="col-md-2">

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Files</h3>
                    </div>
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">

                            <?php foreach ($this->view->logFiles as $filename) { ?>
                                <li <?php if ($filename == $this->view->fileName) { ?>class="active" <?php } ?>>
                                    <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('file' => $filename)); ?>"><i class="fa fa-folder<?php if ($filename == $this->view->fileName) { ?>-open<?php } ?>"></i><?php echo $filename; ?></a>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>

                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Info</h3>
                    </div>
                    <?php if (!empty($this->view->fileName)) { ?>
                        <div class="box-body no-padding">
                            <ul class="nav nav-pills nav-stacked">
                                <li class="margin: 10px;">
                                    <a>Size: <?php echo $this->view->size; ?></a>
                                </li>
                                <li class="margin: 10px;">
                                    <a>Updated at: <?php echo $this->view->modified; ?></a>
                                </li>
                            </ul>
                        </div>
                    <?php } ?>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
    </div>
</div>