    
    <div class="help-left-part">
        <div class="help-nav">
            <h3>帮助中心</h3>
            <h4>新手指南</h4>
            <ul>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/index" class="cur01"><b></b>了解1元云购</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/questiondetail" class="cur02"><b></b>常见问题</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/agreement" class="cur03"><b></b>服务协议</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/userexperience" class="cur04"><b></b>会员福分经验值</a></li>
            </ul>
            <div class="hackbox"></div>
            <h4>服务保障</h4>
            <ul>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/genuinetwo" class="cur05"><b></b>1元云购保障体系</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/genuine" class="cur06"><b></b>正品承诺</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/securepayment" class="cur07"><b></b>安全支付</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/ship" class="cur08"><b></b>商品配送</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/suggestion" class="cur09"><b></b>投诉建议</a></li>
            </ul>
            <div class="hackbox"></div>
            <h4>商品配送</h4>
            <ul>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/deliveryfees" class="cur10"><b></b>配送费用</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/prodcheck" class="cur11"><b></b>商品验货与签收</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/shiptwo" class="cur12"><b></b>长时间未收到商品问题</a></li>
            </ul>
            <div class="hackbox"></div>
            <h4>关于云购</h4>
            <ul>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/about" class="cur13"><b></b>关于我们</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/jobs" class="cur14"><b></b>加入云购</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/business" target="_blank"><b></b>合作专区</a></li>
                <li><a href="javascript:;" target="_blank"><b></b>云购公益</a></li>
                <li><a href="javascript:;" target="_blank"><b></b>云购微博</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/contactus" class="cur16"><b></b>联系我们</a></li>
                <li><a href="<?php echo $this->view->baseUrl?>yungou/help/link" target="_blank"><b></b>友情链接</a></li>
            </ul>
            <div class="hackbox"></div>
        </div>
        <div class="help-contact">
            <p>如果不能在帮助内容中找到答案，或者您有其他建议、投诉，您还可以：</p>
            <ul>
                <li class="CustomerCon"><a id="btnLeftQQ" href="javascript:;" target="_blank" class="Customer"><b></b>在线客服</a></li>
                <li>电话客服热线(免长途费)</li>
                <?php $siteSettings=\App\Site\Helpers\SiteHelper::getSettings();?>
                <li class="tel"><span><?php echo $siteSettings['tel400']?></span></li>
                <li>邮件联系: <a href="mailto:Service@1yyg.com">Service@1yyg.com</a></li>
            </ul>
        </div>
    </div>
