<?php foreach ($schemas4Form as $key => $field) { ?>
    <?php
    if (empty($field['form']['is_show'])) {
        continue;
    }
    
    if (!array_key_exists($key, $this->view->row)) {//!isset($this->view->row[$key]) 
        $this->view->row[$key] = "";
        // echo json_encode($this->view->row,true);
        // echo $key;
    }

    $field['name'] = empty($field['form']['name']) ? $field['name'] : $field['form']['name'];
    $field['form']['placeholder'] = empty($field['form']['placeholder']) ? "输入 " . $field['name'] : $field['form']['placeholder'];
    // 如果没有编辑或新增的权限 那么所有的form表单上的控件只能只读
    if (!$isCando) {
        $field['form']['readonly'] = true;
    }

    if (empty($field['form']['partial'])) {
        //print_r($field);die('xxx');
        $prepend = "";
        $append = "";
        $value = "";
        $input_type = "text";
        if ($field['form']['input_type'] == "hidden") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/hidden');
            $this->partial('partials/form/display');
        } elseif ($field['form']['input_type'] == "textarea") {
            if ($field['data']['type'] == "json") {
                $value = empty($this->view->row[$key]) ? '{}' : (!is_string($this->view->row[$key]) ? \json_encode($this->view->row[$key]) : $this->view->row[$key]);
            } elseif ($field['data']['type'] == "array") {
                $value = empty($this->view->row[$key]) ? '[]' : (!is_string($this->view->row[$key]) ? \json_encode($this->view->row[$key]) : $this->view->row[$key]);
            } else {
                //$value = nl2br($this->view->row[$key]);
                $value = $this->view->row[$key];
            }
            $rows = 5;
            $this->partial('partials/form/textarea');
        } elseif ($field['form']['input_type'] == "ckeditor") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/editor');
        } elseif ($field['form']['input_type'] == "ueditor") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/ueditor');
        } elseif ($field['form']['input_type'] == "text") {
            $prepend = '<i class="fa fa-pencil fa-fw"></i>';
            $value = $this->view->row[$key];
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "password") {
            $prepend = '<i class="fa fa-eye-slash fa-fw"></i>';
            $value = $this->view->row[$key];
            $input_type = "password";
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "number") {
            $value = intval($this->view->row[$key]);
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "currency") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "decimal") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "datetimepicker") {
            $prepend = '<i class="fa fa-calendar fa-fw"></i>';
            $value = $this->view->row[$key];
            // $value = date("Y-m-d H:i:s", $this->view->row[$key]->sec);
            // if ($value == '0001-01-01 00:00:00' || $value == '0000-00-00 00:00:00') {
            //     $value = '';
            // }
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "icon") {
            $prepend = '<i class="fa fa-pencil fa-fw"></i>';
            $value = $this->view->row[$key];
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "radio") {
            $inline = true;
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            $this->partial('partials/form/radio');
        } elseif ($field['form']['input_type'] == "select") {
            $inline = true;
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            if (empty($field['form']['select']['multiple'])) {
                $this->partial('partials/form/select');
            } else {
                if (!is_array($this->view->row[$key])) {
                    // 先用json转换
                    $value = \json_decode($this->view->row[$key], true);
                    // 如果失败就用逗号分隔
                    if (empty($value)) {
                        $value = explode(',', $this->view->row[$key]);
                    }
                } else {
                    $value = $this->view->row[$key];
                }
                $this->partial('partials/form/multipleselect');
            }
        } elseif ($field['form']['input_type'] == "image" || $field['form']['input_type'] == "file") {
            $value = $this->view->row[$key];
            $this->partial('partials/form/file');
        } elseif ($field['form']['input_type'] == "multipleImage" || $field['form']['input_type'] == "multipleFile") {
            // $value = $this->view->row[$key];
            $sortable = true;
            $this->partial('partials/form/multiplefile');
        } else {
            $value = $this->view->row[$key];
            $this->partial('partials/form/input');
        }
    } else { ?>
        <?php $this->partial($field['form']['partial']); ?>
    <?php } ?>
<?php } ?>