<?php
$operation4Action1 = 'insert';
$operation4Action2 = 'add';
if ($this->view->actionName == 'edit') {
    $operation4Action1 = 'update';
    $operation4Action2 = 'edit';
}
$isCando = $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $operation4Action1) &&
    $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $operation4Action2) &&
    $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'list');
?>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->view->actionName == 'add' ? "创建" : "编辑"; ?>
                        <?php //echo $this->view->formName 
                        ?>
                    </h3>

                    <div class="box-tools">
                        <?php if ($this->view->actionName == 'edit') { ?>
                            <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'remove') && !$this->view->readonly) { ?>
                                <?php if ($this->view->is_show_delete_button) { ?>
                                    <div class="btn-group pull-right" style="margin-right: 5px">
                                        <a href="javascript:void(0);" class="btn btn-sm btn-danger 5e217e4051348-delete" title="删除">
                                            <i class="fa fa-trash"></i><span class="hidden-xs"> 删除</span>
                                        </a>
                                    </div>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'list')) { ?>
                            <div class="btn-group pull-right" style="margin-right: 5px">
                                <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array()); ?>" class="btn btn-sm btn-default" title="列表"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;列表</span></a>
                            </div>
                        <?php } ?>

                        <?php if ($this->view->actionName == 'edit') { ?>
                            <?php foreach ($this->view->formTools as $key => $tool) { ?>
                                <?php if (!empty($tool['is_show'])) { ?>
                                    <?php
                                    $is_show4FormTool = is_callable($tool['is_show']) ? $tool['is_show']($this->view->row) : true;
                                    ?>
                                    <?php if (!empty($is_show4FormTool)) { ?>
                                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action']) && !$this->view->readonly) { ?>
                                            <a style="margin-right: 5px" href="javascript:void(0);" class="btn btn-sm btn-primary form-tool-<?php echo $key ?>">
                                                <i class="fa <?php echo empty($tool['icon']) ? 'fa-coffee' : $tool['icon'] ?>"></i><?php echo $tool['title'] ?></a>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form id="form_sample_2" onsubmit="return false" action="<?php echo $this->view->form_act ?>" method="post" accept-charset="UTF-8" class="form-horizontal" pjax-container>
                    <?php if ($this->view->form_template == 'tabbedform') { ?>
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs nav-tabs">
                                <?php if (!empty($this->view->tabbedform_settings['tabs'])) {
                                    $isFirstTab = true; ?>
                                    <?php foreach ($this->view->tabbedform_settings['tabs'] as $idx => $tabInfo) { ?>
                                        <li _id="tab_<?php echo $idx ?>" <?php if ($isFirstTab) { ?>class=active<?php } ?>><a href="javascript:;"><?php echo $tabInfo['name'] ?></a></li>
                                    <?php
                                        $isFirstTab = false;
                                    } ?>
                                <?php } ?>
                                <li class="pull-right header"></li>
                            </ul>
                            <div class="tab-content">
                                <?php if (!empty($this->view->tabbedform_settings['tabs'])) {
                                    $isFirstTab = true; ?>
                                    <?php foreach ($this->view->tabbedform_settings['tabs'] as $idx => $tabInfo) { ?>
                                        <div class="tab-pane <?php if ($isFirstTab) { ?>active<?php } ?>" id="tab_<?php echo $idx ?>">
                                            <div class="box-body fields-group">
                                                <?php
                                                $schemas4Form = $this->view->schemas;
                                                $field4TabForm = empty($tabInfo['fields']) ? array() : $tabInfo['fields'];
                                                if ($isFirstTab) {
                                                    $field4TabForm = array_merge(array('_id', '__CREATE_TIME__', '__CREATE_USER_ID__', '__CREATE_USER_NAME__', '__MODIFY_TIME__', '__MODIFY_USER_ID__', '__MODIFY_USER_NAME__', '__REMOVED__', '__REMOVE_TIME__', '__REMOVE_USER_ID__', '__REMOVE_USER_NAME__'), $field4TabForm);
                                                }
                                                $this->partial('partials/formelement');
                                                ?>
                                                <input type="hidden" name="_tab[]" value="<?php echo $idx ?>" class="_form_" />
                                            </div>
                                        </div>
                                    <?php
                                        $isFirstTab = false;
                                    } ?>
                                <?php } ?>
                                <input type="hidden" name="_token" value="<?php echo $this->view->csrf_token ?>">
                                <!-- /.box-body -->
                                <?php
                                $buttons = array();
                                if ($isCando && !$this->view->readonly) {
                                    if ($this->view->is_show_edit_button) {
                                        $buttons[] = 'submit';
                                    }
                                    // $buttons[] = 'reset';
                                }
                                $submit_redirects = array();
                                $csrf_token = $this->view->csrf_token;
                                $this->partial('partials/form/footer');
                                ?>
                            </div>
                        </div>
                    <?php } else { ?>
                        <div class="box-body">
                            <div class="fields-group">
                                <div class="col-md-12">
                                    <?php
                                    $schemas4Form = $this->view->schemas;
                                    $this->partial('partials/formelement');
                                    ?>
                                </div>
                            </div>
                        </div>

                        <!-- /.box-body -->
                        <?php
                        $buttons = array();
                        if ($isCando) {// && !$this->view->readonly
                            if ($this->view->is_show_edit_button) {
                                $buttons[] = 'submit';
                            }
                            // $buttons[] = 'reset';
                        }
                        $submit_redirects = array();
                        $csrf_token = $this->view->csrf_token;
                        $this->partial('partials/form/footer');
                        ?>
                        <!-- /.box-footer -->
                    <?php } ?>
                </form>
            </div>

        </div>
    </div>
    <?php $this->partial("partials/js/form")
    ?>
</section>