<?php foreach ($schemas4Form as $key => $field) { ?>
    <?php
    // 如果不在tabbedform的tab中的话就不显示
    if ($this->view->form_template == 'tabbedform' && !in_array($key, $field4TabForm)) {
        continue;
    }
    if (empty($field['form']['is_show'])) {
        continue;
    }
    $rowInfo = $this->view->row;
    if (!array_key_exists($key, $rowInfo)) {
        $rowInfo[$key] = "";
    }
    $field['name'] = empty($field['form']['name']) ? $field['name'] : $field['form']['name'];
    $field['form']['placeholder'] = empty($field['form']['placeholder']) ? "输入 " . $field['name'] : $field['form']['placeholder'];
    // 如果没有编辑或新增的权限 那么所有的form表单上的控件只能只读
    if (!$isCando) {
        $field['form']['readonly'] = true;
    }
    $value = $rowInfo[$key];
    if (is_bool($value) && empty($value)) {
        $value = 0;
    }
    if (empty($field['form']['partial'])) {
        $input_type = "text";
        $otherclassList = array();
        $canCheckAll = false;
        $prepend = "";
        $append = "";
        $rows = 0;
        $options = array();
        $inline = true;
        $sortable = false;
        $rangeInfo = array();
        if ($field['form']['input_type'] == "hidden") {
            $this->partial('partials/form/hidden');
            $this->partial('partials/form/display');
        } elseif ($field['form']['input_type'] == "textarea") {
            if ($field['data']['type'] == "json") {
                $value = empty($value) ? '{}' : (!is_string($value) ? \json_encode($value) : $value);
            } elseif ($field['data']['type'] == "array") {
                $value = empty($value) ? '[]' : (!is_string($value) ? \json_encode($value) : $value);
            } else {
                //$value = nl2br($value);
            }
            $rows = 5;
            $this->partial('partials/form/textarea');
        } elseif ($field['form']['input_type'] == "ckeditor") {
            $this->partial('partials/form/editor');
        } elseif ($field['form']['input_type'] == "ueditor") {
            $this->partial('partials/form/ueditor');
        } elseif ($field['form']['input_type'] == "text") {
            if (empty($field['form']['content_type'])) {
                $prepend = '<i class="fa fa-pencil fa-fw"></i>';
            } else {
                if ($field['form']['content_type'] == 'email') {
                    $prepend = '<i class="fa fa-envelope fa-fw"></i>';
                } elseif ($field['form']['content_type'] == 'phone') {
                    $otherclassList = array('form-class-mobile');
                    $prepend = '<i class="fa fa-phone fa-fw"></i>';
                } elseif ($field['form']['content_type'] == 'url') {
                    $prepend = '<i class="fa fa-internet-explorer fa-fw"></i>';
                } elseif ($field['form']['content_type'] == 'ip') {
                    $otherclassList = array('form-class-ip');
                    $prepend = '<i class="fa fa-laptop fa-fw"></i>';
                } elseif ($field['form']['content_type'] == 'color') {
                    $otherclassList = array('form-class-colorpicker');
                    $prepend = '<i></i>';
                }
            }
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "password") {
            $prepend = '<i class="fa fa-eye-slash fa-fw"></i>';
            $input_type = "password";
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "number") {
            $otherclassList = array('form-class-number');
            $value = intval($value);
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "currency") {
            $prepend = '$';
            $otherclassList = array('form-class-currency');
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "decimal") {
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "datetimepicker") {
            $prepend = '<i class="fa fa-calendar fa-fw"></i>';
            if (empty($field['form']['content_type'])) {
                $otherclassList = array('form-class-datetime');
            } else {
                if ($field['form']['content_type'] == 'datetime') {
                    $otherclassList = array('form-class-datetime');
                } elseif ($field['form']['content_type'] == 'date') {
                    $otherclassList = array('form-class-date');
                } elseif ($field['form']['content_type'] == 'time') {
                    $prepend = '<i class="fa fa-clock-o fa-fw"></i>';
                    $otherclassList = array('form-class-time');
                }
            }
            if (!empty($field['form']['datetimepicker']['end']) || !empty($field['form']['datetimepicker']['start'])) {
                $otherclassList = array();
            }
            // $value = date("Y-m-d H:i:s", $value->sec);
            // if ($value == '0001-01-01 00:00:00' || $value == '0000-00-00 00:00:00') {
            //     $value = '';
            // }
            $this->partial('partials/form/input');
        } elseif (in_array($field['form']['input_type'], array("datetimerange", "daterange", "timerange"))) {
            $rangeInfo = $field['form'][$field['form']['input_type']];
            if (!empty($rangeInfo['name'])) {
                $field['name'] = $rangeInfo['name'];
            }
            $rangeInfo['start_value'] = '';
            $rangeInfo['end_value'] = '';
            $rangeInfo['start_placeholder'] = '';
            $rangeInfo['end_placeholder'] = '';
            foreach (array('start' => $rangeInfo['start'], 'end' => $rangeInfo['end']) as $rkey => $rangeField) {
                $fieldRange = $schemas4Form[$rangeField];
                $fieldRange['name'] = empty($fieldRange['form']['name']) ? $fieldRange['name'] : $fieldRange['form']['name'];
                $rangeInfo[$rkey . '_placeholder'] = empty($fieldRange['form']['placeholder']) ? "输入 " . $fieldRange['name'] : $fieldRange['form']['placeholder'];
                if (array_key_exists($rangeField, $this->view->row)) {
                    $rangeInfo[$rkey . '_value'] = $this->view->row[$rangeField];
                }
            }
            $this->partial('partials/form/' . $field['form']['input_type']);
        } elseif ($field['form']['input_type'] == "icon") {
            $prepend = '<i class="fa fa-pencil fa-fw"></i>';
            $otherclassList = array('form-class-iconpicker');
            $this->partial('partials/form/input');
        } elseif ($field['form']['input_type'] == "slider") {
            $otherclassList = array('form-class-slider');
            $this->partial('partials/form/slider');
        } elseif ($field['form']['input_type'] == "switch") {
            $otherclassList = array('form-class-switch');
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            $this->partial('partials/form/switchfield');
        } elseif ($field['form']['input_type'] == "radio") {
            $otherclassList = array('form-class-radio');
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            $this->partial('partials/form/radio');
        } elseif ($field['form']['input_type'] == "checkbox") {
            $otherclassList = array('form-class-checkbox');
            $canCheckAll = empty($field['form']['checkbox']['isCheckAll']) ? false : true;
            if (!is_array($value)) {
                // 先用json转换
                $value = \json_decode($value, true);
                // 如果失败就用逗号分隔
                if (empty($value)) {
                    $value = explode(',', $value);
                }
            }
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            $this->partial('partials/form/checkbox');
        } elseif ($field['form']['input_type'] == "select") {
            $options = is_callable($field['form']['items']) ? $field['form']['items']() : $field['form']['items'];
            if (empty($field['form']['select']['multiple'])) {
                $otherclassList = array('form-class-select');
                $this->partial('partials/form/select');
            } else {
                if (!is_array($value)) {
                    // 先用json转换
                    $value = \json_decode($value, true);
                    // 如果失败就用逗号分隔
                    if (empty($value)) {
                        $value = explode(',', $value);
                    }
                }
                $otherclassList = array('form-class-multipleselect');
                $this->partial('partials/form/multipleselect');
            }
        } elseif ($field['form']['input_type'] == "image" || $field['form']['input_type'] == "file") {
            $this->partial('partials/form/file');
        } elseif ($field['form']['input_type'] == "multipleImage" || $field['form']['input_type'] == "multipleFile") {
            $sortable = true;
            $this->partial('partials/form/multiplefile');
        } else {
            $this->partial('partials/form/input');
        }
    } else { ?>
        <?php $this->partial($field['form']['partial']); ?>
    <?php } ?>
<?php } ?>