<?php
$operation4Action1 = 'insert';
$operation4Action2 = 'add';
if ($this->view->actionName == 'edit') {
    $operation4Action1 = 'update';
    $operation4Action2 = 'edit';
}
$isCando = $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $operation4Action1) &&
    $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $operation4Action2) &&
    $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'list');
?>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->view->actionName == 'add' ? "创建" : "编辑"; ?>
                        <?php //echo $this->view->formName 
                        ?>
                    </h3>

                    <div class="box-tools">
                        <?php if ($this->view->actionName == 'edit') { ?>
                            <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'remove')) { ?>
                                <div class="btn-group pull-right" style="margin-right: 5px">
                                    <a href="javascript:void(0);" class="btn btn-sm btn-danger 5e217e4051348-delete" title="删除">
                                        <i class="fa fa-trash"></i><span class="hidden-xs"> 删除</span>
                                    </a>
                                </div>
                            <?php } ?>
                        <?php } ?>
                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'list')) { ?>
                            <div class="btn-group pull-right" style="margin-right: 5px">
                                <a href="<?php echo $this->view->list_url ?>" class="btn btn-sm btn-default" title="列表"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;列表</span></a>
                            </div>
                        <?php } ?>

                        <?php if ($this->view->actionName == 'edit') { ?>
                            <?php foreach ($this->view->formTools as $key => $tool) { ?>
                                <?php if (!empty($tool['is_show'])) { ?>
                                    <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action'])) { ?>
                                        <a style="margin-right: 5px" href="javascript:void(0);" class="btn btn-sm btn-primary form-tool-<?php echo $key ?>">
                                            <i class="fa <?php echo empty($tool['icon']) ? 'fa-coffee' : $tool['icon'] ?>"></i><?php echo $tool['title'] ?></a>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form id="form_sample_2" action="<?php echo $this->view->form_act ?>" method="post" accept-charset="UTF-8" class="form-horizontal" pjax-container="">
                    <div class="box-body">

                        <div class="fields-group">

                            <div class="col-md-12">
                                <?php
                                $schemas4Form = $this->view->schemas;
                                $this->partial('partials/formelement');
                                ?>
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <?php
                    $buttons = array();
                    if ($isCando) {
                        $buttons[] = 'submit';
                        // $buttons[] = 'reset';
                    }
                    $submit_redirects = array();
                    $csrf_token = $this->view->csrf_token;
                    $this->partial('partials/form/footer');
                    ?>
                    <!-- /.box-footer -->
                </form>
            </div>

        </div>
    </div>
    <?php $this->partial("partials/js/form")
    ?>
</section>