<?php echo $this->getContent(); ?>
<?php //die('list'); 
?>

<div class="row">
	<div class="col-md-12">
		<div class="box">

			<?php if (isset($title)) { ?>
				<div class="box-header with-border">
					<h3 class="box-title"> <?php echo $title ?></h3>
				</div>
			<?php } ?>

			<?php if (true || $grid->showTools() || $grid->showExportBtn() || $grid->showCreateBtn()) { ?>
				<div class="box-header with-border">
					<div class="pull-right">
						<!--{!! $grid->renderColumnSelector() !!}-->
						<?php //$this->partial("partials/grid/column_selector"); 
						?>

						<?php if (false && $grid->showExportBtn()) { ?>
							<!--{!! $grid->renderExportButton() !!}-->
							<?php //$this->partial("partials/grid/export_button"); 
							?>
						<?php } ?>

						<?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'add') && $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'insert') && !$this->view->readonly) { //|| $grid->showCreateBtn()
						?>
							<!--{!! $grid->renderCreateButton() !!}-->
							<?php $this->partial("partials/grid/create_button"); ?>
						<?php } ?>

					</div>

					<?php if (true || $grid->showTools()) { ?>
						<div class="pull-left">
							<!--{!! $grid->renderHeaderTools() !!}-->
							<div class="btn-group" style="margin-right: 5px" data-toggle="buttons">
								<label class="btn btn-sm btn-dropbox 5e280b9811ada-filter-btn" title="筛选">
									<input type="checkbox"><i class="fa fa-filter"></i><span class="hidden-xs">&nbsp;&nbsp;筛选</span>
								</label>
							</div>

							<?php foreach ($this->view->headerTools as $key => $tool) { ?>
								<?php if (!empty($tool['is_show']) && empty($tool['is_export'])) { ?>
									<?php
									$is_show4HeaderTool4NotExport = is_callable($tool['is_show']) ? $tool['is_show']() : true;
									?>
									<?php if (!empty($is_show4HeaderTool4NotExport)) { ?>
										<?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action']) && !$this->view->readonly) { ?>
											<a href="javascript:void(0);" class="btn btn-sm btn-primary header-tool-<?php echo $key ?>">
												<i class="fa <?php echo empty($tool['icon']) ? 'fa-coffee' : $tool['icon'] ?>"></i><?php echo $tool['title'] ?></a>
										<?php } ?>
									<?php } ?>
								<?php } ?>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
			<?php } ?>

			<!--{!! $grid->renderFilter() !!}-->
			<?php $this->partial("partials/search")
			?>
			<!--{!! $grid->renderHeader() !!}-->

			<!-- /.box-header -->
			<div class="box-body table-responsive no-padding">
				<table class="table table-hover" style="width:100%" id="example">
					<thead>
						<tr>
							<?php
							$idx = $orderIdx = 0;
							$orderBy = "desc";
							$isFirst = false;
							?>
							<?php foreach ($this->view->schemas as $key => $field) { ?>
								<?php if (!empty($field['list']['is_show'])) { ?>
									<?php
									if (!$isFirst && isset($this->view->defaultSort[$key])) {
										$orderIdx = $idx;
										$orderBy = ($this->view->defaultSort[$key] == -1) ? 'desc' : 'asc';
										$isFirst = true;
									}
									$idx++;
									?>
									<th <?php if (!empty($field['list']['width'])) { ?>width="<?php echo $field['list']['width'] ?>" <?php } ?>><?php echo isset($field['list']['name']) ? $field['list']['name'] : $field['name']; ?></th>
								<?php } ?>
							<?php } ?>
							<th>操作</th>
						</tr>
					</thead>
				</table>
				<?php $this->partial("partials/js/list")
				?>
			</div>
			<!-- /.box-body -->

			<?php
			if (!empty($this->view->partials4List)) {
				foreach ($this->view->partials4List as $partial) {
					$this->partial($partial);
				}
			}
			?>
		</div>
	</div>
</div>