<div class="modal" tabindex="-1" role="dialog" id="<?php echo $this->view->modal_id ?>">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php echo $this->view->title ?></h4>
            </div>
            <form>
                <div class="modal-body">
                    <?php
                    $isCando = true;
                    $schemas4Form = $this->view->fields;
                    $this->partial('partials/formelement');
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php $this->partial("partials/js/modal")
?>
<script>
    $(function() {
        if (typeof ModalComponents == 'object') {
            ModalComponents.init();
        }
    })
</script>