<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->

        <div class="user-panel">
            <div class="pull-left image">
                <!-- <img src="<?php echo empty($_SESSION['admin_user_info']['headimgurl']) ? $this->view->adminConfig->admin->default_avatar : $this->view->baseUrl . "service/file/index?upload_path=system/user&id={$_SESSION['admin_user_info']['headimgurl']}&w=50&h=50"; ?>" class="img-circle" alt="User Image"> -->
                <img src="<?php echo empty($_SESSION['admin_user_info']['headimgurl']) ? $this->view->adminConfig->admin->default_avatar : $this->myTag->getUploadFilePath('system/user',$_SESSION['admin_user_info']['headimgurl']); ?>" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p><?php echo $_SESSION['admin_name'] ?></p>
                <!-- Status -->
                <a href="javascript:;"><i class="fa fa-circle text-success"></i> 上线</a>
            </div>
        </div>

        <?php if (false && $this->view->adminConfig->admin->enable_menu_search) { ?>
            <!-- search form (Optional) -->
            <form class="sidebar-form" style="overflow: initial;" onsubmit="return false;">
                <div class="input-group">
                    <input type="text" autocomplete="off" class="form-control autocomplete" placeholder="Search...">
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                        </button>
                    </span>
                    <ul class="dropdown-menu" role="menu" style="min-width: 210px;max-height: 300px;overflow: auto;">
                        <?php if (!empty($menuLinks)) { ?>
                            <?php foreach ($menuLinks as $link) { ?>
                                <li>
                                    <a href="<?php echo $link['uri'] ?>"><i class="fa <?php echo $link['icon'] ?>"></i><?php echo $link['title'] ?></a>
                                </li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                </div>
            </form>
            <!-- /.search form -->
        <?php } ?>

        <!-- Sidebar Menu -->
        <?php $this->partial("partials/container/sidebar/sidebar_menu") ?>
        <!-- /.sidebar-menu -->
    </section>
</aside>