<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/Ionicons/css/ionicons.min.css">
<!-- jvectormap -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/jvectormap/jquery-jvectormap.css">
<!-- daterange picker -->
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-daterangepicker/daterangepicker.css">-->
<!-- bootstrap datepicker -->
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">-->
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/iCheck/all.css">
<!-- Bootstrap Color Picker -->
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">-->
<!-- Bootstrap time Picker -->
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/timepicker/bootstrap-timepicker.min.css">-->
<!-- Select2 -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/select2/dist/css/select2.min.css">
<!-- DataTables -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/AdminLTE.min.css">

<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/css/fileinput.min.css?v=4.5.2">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.css">
<!-- 
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.css">
 -->
<!-- 
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">

 -->
<!--
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.skinNice.css">
 -->
<!-- 
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/fontawesome-iconpicker/dist/css/fontawesome-iconpicker.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-duallistbox/dist/bootstrap-duallistbox.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/skin-blue.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/nprogress/nprogress.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/nestable/nestable.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/toastr/build/toastr.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap3-editable/css/bootstrap-editable.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/google-fonts/fonts.css">
-->

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<style>
    .form-group>label.asterisk:before {
        content: " *";
        color: red;
    }

    .fa-refresh:before {
        content: "\f021";
    }
</style>