<div class="row">
	<div class="col-md-12">
		<div class="box">

			<?php if (isset($title)) { ?>
				<div class="box-header with-border">
					<h3 class="box-title"> <?php echo $title ?></h3>
				</div>
			<?php } ?>

			<?php if (true || $grid->showTools() || $grid->showExportBtn() || $grid->showCreateBtn()) { ?>
				<div class="box-header with-border">

					<div class="pull-right">
						<!--{!! $grid->renderColumnSelector() !!}-->
						<?php //$this->partial("partials/grid/column_selector"); 
						?>

						<?php if (false && $grid->showExportBtn()) { ?>
							<!--{!! $grid->renderExportButton() !!}-->
							<?php //$this->partial("partials/grid/export_button"); 
							?>
						<?php } ?>

						<div class="btn-group pull-right grid-refresh-btn" style="margin-right: 10px">
							<a href="javascript:void(0);" class="btn btn-sm btn-success container-refresh" title="刷新">
								<i class="fa fa-refresh"></i><span class="hidden-xs">&nbsp;&nbsp;刷新</span>
							</a>
						</div>

						<?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'add') && $this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'insert') && !$this->view->readonly) { //|| $grid->showCreateBtn()
						?>
							<!--{!! $grid->renderCreateButton() !!}-->
							<?php $this->partial("partials/grid/create_button"); ?>
						<?php } ?>

					</div>

					<?php if (true || $grid->showTools()) { ?>
						<div class="pull-left">
							<!--{!! $grid->renderHeaderTools() !!}-->
							<!-- <div class="btn-group" style="margin-right: 5px" data-toggle="buttons">
								<label class="btn btn-sm btn-dropbox 5e280b9811ada-filter-btn" title="筛选">
									<input type="checkbox"><i class="fa fa-filter"></i><span class="hidden-xs">&nbsp;&nbsp;筛选</span>
								</label>
							</div> -->
							<div class="btn-group">
								<a class="btn btn-primary btn-sm tree-608a681952aa6-tree-tools" data-action="expand" title="展开">
									<i class="fa fa-plus-square-o"></i>&nbsp;展开
								</a>
								<a class="btn btn-primary btn-sm tree-608a681952aa6-tree-tools" data-action="collapse" title="收起">
									<i class="fa fa-minus-square-o"></i>&nbsp;收起
								</a>
							</div>
							<div class="btn-group">
								<a class="btn btn-info btn-sm tree-608a681952aa6-save" title="保存"><i class="fa fa-save"></i><span class="hidden-xs">&nbsp;保存</span></a>
							</div>
							<?php foreach ($this->view->headerTools as $key => $tool) { ?>
								<?php if (!empty($tool['is_show']) && empty($tool['is_export'])) { ?>
									<?php
									$is_show4HeaderTool4NotExport = is_callable($tool['is_show']) ? $tool['is_show']() : true;
									?>
									<?php if (!empty($is_show4HeaderTool4NotExport)) { ?>
										<?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action']) && !$this->view->readonly) { ?>
											<a href="javascript:void(0);" class="btn btn-sm btn-primary header-tool-<?php echo $key ?>">
												<i class="fa <?php echo empty($tool['icon']) ? 'fa-coffee' : $tool['icon'] ?>"></i><?php echo $tool['title'] ?></a>
										<?php } ?>
									<?php } ?>
								<?php } ?>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
			<?php } ?>

			<!--{!! $grid->renderFilter() !!}-->
			<?php $this->partial("partials/search")
			?>
			<!--{!! $grid->renderHeader() !!}-->

			<!-- /.box-header -->
			<div class="box-body table-responsive no-padding">
				<!-- <div class="box-header">
					<div class="btn-group">
						<a class="btn btn-primary btn-sm tree-608a681952aa6-tree-tools" data-action="expand" title="展开">
							<i class="fa fa-plus-square-o"></i>&nbsp;展开
						</a>
						<a class="btn btn-primary btn-sm tree-608a681952aa6-tree-tools" data-action="collapse" title="收起">
							<i class="fa fa-minus-square-o"></i>&nbsp;收起
						</a>
					</div>
				</div> -->
				<div class="dd" id="tree-608a681952aa6">
					<?php $this->partial("partials/tree"); ?>
				</div>
				<?php $this->partial("partials/js/list") ?>
			</div>
			<!-- /.box-body -->
		</div>
	</div>
</div>