
<?php
$fields4RowList = array();
// 第一行的
$fields4Row1 = array();
$fields4Row1[] = array(
  'width' => 12,
  'element' => 'index/partials/index/row1'
);
$fields4RowList[] = $fields4Row1;

// 第二行的
$fields4Row2 = array();
$fields4Row2[] = array(
  'width' => 4,
  'element' => 'index/partials/index/row2'
);
$fields4Row2[] = array(
  'width' => 4,
  'element' => 'index/partials/index/row3'
);
$fields4Row2[] = array(
  'width' => 4,
  'element' => 'index/partials/index/row4'
);
$fields4RowList[] = $fields4Row2;

// 循环显示所有的行
foreach ($fields4RowList as $fields4Row) {
  $this->partial('partials/form/row');
}
?>
