<!DOCTYPE html>
<html>
<?php
$this->view->csrf_token = createRandCode(40);
$_SESSION['csrf_token'] = $this->view->csrf_token;
?>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?php echo  $this->view->adminConfig->admin->name ?> | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <?php $this->partial("partials/styles") ?>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body class="hold-transition login-page" <?php if ($this->view->adminConfig->admin->login_background_image) { ?>style="background: <?php echo $this->view->adminConfig->admin->login_background_image ?> no-repeat;background-size: cover;" <?php } ?>>
  <div class="login-box">
    <div class="login-logo">
      <a href="javascript:;"><?php echo !empty($this->view->adminConfig->admin->logo) ? $this->view->adminConfig->admin->logo : $this->view->adminConfig->admin->title ?></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg">登录</p>
      <form id="login_form1" class="login-form" action="<?php echo $this->view->form_act ?>" method="post">
        <div id="login_form_group1" class="form-group has-feedback">
          <label id="login_form_error1" class="control-label" for="inputError" style="display: none;"><i class="fa fa-times-circle-o"></i>These credentials do not match our records.</label><br />
          <!--<input type="email" class="form-control" placeholder="Email">-->
          <input type="text" class="form-control" placeholder="用户名" name="username" value="" required="1" data-value="">
          <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="password" class="form-control" placeholder="密码" name="password" required="1" data-value="">
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox" name="remember" value="1" checked> 记住我
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <input type="hidden" name="_token" value="<?php echo $this->view->csrf_token ?>">
            <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <!--
      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
          Facebook</a>
        <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
          Google+</a>
      </div>
      -->
      <!-- /.social-auth-links -->
      <!--
      <a href="#">I forgot my password</a><br>
      <a href="register.html" class="text-center">Register a new membership</a>
      -->
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <?php $this->partial("partials/js") ?>

  <?php $this->partial("{$this->view->controllerName}/partials/js/login") ?>
  <script>
    $(function() {
      $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' /* optional */
      });
      Login.init();
    });
  </script>
</body>

</html>