<?php

use App\Backend\Submodules\System\Models\Menu;

$requestUrl = $this->view->moduleName . '/' . $this->view->controllerName;
$menu_list = !empty($_SESSION['roleInfo']) ? $_SESSION['roleInfo']['menu_list'] : array();

$is_active4index = ($requestUrl == 'admin/index') ? true : false;

// 角色判断,当用户角色为非超级管理员时，进行权限判断
if (isset($_SESSION['admin_id'])) {
	$roleAlias = $_SESSION['roleInfo']['alias'];
} else {
	$roleAlias = 'guest';
}
$modelMenu = new Menu();
$menus = $modelMenu->getPrivilege($menu_list, $requestUrl);
?>

<ul class="sidebar-menu tree" data-widget="tree">
	<li class="header">菜单</li>
	<li class="<?php if (!empty($is_active4index)) { ?>active<?php } ?> " style=" height: auto;">
		<a href="<?php echo $this->view->baseUrl ?>admin/index/index">
			<i class="fa fa-bar-chart"></i> <span>首页</span>
		</a>
	</li>

	<?php $index = 0; ?>
	<?php foreach ($menus as $menukey => $menu) { ?>
		<?php if (($roleAlias == 'superAdmin') || !empty($menu['cando'])) { ?>
			<li class="<?php if (!empty($menu['is_active'])) { ?>active<?php } ?> treeview <?php if (!empty($menu['is_active'])) { ?>menu-open<?php } ?>" style="height: auto;">
				<a href="javascript:;">
					<i class="fa <?php echo empty($menu['icon'])?'fa-share':$menu['icon'] ?>"></i> <span><?php echo ($menu['name']) ?></span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<?php $index2 = 0; ?>
				<ul class="treeview-menu">
					<?php foreach ($menu['priv'] as $priv) { ?>
						<?php if (($roleAlias == 'superAdmin') || !empty($priv['cando'])) { ?>
							<?php if (false) { ?>
								<li <?php if (!empty($priv['is_active'])) { ?>class="active" <?php } ?>><a href="javascript:;"><i class="fa <?php echo empty($priv['icon'])?'fa-circle-o':$priv['icon'] ?>"></i> <?php echo ($priv['name']) ?></a></li>
								<li class="treeview">
									<a href="javascript:;"><i class="fa <?php echo empty($priv['icon'])?'fa-circle-o':$priv['icon'] ?>"></i> Level One
										<span class="pull-right-container">
											<i class="fa fa-angle-left pull-right"></i>
										</span>
									</a>
									<ul class="treeview-menu">
										<li><a href="javascript:;"><i class="fa fa-circle-o"></i> Level Two</a></li>
										<li class="treeview">
											<a href="javascript:;"><i class="fa fa-circle-o"></i> Level Two
												<span class="pull-right-container">
													<i class="fa fa-angle-left pull-right"></i>
												</span>
											</a>
											<ul class="treeview-menu">
												<li><a href="javascript:;"><i class="fa fa-circle-o"></i> Level Three</a></li>
												<li><a href="javascript:;"><i class="fa fa-circle-o"></i> Level Three</a></li>
											</ul>
										</li>
									</ul>
								</li>
							<?php } else { ?>
								<li <?php if (!empty($priv['is_active'])) { ?>class="active" <?php } ?>><a href="<?php echo $this->view->baseUrl ?><?php echo $priv['url'] ?>"><i class="fa <?php echo empty($priv['icon'])?'fa-circle-o':$priv['icon'] ?>"></i> <?php echo ($priv['name']) ?></a></li>
							<?php } ?>
						<?php } ?>
						<?php $index2++ ?>
					<?php } ?>
				</ul>
			</li>
		<?php } ?>
		<?php $index++ ?>
	<?php } ?>
</ul>