<ul class="sidebar-menu tree" data-widget="tree">
	<li class="header">菜单</li>
	<li class="<?php if (!empty($this->view->is_active4index)) { ?>active<?php } ?> " style=" height: auto;">
		<a href="<?php echo $this->view->baseUrl ?>admin/index/index">
			<i class="fa fa-bar-chart"></i> <span>首页</span>
		</a>
	</li>

	<?php $index = 0; ?>
	<?php foreach ($this->view->menus as $menukey => $menu) { ?>
		<?php
		$this->partial('partials/container/sidebar/menu')
		?>
		<?php $index++ ?>
	<?php } ?>
</ul>