<div class="row">
    <div class="col-md-12">
        <div class="callout callout-info">
            <h4>Markdown Editor</h4>
            <a href="https://github.com/laravel-admin-extensions/simplemde" target='_blank'>https://github.com/laravel-admin-extensions/simplemde</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Markdown Editor</h3>
                <div class="box-tools pull-right">
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body" style="display: block;">
                <form method="POST" action="" class="form-horizontal" accept-charset="UTF-8" pjax-container="1">
                    <div class="box-body fields-group">

                        <div class="form-group  ">

                            <label for="content" class="col-sm-2  control-label">Content</label>

                            <div class="col-sm-8 simplemde-609cfcbf22779">


                                <textarea id="content"></textarea>

                                <input type="hidden" name="content" value="" />


                            </div>
                        </div>

                        <style>
                            .simplemde-609cfcbf22779 .editor-toolbar.fullscreen,
                            .simplemde-609cfcbf22779 .CodeMirror-fullscreen {
                                z-index: 10000 !important;
                            }

                            .simplemde-609cfcbf22779 .CodeMirror {
                                height: 300px;
                            }
                        </style>

                    </div>

                    <input type="hidden" name="_token" value="bpeOq7hhCi1QONgd42hXCGfU3jhH4xzV8afQM7tM">

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="col-md-2"></div>

                        <div class="col-md-8">
                            <div class="btn-group pull-left">
                                <button type="reset" class="btn btn-warning pull-right">重置</button>
                            </div>

                            <div class="btn-group pull-right">
                                <button type="submit" class="btn btn-info pull-right">提交</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div><!-- /.box-body -->
        </div>

        <script>

        </script>
    </div>
</div>

<script data-exec-on-popstate>
    $(function() {
        var options = {
            element: $("#content")[0]
        };

        Object.assign(options, []);

        var simplemde_609cfcbf2278e = new SimpleMDE(options);

        simplemde_609cfcbf2278e.codemirror.on("change", function() {
            var html = simplemde_609cfcbf2278e.value();
            $('input[name=content]').val(html);
        });

    });
</script>