        <div class="g-links">            
            <a href="<?php echo $this->view->baseUrl?>" target="_blank" title="首页">首页</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/about" target="_blank" title="关于集资购">关于集资购</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/privacy" target="_blank" title="隐私声明">隐私声明</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/business" target="_blank" title="合作专区">合作专区</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/link" target="_blank" title="友情链接">友情链接</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/jobs" target="_blank" title="加入集资购">加入集资购</a><s></s>
            <a href="<?php echo $this->view->baseUrl?>yungou/help/contactus" target="_blank" title="联系我们">联系我们</a>
        </div>