<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <textarea <?php if (!empty($field['form']['readonly'])) { ?>readonly <?php } ?><?php if ($field['validation']['required']) { ?>required="1" <?php } ?> class="form-control <?php echo $key ?>" id="<?php echo $key ?>" name="<?php echo $key ?>" placeholder="<?php echo $field['form']['placeholder']; ?>"><?php echo $value ?></textarea>

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>
