<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <input <?php if (false && $field['validation']['required']) { ?>required="1" <?php } ?> type="file" class="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo $value ?>"/>

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>