<div class="<?php echo $this->view->viewClass['form-group'] ?>">
    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">
        <input type="text" id="<?php echo $key ?>" name="<?php echo $key ?>" value="{{$value}}" class="form-control" readonly {!! $attributes !!} />

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>