<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <div class="input-group">

            <?php if (!empty($prepend)) { ?>
                <span class="input-group-addon"><?php echo $prepend ?></span>
            <?php } ?>

            <input <?php if (!empty($field['form']['readonly'])) { ?>readonly <?php } ?> <?php if ($field['validation']['required']) { ?>required="1" <?php } ?> type="<?php echo $input_type ?>" id="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo $value ?>" class="form-control <?php echo $key ?>" placeholder="<?php echo $field['form']['placeholder']; ?>">

            <?php if (!empty($append)) { ?>
                <span class="input-group-addon clearfix"><?php echo $append ?></span>
            <?php } ?>

        </div>

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>