<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <select <?php if (!empty($field['form']['readonly'])) { ?>disabled data-disable=true<?php } ?><?php if ($field['validation']['required']) { ?>required="1" <?php } ?> class="form-control <?php echo empty($otherclassList) ? '' : implode(' ', $otherclassList) ?>" style="width: 100%;" name="<?php echo $key ?>[]" multiple="multiple" data-placeholder="<?php echo $field['form']['placeholder']; ?>" data-value="<?php echo empty($value) ? '' : implode(',', $value) ?>">
            <?php foreach ($options as $select => $option) { ?>
                <option value="<?php echo $select ?>" <?php if (in_array($select, $value)) { ?>selected<?php } ?>><?php echo $option ?></option>
            <?php } ?>
        </select>
        <input type="hidden" name="<?php echo $key ?>[]" />

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>