<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <input type="file" class="{{$class}}" name="<?php echo $key ?>[]" {!! $attributes !!} />
        @isset($sortable)
        <input type="hidden" class="{{$class}}_sort" name="{{ $sort_flag."[$name]" }}"/>
        @endisset

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>
