<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>
        <?php if (!empty($options)) { ?>
            <?php foreach ($options as $option => $label) { ?>

                <?php echo !empty($inline) ? '<span class="icheck">' : '<div class="radio icheck">'; ?>

                <label <?php if (!empty($inline)) { ?>class="radio-inline" <?php } ?>>
                    <?php if (isset($label['value'])) { ?>
                        <input <?php if (!empty($field['form']['readonly'])) { ?>disabled <?php } ?><?php if ($field['validation']['required']) { ?>required="1" <?php } ?> type="radio" name="<?php echo $key ?>" value="<?php echo $label['value'] ?>" class="minimal <?php echo empty($otherclassList) ? '' : implode(' ', $otherclassList) ?> <?php echo $key ?> radio-<?php echo $key ?>" <?php if ($value == $label['value']) { ?>checked<?php } ?> />&nbsp;<?php echo $label['name'] ?>&nbsp;&nbsp;
                    <?php } else { ?>
                        <input <?php if (!empty($field['form']['readonly'])) { ?>disabled <?php } ?><?php if ($field['validation']['required']) { ?>required="1" <?php } ?> type="radio" name="<?php echo $key ?>" value="<?php echo $option ?>" class="minimal <?php echo empty($otherclassList) ? '' : implode(' ', $otherclassList) ?> <?php echo $key ?> radio-<?php echo $key ?>" <?php if ($value == $option) { ?>checked<?php } ?> />&nbsp;<?php echo $label ?>&nbsp;&nbsp;
                    <?php } ?>
                </label>

                <?php echo !empty($inline) ? '</span>' : '</div>'; ?>
            <?php } ?>
        <?php } ?>

        <?php if (!empty($field['form']['readonly'])) { ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>">
        <?php } ?>
        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>