<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <input type="hidden" name="<?php echo $key ?>" />

        <select class="form-control <?php echo $key ?>" style="width: 100%;" name="<?php echo $key ?>">
            <?php if (!empty($groups)) { ?>
                <?php foreach ($groups as $group) { ?>
                    <optgroup label="<?php echo $group['label']  ?>">
                        <?php foreach ($group['options'] as $select => $option) { ?>
                            <option value="<?php echo $select ?>" <?php if (($select == $this->view->row[$key])) { ?>selected<?php } ?>><?php echo $option ?></option>
                        <?php } ?>
                    </optgroup>
                <?php } ?>
            <?php } else { ?>
                <option value=""></option>
                <?php foreach ($options as $select => $option) { ?>
                    <option value="<?php echo $select ?>" <?php if (($select == $this->view->row[$key])) { ?>selected<?php } ?>><?php echo $option ?></option>
                <?php } ?>
            <?php } ?>
        </select>

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>