<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <input <?php if (!empty($field['form']['readonly'])) { ?> readonly data-disable=true <?php } ?> <?php if ($field['validation']['required']) { ?>required="1" <?php } ?> type="text" class="<?php echo empty($otherclassList) ? '' : implode(' ', $otherclassList) ?>" name="<?php echo $key ?>" value="<?php echo $value ?>" data-from="<?php echo $value ?>" <?php if (isset($field['form']['slider']['min'])) { ?>data-min="<?php echo $field['form']['slider']['min'] ?>" <?php } ?> <?php if (isset($field['form']['slider']['max'])) { ?>data-max="<?php echo $field['form']['slider']['max'] ?>" <?php } ?> />

        <?php if (!empty($field['form']['readonly'])) { ?>
            <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>">
        <?php } ?>
        
        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>