<div class="<?php echo $this->view->viewClass['form-group'] ?> <?php echo (empty($errors) || !$errors->has($errorKey)) ? '' : 'has-error' ?>">

    <label for="<?php echo $key ?>" class="<?php echo $this->view->viewClass['label'] ?> <?php if ($field['validation']['required']) { ?>asterisk<?php } ?> control-label"><?php echo $field['name'] ?></label>

    <div class="<?php echo $this->view->viewClass['field'] ?>">

        <?php $this->partial('partials/form/error'); ?>

        <input <?php if (!empty($field['form']['readonly'])) { ?>disabled <?php } ?> <?php if ($field['validation']['required']) { ?>required="1" <?php } ?> type="checkbox" class="<?php echo empty($otherclassList) ? '' : implode(' ', $otherclassList) ?> <?php echo $key ?> <?php echo $key ?>-switch" <?php if (intval($value) == 1) { ?>checked<?php } ?> />
        <input type="hidden" class="<?php echo $key ?>" name="<?php echo $key ?>" value="<?php echo $value ?>" />

        <?php $this->partial('partials/form/help-block'); ?>

    </div>
</div>