<?php $siteSettings=\App\Site\Views\Helpers\SiteHelper::getSettings();?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $siteSettings['title']?>--会员中心</title>    
    <base href="<?php echo $this->view->resourceUrl?>" />
    <link rel="stylesheet" type="text/css" href="../yungou/css/header.css" />
    <link rel="stylesheet" type="text/css" href="css/base.css" />
    <link rel="stylesheet" type="text/css" href="/CSS/pagination.css" />
</head>
<body>
<div class="wrapper">
    <!--顶部-->
    <div class="g-toolbar clrfix">
        <div class="w1190">
            <ul class="fl">
                <li class="f-collect">
                  <div class="u-menu-hd">
                      <a id="btnTFavorite" href="javascript:;" title="收藏">收藏</a>
                  </div>
                </li>
                <li class="f-gap"><s></s></li>
                <li id="liMobile" class="u-arr">
                  <div class="u-menu-hd transparent-png">
                      <a href="<?php echo $this->view->baseUrl?>mobile.html" target="_blank" title="手机云购">手机云购</a>
                      <div class="f-top-arrow"><cite>◆</cite><b>◆</b></div>
                  </div>
                  <div class="u-select">
                      <p>
                          <a href="<?php echo $this->view->baseUrl?>mobile.html" target="_blank">
                              <img src="images/andriod.jpg">
                              下载客户端
                          </a>
                      </p>
                  </div>
                </li>
                <li class="f-gap" style="display:none;"><s></s></li>
                <li id="liCCTV" style="display:none;">
                  <a href="javascript:;" target="_blank" class="cctv-icon">
                      <img src="/Images/cctv-icon.jpg" alt="央视网" width="80" height="35" class="cctv-icon-img">
                      <span class="cctv-icon-txt">广告合作伙伴</span>
                  </a>
                </li>
            </ul>
            <?php                
                $loginName = \App\Member\Views\Helpers\MemberHelper::getLoginName($this->view->memberInfo);
            ?>
            <ul id="ulTopRight" class="fr"><li><div class="u-menu-hd u-menu-login"><a href="<?php echo $this->view->baseUrl?>member/index/index" title="<?php echo $loginName?>" class="blue"><span class="fl"><img src="/Images/UserFace-25-0000.jpg"><s class="transparent-png"></s></span><?php echo $loginName?></a><a href="<?php echo $this->view->baseUrl?>member/passport/logout" title="退出">[退出]</a></div></li><li class="f-gap"><s></s></li>
                <li id="liMember" class="u-arr-1yyg" style="display: none;">
                  <div class="u-menu-hd">
                      <a href="<?php echo $this->view->baseUrl?>member/index/index" title="我的1元云购">我的1元云购</a>
                      <div class="f-top-arrow"><cite>◆</cite><b>◆</b></div>
                  </div>
                  <div class="u-select">
                      <span><a href="<?php echo $this->view->baseUrl?>member/index/userbuylist" title="云购记录">云购记录</a></span>
                      <span><a href="<?php echo $this->view->baseUrl?>member/index/orderlist" title="获得的商品">获得的商品</a></span>
                      <span><a href="<?php echo $this->view->baseUrl?>member/admin/membermodify" title="个人设置">个人设置</a></span>
                  </div>
                </li>
                <li class="f-gap" style="display: none;"><s></s></li>
                <li id="liHome" style="">
                  <div class="u-menu-hd">
                      <a href="<?php echo $this->view->baseUrl?>member/index/index" title="我的1元云购">我的1元云购</a>
                  </div>
                </li>
                <li class="f-gap" style=""><s></s></li>

                <li class="f-gap" style="display: none;"><s></s></li>
                <li>
                  <div class="u-menu-hd">
                      <a href="<?php echo $this->view->baseUrl?>member/index/userrecharge" title="充值">充值</a>
                  </div>
                </li>
                <li class="f-gap"><s></s></li>
                <li>
                  <div class="u-menu-hd">
                      <a href="<?php echo $this->view->baseUrl?>yungou/help/index" title="帮助">帮助</a>
                  </div>
                </li>
                <li class="f-gap"><s></s></li>
                <li>
                  <div class="u-menu-hd">
                      <a href="<?php echo $this->view->baseUrl?>yungou/help/contactus" title="投诉">投诉</a>
                  </div>
                </li>
                <li class="f-gap" style=""><s></s></li>
                <li id="lizxkf" class="f-zxkf" style="display: none;">
                  <div class="u-menu-hd">
                      <a id="btnTopQQ" href="javascript:;" title="在线客服" class="u-service u-service-on"><i></i>在线客服</a>
                  </div>
                </li>
                <li class="f-zxkf" style="">
                 <div class="u-menu-hd">
                     <a href="<?php echo $this->view->baseUrl?>yungou/index/index" title="1元云购首页" class="orange">1元云购首页</a>
                 </div>
                </li>
            </ul>
        </div>
    </div>
    <!--头部-->
        
    <!--导航-->
    <div class="p-center-nav clrfix">
        <div class="banner-middle clrfix">
            <div class="nav-new">
                <ul>
                    <li <?php if($this->view->controllerName=='index'){?>class="curr"<?php }?>><a href="<?php echo $this->view->baseUrl?>member/index/index" title="我的1元云购">我的1元云购</a><em class="z-my-1yyg u-personal"></em></li>
                    <li <?php if($this->view->controllerName=='admin'){?>class="curr"<?php }?>><a href="<?php echo $this->view->baseUrl?>member/admin/membermodify" title="账号设置">账号设置</a><em class="z-account-settings u-personal"></em></li>
                    <li><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $_SESSION['member_id']?>" title="个人主页">个人主页</a><em class="z-home-page u-personal"></em></li>
                </ul>
            </div>
            <div class="nav-return">
                <a href="/" class="transparent-png"></a>
            </div>
        </div>
        <div class="banner-right"></div>
    </div>
    <!--右侧工具栏-->
    <div id="divMemberRTool" class="g-narrow-con member-narrow" style="display:block">
        <div class="m-narrow-list" style="height:232px;">
            <ul>
                <li class="f-customer-service" id="li_customer_service"><!--客服-->
                    <div class="u-float-list">
                        <a href="javascript:;" class="z-customer-on"><s></s><em class="orange">在<br>线<br>客<br>服</em></a><!-- z-customer-off 客服不在线时 -->
                    </div>
                </li>
                <li class="f-member-cart f-member-cart2"><!--购物车-->
                    <div class="u-float-list">
                        <a href="<?php echo $this->view->baseUrl?>yungou/cart/list" target="_blank">
                            <em style="display:none" id="rightCartNum">0</em>
                            <s class="u-personal"></s>
                            <cite style="display:none;">购<br>物<br>车</cite>
                        </a>
                    </div>
                </li>
                <li class="f-feedback"><!--意见反馈-->
                    <div class="u-float-list">
                        <a href="<?php echo $this->view->baseUrl?>htm-suggestion.html" target="_blank"><i></i><cite>意见反馈</cite></a>
                    </div>
                </li>
                <li class="f-back-to" style="display:none;"><!--Top-->
                    <div class="u-float-list">
                        <a href="javascript:;"><i></i><cite>置顶</cite></a>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div class="p-center-main clrfix">
        <!--左边导航-->        
        <?php echo $this->getContent(); ?>
    </div>

    <!--版权-->
    <div class="g-copyrightCon">
        <div class="w1190">
            <?php $this->partial("partials/g_links") ?>
            <?php $this->partial("partials/g_copyright") ?>
            <div class="g-authentication">
                <a href="javascript:;" target="_blank" class="fi_ectrustchina"></a>
                <a href="javascript:;" target="_blank" class="fi_315online"></a>
                <a href="javascript:;" target="_blank" class="fi_qh"></a>
                <a href="javascript:;" target="_blank" class="fi_cnnic"></a>
                <a href="javascript:;" target="_blank" class="fi_anxibao"></a>
                <a href="javascript:;" target="_blank" class="fi_pingan"></a>
                <a href="javascript:;" target="_blank" class="fi_yangshi"></a>
            </div>
        </div>
    </div>
</div>

<!-- 弹层开始 -->
<link rel="stylesheet" type="text/css" href="/CSS/pageDialog.css" /> 
<div class="pageDialogBG" id="pageDialogBG"></div>
<!-- <div class="pageDialogBorder" id="pageDialogBorder"></div> -->
<div class="pageDialog" id="pageDialog">
    <div class="pageDialogClose" id="pageDialogClose" title="关闭"></div>
    <div class="pageDialogMain" id="pageDialogMain">
        <div class="content"></div>
    </div>
</div>
<!-- 弹层结束 -->
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/memberindex.js"></script>
</body>
</html>