<script>
  function LA() {}
  LA.token = "<?php echo $_SESSION['csrf_token'] ?>";
</script>
<!-- REQUIRED JS SCRIPTS -->
<script src="<?php echo $this->view->resourceUrl ?>bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>dist/js/app.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../jquery-pjax/jquery.pjax.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../nprogress/nprogress.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../nestable/jquery.nestable.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/iCheck/icheck.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.bundle.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../moment/min/moment-with-locales.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/canvas-to-blob.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/fileinput.min.js?v=4.5.2"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/select2/select2.full.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../number-input/bootstrap-number-input.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../fontawesome-iconpicker/dist/js/fontawesome-iconpicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/sortable.min.js?v=4.5.2"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-duallistbox/dist/jquery.bootstrap-duallistbox.min.js"></script>

<!-- ckeditor start -->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ckeditor/ckeditor.js"></script>
<!-- ckeditor end -->

<!-- ueditor start -->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/third-party/zeroclipboard/ZeroClipboard.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.all.min.js"> </script>
<!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
<!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/lang/zh-cn/zh-cn.js"></script>
<!-- ueditor end -->

<!-- DataTables -->
<script src="<?php echo $this->view->resourceUrl ?>../datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

<script src="<?php echo $this->view->resourceUrl ?>../jquery-validation/jquery.validate.min.js"></script>

<!-- page script -->
<?php $this->partial("partials/js/app") ?>

<script>
  $(function() {

    if (typeof App == 'object') {
      App.init();
    }
    if (typeof Search == 'object') {
      Search.init();
    }
    if (typeof List == 'object') {
      List.init();
    }
    //FormValidation.init();
    if (typeof FormComponents == 'object') {
      FormComponents.init();
    }
  })
</script>
<?php $this->partial("partials/toastr") ?>