<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/iCheck/all.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/css/fileinput.min.css?v=4.5.2">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.skinNice.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../fontawesome-iconpicker/dist/css/fontawesome-iconpicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-duallistbox/dist/bootstrap-duallistbox.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/skin-blue.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../nprogress/nprogress.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../nestable/nestable.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap3-editable/css/bootstrap-editable.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../google-fonts/fonts.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/AdminLTE.min.css">

<script src="<?php echo $this->view->resourceUrl ?>plugins/jQuery/jQuery-2.1.4.min.js"></script>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->