    <div class="g-logo-top">
        <a href="/" class="transparent-png fl"><img src="images/logo.png"></a>
        <span class="fr">想起来了？<a id="hylinkLoginPage" class="blue" href="<?php echo $this->view->baseUrl?>member/passport/login">立即登录</a></span>
    </div>

    <div class="g-contentCon clrfix">
        <div class="sign-success clrfix">
            <i class="passport-icon"></i>
            <span>恭喜您，密码设置成功！</span>
            <a id="a_go" href="<?php echo $this->view->baseUrl?>member/passport/login" class="orange"><em>立即登录</em>（3秒）</a>
        </div>
    </div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/login.js"></script>
