    <input type="hidden" id="mobileEmail" value="<?php echo !empty($_SESSION['member_mobile'])?'mobile':'email'?>">
    <div class="g-logo-top">
        <a href="/" class="transparent-png fl"><img src="images/logo.png"></a>
        <span class="fr">已有账号？<a id="hylinkLoginPage" class="blue" href="<?php echo $this->view->baseUrl?>member/passport/login">立即登录</a></span>
    </div>

    <div class="g-contentCon clrfix">
        <div class="m-main clrfix">
            <h2 class="gray3">验证信息</h2>
            <div class="security-code-con clrfix">
                <dl>
                    <dt>验证码已发送至<b class="blue"><?php echo !empty($_SESSION['member_mobile'])?$_SESSION['member_mobile']:$_SESSION['member_email']?></b><a id="hylinkRegisterPageA" href="<?php echo $this->view->baseUrl?>member/passport/register">更换</a></dt>
                    <dd class="code-form">
                        <input id="txtCode" type="text" maxlength="6" class="iptfocus" me="<?php echo !empty($_SESSION['member_mobile'])?$_SESSION['member_mobile']:$_SESSION['member_email']?>"><a id="btnSend" href="javascript:;">重新发送</a>
                         <em style="" class="iptem">请输入6位验证码</em>
                        <span class="orange" style="display:none;"></span>
                    </dd>
                    <dd><a id="btnSubmitRegistercheck" href="javascript:;" class="z-agreeBtn">提交</a></dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="g-contentCon clrfix" style="display:none;">
        <div class="sign-success clrfix">
            <i class="passport-icon"></i>
            <span>恭喜您，注册成功！</span>
            <p>您现在可以通过<b class="blue">793671@qq.com</b>进行登录和收取获得商品的信息</p>
            <a href="/" class="orange" id="a_go"><em>立即1元云购</em>（1秒）</a>
        </div>
    </div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/login.js"></script>