<script>
  function LA() {}
  LA.token = "<?php echo $this->view->csrf_token ?>";
  LA.sessionImage = new Image();
</script>
<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 3 -->
<script src="<?php echo $this->view->resourceUrl ?>../jQuery/jquery.uniform.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../jquery-validation/jquery.validate.min.js"></script>

<!-- Bootstrap 3.3.7 -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<!-- <script src="<?php echo $this->view->resourceUrl ?>dist/js/app.min.js"></script> -->
<script src="<?php echo $this->view->resourceUrl ?>dist/js/adminlte.min.js"></script>

<!-- Select2 -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/select2/dist/js/select2.full.min.js"></script>
<!-- InputMask -->
<script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.extensions.js"></script>
<!-- <script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.bundle.min.js"></script> -->
<!-- date-range-picker -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/moment/min/moment.min.js"></script>
<!-- <script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/moment/min/moment-with-locales.min.js"></script> -->

<script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- bootstrap color picker -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<!-- <script src="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.js"></script> -->

<!-- bootstrap time picker -->
<script src="<?php echo $this->view->resourceUrl ?>plugins/timepicker/bootstrap-timepicker.min.js"></script>
<!-- SlimScroll -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- DataTables -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- iCheck 1.0.1 -->
<script src="<?php echo $this->view->resourceUrl ?>plugins/iCheck/icheck.min.js"></script>
<!-- FastClick -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/fastclick/lib/fastclick.js"></script>
<!-- Sparkline -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap  -->
<script src="<?php echo $this->view->resourceUrl ?>plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- ChartJS -->
<script src="<?php echo $this->view->resourceUrl ?>bower_components/chart.js/Chart.js"></script>

<script src="<?php echo $this->view->resourceUrl ?>bower_components/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>

<script src="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../number-input/bootstrap-number-input.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/canvas-to-blob.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/fileinput.min.js?v=4.5.2"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/sortable.min.js?v=4.5.2"></script>
<script src="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../nprogress/nprogress.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../jquery-pjax/jquery.pjax.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.js"></script>

<!-- ckeditor start -->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ckeditor/ckeditor.js"></script>
<!-- ckeditor end -->

<!-- ueditor start -->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/third-party/zeroclipboard/ZeroClipboard.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.all.min.js"> </script>
<!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
<!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/lang/zh-cn/zh-cn.js"></script>
<!-- ueditor end -->
<script src="<?php echo $this->view->resourceUrl ?>../nestable/jquery.nestable.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../fontawesome-iconpicker/dist/js/fontawesome-iconpicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>../bootstrap-duallistbox/dist/jquery.bootstrap-duallistbox.min.js"></script>

<!-- page script -->
<?php $this->partial("partials/js/app") ?>
<?php if ($this->view->adminConfig->admin->is_tab_iframe_used) { ?>
  <?php if (empty($this->view->__SHOWBYIFRAME__)) { ?>
    <?php $this->partial("partials/js/app_iframe") ?>
  <?php } ?>
<?php } ?>

<script>
  $(function() {

    if (typeof App == 'object') {
      App.init();
    }
    //FormValidation.init();
    if (typeof FormComponents == 'object') {
      FormComponents.init();
    }
    if (typeof Search == 'object') {
      Search.init();
    }
    if (typeof List == 'object') {
      List.init();
    }
  })
</script>
<?php $this->partial("partials/toastr") ?>