<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bootstrap/css/bootstrap.min.css"> -->
<!-- Font Awesome -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/Ionicons/css/ionicons.min.css">
<!-- jvectormap -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/jvectormap/jquery-jvectormap.css">
<!-- daterange picker -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-daterangepicker/daterangepicker.css">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/iCheck/all.css">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.css"> -->
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/timepicker/bootstrap-timepicker.min.css">
<!-- Select2 -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/select2/dist/css/select2.min.css">
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/select2/select2.min.css"> -->
<!-- DataTables -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">


<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/_all-skins.min.css"> -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/skin-blue.min.css">

<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/css/fileinput.min.css?v=4.5.2">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../nprogress/nprogress.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../google-fonts/fonts.css">
<!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/ion.rangeSlider/css/ion.rangeSlider.css"> -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/ion.rangeSlider/css/ion.rangeSlider.min.css">

<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../fontawesome-iconpicker/dist/css/fontawesome-iconpicker.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-duallistbox/dist/bootstrap-duallistbox.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../nestable/nestable.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap3-editable/css/bootstrap-editable.css">
<!-- Theme style -->
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/AdminLTE.min.css">

<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../grid-lightbox/resources/assets/magnific-popup.css">

<!-- <script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery/dist/jquery.min.js"></script> -->
<script src="<?php echo $this->view->resourceUrl ?>../jQuery/jQuery-2.1.4.min.js"></script>

<?php if ($this->view->adminConfig->admin->is_tab_iframe_used) { ?>
    <?php if (empty($this->view->__SHOWBYIFRAME__)) { ?>
        <style type="text/css">
            /* NAV TABS */
            .nav-tabs-custom {
                margin-bottom: 20px;
                background: #fff;
                box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
                border-radius: 3px;
            }

            .nav-tabs-custom>.nav-tabs {
                margin: 0;
                border-bottom-color: #f4f4f4;
                border-top-right-radius: 3px;
                border-top-left-radius: 3px;
            }

            .nav-tabs-custom>.nav-tabs>li {
                border-top: 3px solid transparent;
                margin-bottom: -2px;
                margin-right: 5px;
            }

            .nav-tabs-custom>.nav-tabs>li>a {
                color: #444;
                border-radius: 0;
            }

            .nav-tabs-custom>.nav-tabs>li>a.text-muted {
                color: #999;
            }

            .nav-tabs-custom>.nav-tabs>li>a,
            .nav-tabs-custom>.nav-tabs>li>a:hover {
                background: transparent;
                margin: 0;
            }

            .nav-tabs-custom>.nav-tabs>li>a:hover {
                color: #999;
            }

            .nav-tabs-custom>.nav-tabs>li:not(.active)>a:hover,
            .nav-tabs-custom>.nav-tabs>li:not(.active)>a:focus,
            .nav-tabs-custom>.nav-tabs>li:not(.active)>a:active {
                border-color: transparent;
            }

            .nav-tabs-custom>.nav-tabs>li.active {
                border-top-color: #3c8dbc;
            }

            .nav-tabs-custom>.nav-tabs>li.active>a,
            .nav-tabs-custom>.nav-tabs>li.active:hover>a {
                background-color: #fff;
                color: #444;
            }

            .nav-tabs-custom>.nav-tabs>li.active>a {
                border-top-color: transparent;
                border-left-color: #f4f4f4;
                border-right-color: #f4f4f4;
            }

            .nav-tabs-custom>.nav-tabs>li:first-of-type {
                margin-left: 0;
            }

            .nav-tabs-custom>.nav-tabs>li:first-of-type.active>a {
                border-left-color: transparent;
            }

            .nav-tabs-custom>.nav-tabs.pull-right {
                float: none !important;
            }

            .nav-tabs-custom>.nav-tabs.pull-right>li {
                float: right;
            }

            .nav-tabs-custom>.nav-tabs.pull-right>li:first-of-type {
                margin-right: 0;
            }

            .nav-tabs-custom>.nav-tabs.pull-right>li:first-of-type>a {
                border-left-width: 1px;
            }

            .nav-tabs-custom>.nav-tabs.pull-right>li:first-of-type.active>a {
                border-left-color: #f4f4f4;
                border-right-color: transparent;
            }

            .nav-tabs-custom>.nav-tabs>li.header {
                line-height: 35px;
                padding: 0 10px;
                font-size: 20px;
                color: #444;
            }

            .nav-tabs-custom>.nav-tabs>li.header>.fa,
            .nav-tabs-custom>.nav-tabs>li.header>.glyphicon,
            .nav-tabs-custom>.nav-tabs>li.header>.ion {
                margin-right: 5px;
            }

            .nav-tabs-custom>.tab-content {
                background: #fff;
                padding: 10px;
                border-bottom-right-radius: 3px;
                border-bottom-left-radius: 3px;
            }

            .nav-tabs-custom .dropdown.open>a:active,
            .nav-tabs-custom .dropdown.open>a:focus {
                background: transparent;
                color: #999;
            }

            .nav-tabs-custom.tab-primary>.nav-tabs>li.active {
                border-top-color: #3c8dbc;
            }

            .nav-tabs-custom.tab-info>.nav-tabs>li.active {
                border-top-color: #00c0ef;
            }

            .nav-tabs-custom.tab-danger>.nav-tabs>li.active {
                border-top-color: #dd4b39;
            }

            .nav-tabs-custom.tab-warning>.nav-tabs>li.active {
                border-top-color: #f39c12;
            }

            .nav-tabs-custom.tab-success>.nav-tabs>li.active {
                border-top-color: #00a65a;
            }

            .nav-tabs-custom.tab-default>.nav-tabs>li.active {
                border-top-color: #d2d6de;
            }

            .content-tabs {
                border-bottom: solid 2px #e7ebee;
                background: #fff !important;
                border-top: none;
                height: 41px;
            }

            .content-tabs .page-tabs a.active {
                background: whitesmoke;
                color: #fff !important;
                border-right: solid 1px #e7ebee;
            }

            .content-tabs .roll-left {
                border-right: solid 1px #e7ebee;
            }

            .content-tabs .roll-right {
                border-left: solid 1px #e7ebee;
            }

            #content-wrapper {
                background-color: #f9f9f9;
                border-left: 2px solid #e7ebee;
            }

            @media (min-width: 768px) {
                .nav-small #nav-col {
                    width: 64px;
                }

                .nav-small #content-wrapper {
                    margin-left: 64px;
                }

                .content-tabs {
                    position: relative;
                    height: 42px;
                    line-height: 39.5px;
                    background: #fafafa;
                    border-bottom: solid 2px #2c3e50;
                    font-size: 12px;
                    border-top: 1px solid #ddd;
                }

                .content-tabs .roll-nav {
                    position: absolute;
                    width: 40px;
                    height: 39px;
                    text-align: center;
                    color: #475059;
                    z-index: 2;
                    top: 0;
                }

                .content-tabs .roll-left {
                    left: 0;
                    border-right: solid 1px #ddd;
                }

                .content-tabs .roll-right {
                    right: 0;
                    border-left: solid 1px #ddd;
                }

                .content-tabs button {
                    background: #fff;
                    border: 0;
                    height: 39px;
                    line-height: 39px;
                    width: 40px;
                    outline: 0;
                }

                .content-tabs button:hover {
                    background: #fafafa;
                }

                .content-tabs button i {
                    color: #999;
                }

                .content-tabs nav.page-tabs {
                    margin-left: 40px;
                    width: 100000px;
                    height: 40px;
                    overflow: hidden;
                }

                .content-tabs nav.page-tabs .page-tabs-content {
                    float: left;
                }

                .content-tabs .page-tabs a {
                    display: block;
                    float: left;
                    border-right: solid 0px #ddd;
                    padding: 0 15px;
                    padding-right: 8px;
                    text-decoration: none;
                    color: #475059;
                }

                .content-tabs .page-tabs a:first-child {
                    padding-right: 15px;
                }

                .content-tabs .page-tabs a i {
                    margin-top: -10px;
                    right: 0px;
                    position: relative;
                    color: #999;
                }

                .content-tabs .page-tabs a i:hover {
                    color: #c00 !important;
                }

                .content-tabs .page-tabs a.active {
                    background: #2c3e50;
                    color: #fff;
                    border-right: solid 1px #2c3e50;
                }

                .content-tabs .page-tabs a.active i:hover {
                    color: #fff !important;
                }

                .content-tabs .roll-right.tabRight {
                    right: 120px;
                }

                .content-tabs .roll-right.btn-group {
                    right: 40px;
                    width: 80px;
                    padding: 0;
                }

                .content-tabs .roll-right.btn-group button {
                    width: 80px;
                }

                .content-tabs .roll-right.tabExit {
                    background: #fff;
                    height: 39px;
                    width: 40px;
                    outline: 0;
                }

                .page-tabs-list {
                    position: absolute;
                    width: 40px;
                    height: 39px;
                    text-align: center;
                    color: #475059;
                    z-index: 2;
                    top: 0;
                }
            }

            @media (max-width: 768px) {
                .content-tabs {
                    display: none;
                }
            }

            .nav-link {
                cursor: pointer;
            }

            html {
                overflow: hidden;
            }

            .systitle {
                font-size: 1.4em;
                font-weight: bold;
                cursor: default;
            }

            .systitle:hover {
                cursor: default;
                background-color: transparent;
            }

            .subsystitle {
                font-size: 1.1em;
                font-weight: bold;
                cursor: pointer;
            }

            .menu_tab {
                padding: 0 10px !important;
            }

            .page_tab_title {
                padding-right: 3px;
                font-size: 1.1em;
            }

            .page_tab_close {
                cursor: pointer;
                font-size: 1.3em;
                font-weight: bold;
            }
        </style>
    <?php } ?>
<?php } ?>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->