<link rel="stylesheet" type="text/css" href="css/Detail.css" />
<input type="hidden" id="pageID" value="postdetail">
<div class="g-main-con clrfix" id="loadingPicBlock">
    <div class="w1190">
        <div class="m-position">当前位置：<a href="<?php echo $this->view->baseUrl?>" title="首页">首页</a><span class="f-tran f-tran-prev f-tran-next">&gt;</span><a href="<?php echo $this->view->baseUrl?>yungou/post/index" title="晒单列表">晒单列表</a><span class="f-tran f-tran-prev f-tran-next">&gt;</span>晒单详情</div>
        <div class="g-detailCon clrfix">
            <!--左边部分-->
            <div class="m-detail-left clrfix">
                <!--会员和商品信息宽屏-->
                <div class="winners-info gray9 clrfix"><ul><li class="win-head">
                <a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->postInfo['buyer_id']?>" target="_blank">
                <img src="<?php echo \App\Member\Views\Helpers\MemberHelper::getImagePath($this->view->baseUrl, $this->view->postInfo['goods_info']['prize_buyer_avatar'])?>"><s class="transparent-png"></s></a></li><li class="win-name">
                <a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->postInfo['buyer_id']?>" target="_blank"><?php echo getBuyerName($this->view->postInfo['goods_info']['prize_buyer_name'], $this->view->postInfo['goods_info']['prize_buyer_register_by'])?></a></li>
                <li><i>本云参与：</i><em class="orange f-tran-prev"><?php echo $this->view->postInfo['goods_info']['prize_buyer_purchase_num']?></em>人次</li>
                <li><i>幸运集资购码：</i><span class="orange"><?php echo $this->view->postInfo['goods_info']['prize_code']?></span></li>
                <li><i>揭晓时间：</i><cite><?php echo date('Y-m-d H:i:s',$this->view->postInfo['goods_info']['prize_time'])?></cite></li></ul><b class="point-out"><s></s></b></div><div class="next-period"><dl><dt>
                <a rel="nofollow" href="<?php echo $this->view->baseUrl?>yungou/lottery/detail?id=<?php echo $this->view->postInfo['goods_id']?>" target="_blank">
                <img src="<?php echo \App\Goods\Views\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl, $this->view->postInfo['goods_info']['image'])?>"></a></dt><dd class="comm-name "><p>
                <a href="<?php echo $this->view->baseUrl?>yungou/lottery/detail?id=<?php echo $this->view->postInfo['goods_id']?>" target="_blank">(第<?php echo $this->view->postInfo['goods_info']['period']?>云)<?php echo $this->view->postInfo['goods_info']['name']?></a></p></dd>
                <dd class="gray9">商品价值：￥<?php echo showPrice($this->view->postInfo['goods_info']['price'],2)?></dd></dl><span class="publicly-get transparent-png"></span></div>
                
                <!--他的其他晒单-->
                <div class="other-single">
                    <dl>
                        <dt class="gray3"><i>TA</i>的其他晒单</dt>
                    </dl>
                </div>
                
            </div>
            <!--中间部分-->
            <div class="m-detail-middle clrfix">
                <!--会员和商品信息窄屏-->
                <div class="procurer-and-next clrfix">
                    <div class="m-procurerCon fl gray9">
                        <ul>
                            <li class="win-head">
                                <a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->postInfo['buyer_id']?>" target="_blank">
                                    <img src="<?php echo \App\Member\Views\Helpers\MemberHelper::getImagePath($this->view->baseUrl, $this->view->postInfo['goods_info']['prize_buyer_avatar'])?>">
                                    <s class="transparent-png"></s>
                                </a>
                            </li>
                            <li>
                                <p>
                                    <a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->postInfo['buyer_id']?>" target="_blank">
                                        <?php echo getBuyerName($this->view->postInfo['goods_info']['prize_buyer_name'], $this->view->postInfo['goods_info']['prize_buyer_register_by'])?>
                                    </a>
                                </p>
                                <span>
                                    本云参与：<em class="orange"><?php echo $this->view->postInfo['goods_info']['prize_buyer_purchase_num']?></em>人次
                                </span>
                                <span>
                                    幸运集资购码：<em class="orange"><?php echo $this->view->postInfo['goods_info']['prize_code']?></em>
                                </span>
                                <span>
                                    揭晓时间：<?php echo date('Y-m-d H:i:s',$this->view->postInfo['goods_info']['prize_time'])?>
                                </span>
                            </li>
                        </ul>
                        <b class="point-out"><s></s></b>
                    </div>
                    <div class="m-nextCon fr">
                        <ul>
                            <li class="u-bor-left">
                                <a rel="nofollow" href="<?php echo $this->view->baseUrl?>yungou/lottery/detail?id=<?php echo $this->view->postInfo['goods_id']?>" target="_blank">
                                    <img src="<?php echo \App\Goods\Views\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl, $this->view->postInfo['goods_info']['image'],162,162)?>">
                                </a>
                            </li>
                            <li class="u-bor-right u-bor-top">
                                <p>
                                    <a href="<?php echo $this->view->baseUrl?>yungou/lottery/detail?id=<?php echo $this->view->postInfo['goods_id']?>" target="_blank">
                                        (第<?php echo $this->view->postInfo['goods_info']['period']?>云)<?php echo $this->view->postInfo['goods_info']['name']?>
                                    </a>
                                </p>
                                商品价值：￥<?php echo showPrice($this->view->postInfo['goods_info']['price'],2)?>
                            </li>
                        </ul>
                        <span class="publicly-get transparent-png"></span>
                    </div>
                </div>
                <!--晒单内容-->
                <div class="single-info clrfix">
                    <dl>
                        <dt class="gray3"><?php echo $this->view->postInfo['title']?></dt>
                        <dd class="single-fufen"><cite><?php echo date('Y-m-d H:i:s',strtotime($this->view->postInfo['post_time']))?></cite><cite>
                        <em><?php echo $this->view->postInfo['read_num']?></em>人阅读</cite><cite><em id="b_ReplayCount"><?php echo $this->view->postInfo['reply_num']?></em>人评论</cite><span class="transparent-png"><b><?php echo $this->view->postInfo['point']?></b></span></dd><dd class="gray6">
                        <p><?php echo $this->view->postInfo['content']?></p>
                        </dd>
                        <dd>
                        <?php $pics =  explode(',', $this->view->postInfo['pic'])?>
                        <?php foreach ($pics as $pic) {?>
                            <img src="<?php echo \App\Post\Views\Helpers\PostHelper::getPostImage($this->view->baseUrl, $pic,105,105)?>" border="0" alt="">
                        <?php }?>
                        </dd>
                    </dl>
                </div>
                <!--回复总数-->
                <div class="reply-total clrfix">
                    <ul>
                        <li class="m-gxhf gray6 fl"><i></i>共<em class="orange" id="em_ReplayCount"><?php echo $this->view->postInfo['reply_num']?></em>条评论</li>
                        <li class="m-share fr" id="li_share" style="display:;">
                            <p id="p_xianmu" class="u-xianmu <?php if(!empty($this->view->isVoted)){?>u-xianmu-past<?php }?>">
                                <a href="javascript:;">
                                    <i class="transparent-png"></i>
                                    <em>羡慕</em>
                                    <span class="gray9">
                                        <cite class="em" votenum="<?php echo $this->view->postInfo['vote_num']?>">
                                            <?php echo $this->view->postInfo['vote_num']?>
                                        </cite><b><s></s></b>
                                    </span>
                                    <img class="transparent-png" src="/Images/xin.png" alt="">
                                </a>
                            </p>
                            <!-- Baidu Button BEGIN -->
                            <div id="bdshare" class="bdshare_t bds_tools get-codes-bdshare" style="position: relative;">
                                <div class="bdsharebuttonbox" style="position:absolute;width:100%;height:100%;filter:alpha(opacity=0);-moz-opacity:0;-khtml-opacity: 0;opacity: 0;"><a href="#" class="bds_more" data-cmd="more" style="width:57px;height:24px;"></a></div>
                                <span class="bds_more"><cite></cite>分享</span>
                            </div>
                            <script>
                            window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{}};
                            with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
                        </li>
                    </ul>
                </div>
                <!--晒单评论开始-->
                <!--输入框-->
                <div id="bottomComment">
                    <div class="not-login clrfix input-comment-bor">
                        <div name="userFace" class="input-pic fl">
                            <img src="<?php echo \App\Member\Views\Helpers\MemberHelper::getImagePath($this->view->baseUrl, $this->view->memberInfo['avatar']);?>">
                            <i class="transparent-png"></i>
                        </div>                        
                        <?php if(!empty($_SESSION['member_id'])){?>
                            <div class="input-box fl">
                                <div class="textCon">
                                    <iframe hidefocus="true" name="myFrame" frameborder="0" scrolling="no" src="/yungou/message.html?page=postdetaila" style="width: 565px; height: 155px;cursor:text;"></iframe>
                                </div>
                            </div>
                        <?php }else{?>
                            <div class="point-box fl gray6">
                                请您<a href="javascript:;" name="replyLoginBtn" class="tan_login">登录</a>或<a href="/member/passport/register">注册</a>后再评论<b><s></s></b>
                            </div>
                        <?php }?>
                    </div>
                </div>
                <!--评论列表-->
                <div id="commentList" class="comment-main clrfix">
                    <ul></ul>
                </div>

                <div class="g-pagination" id="g-pagination"></div>

                <!--晒单评论结束-->

            </div>
            <!--右边-->
            <div class="m-detail-right clrfix">
                <!--其他获得者-->
                
                    <div class="other-get clrfix">
                        <dl id="dl_otherget" codeID="<?php echo $this->view->postInfo['goods_id']?>">
                            <dt>
                                <cite class="gray3 fl">其他获得者</cite>
                                <span class="fr">
                                    <a rel="nofollow" id="otherleft" href="javascript:;" class="other-left other-left-none"></a><a id="otherright" href="javascript:;" class="other-right"></a>
                                </span>
                            </dt>
                        </dl>
                    </div>

                
                <!--最新晒单-->
                <div class="new-single">
                    <h4 class="gray3">最新晒单</h4>
                    <ul></ul>
                </div>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/post.js"></script>