<link rel="stylesheet" type="text/css" href="css/List.css" />
<input type="hidden" id="pageID" value="postindex">
<div class="g-main-con clrfix">
    <div class="w1190">
        <!--导航开始-->
        <div class="g-single-part1 clrfix">
            <div class="m-single-title">
                <em class="gray3">晒单分享</em>
                <s></s>
                <span class="gray9">共<i class="orange"><?php echo $this->view->postList['total']?></i>个幸运获得者晒单</span>
            </div>
            <div class="m-single-menu">
                <ul class="fl" id="ul_order">
                    <?php
                        $params=array();
                        if(!empty($this->view->i)){
                            $params['i'] = $this->view->i;
                        }
                        $urlParams10 = http_build_query(array_merge($params,array('r'=>10)));
                        $urlParams40 = http_build_query(array_merge($params,array('r'=>40)));
                        $urlParams30 = http_build_query(array_merge($params,array('r'=>30)));
                        $urlParams20 = http_build_query(array_merge($params,array('r'=>20)));
                        
                    ?>
                    <li class="<?php if($this->view->r==10){?>current<?php }?>">
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams10 ?>" title="最新">最新</a>
                    </li>
                    <li class="<?php if($this->view->r==40){?>current<?php }?>">
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams40 ?>" title="精华">精华</a>
                    </li>
                    <li class="<?php if($this->view->r==30){?>current<?php }?>">
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams30 ?>" title="推荐">推荐</a>
                    </li>
                    <li class="<?php if($this->view->r==20){?>current<?php }?>">
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams20 ?>" title="人气">人气</a>
                    </li>
                </ul>
                <?php
                    $params=array();
                    if(!empty($this->view->r)){
                        $params['r'] = $this->view->r;
                    }
                    $urlParams = http_build_query($params);                    
                ?>
                <div id="div_category" class="category-feedback fr">
                    <p>
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams ?>"><em>全部分类</em><s></s></a>
                    </p>
                    <div class="classification">
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams ?>" class="<?php if(empty($this->view->i)){?>hover<?php }?>">
                            全部分类
                        </a>
                        <?php $topLevelCategoryList = \App\Goods\Views\Helpers\GoodsHelper::getTopLevelCategoryList();?>
                        <?php if(!empty($topLevelCategoryList)){?>
                        <?php foreach ($topLevelCategoryList as $category) {?>
                        <?php
                        $params=array();
                        if(!empty($this->view->r)){
                            $params['r'] = $this->view->r;
                        }
                        $params['i'] = $category['_id'];
                        $urlParams = http_build_query($params);
                    ?>
                        <a href="<?php echo $this->view->baseUrl?>yungou/post/index?<?php echo $urlParams ?>"  class="<?php if(!empty($this->view->i) && $this->view->i == $category['_id'] ){?>hover<?php }?>">
                            <?php echo $category['name']?>
                        </a>
                        <?php }?>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>
        <!--导航结束-->
        <!--列表开始-->
        <div id="loadingSinglePic" class="g-single-part2 clrfix">
            <?php if(!empty($this->view->postList['datas'])){?>
            <?php foreach ($this->view->postList['datas'] as $idx => $post) {?>
            <div class="m-single <?php if($idx%4 == 0){?>m-single-special<?php }?>">
                <div class="single-list">
                    <ul>
                        <li class="sig-pic sig-pic-size">
                        <?php 
                        $pics =  explode(',', $post['pic']);
                        $pic = $pics[0];
                        ?>
                            <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/post/detail?id=<?php echo $post['_id']?>">
                                <img src="<?php echo \App\Post\Views\Helpers\PostHelper::getPostImage($this->view->baseUrl, $pic,30,30)?>"
                                border="0" alt="">
                            </a>
                        </li>
                        <li class="sig-title">
                            <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/post/detail?id=<?php echo $post['_id']?>">
                                <b>
                                    <?php echo $post['title']?>
                                </b>
                            </a>
                        </li>
                        <li class="sig-text">
                            <?php echo $post['content']?>
                        </li>
                        <li class="gray9">
                            <?php echo date('Y-m-d H:i:s',strtotime($post['post_time']))?>
                        </li>
                        <li class="sig-xmjdh">
                            <span class="xmjdh_left">
                                <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $post['buyer_id']?>">
                                    <cite class="fl">
                                        <img src="<?php echo \App\Member\Views\Helpers\MemberHelper::getImagePath($this->view->baseUrl, $post['goods_info']['prize_buyer_avatar'])?>">
                                        <s class="transparent-png"></s>
                                    </cite>
                                    <em class="fl"><?php echo getBuyerName($post['goods_info']['prize_buyer_name'],$post['goods_info']['prize_buyer_register_by'])?></em>
                                </a>
                            </span>
                            <span class="xmjdh_right">
                                <a href="javascript:;" class="xianmu p_xianmu <?php if(!empty($post['isVoted'])){?>xianmu-past<?php }?>" num="<?php echo $post['vote_num']?>" postid="<?php echo $post['_id']?>">
                                    <i class="transparent-png"></i>
                                    <em class="em" votenum="<?php echo $post['vote_num']?>"><?php echo $post['vote_num']?></em>
                                    <img class="transparent-png" src="/Images/xin.png">
                                </a>
                                <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/post/detail?id=<?php echo $post['_id']?>" class="pinglun">
                                    <i class="transparent-png"></i>
                                    <em><?php echo $post['reply_num']?></em>
                                </a>
                            </span>
                        </li>
                    </ul>
                    <b class="curr-arrow">
                        <s>
                        </s>
                    </b>
                </div>
            </div>
            <?php }?>
            <?php }?>
        </div>
        <!--列表结束-->
        <!--翻页开始-->
        <div class="g-pagination w1190">
            <span <?php if(empty($this->view->pager['page_prev'])){?>class="f-noClick"<?php }?>><a title="上一页" href="<?php if($this->view->pager['page_prev']){ echo $this->view->pager['page_prev']; }else{?>javascript:;<?php }?>"><i class="f-tran f-tran-prev">&lt;</i>上一页</a></span>
            <?php if($this->view->pager['page_first']){?><span><a href="<?php echo $this->view->pager['page_first'];?>">1</a></span><span>…</span><?php }?>
            <?php if($this->view->pager['page_count'] != 1){?>
            <?php foreach ($this->view->pager['page_number'] as $key => $item) {?>
            <?php if($this->view->pager['page'] == $key){?>
            <span class="current"><a><?php echo $key;?></a></span>
            <?php }else{?>
            <span><a href="<?php echo $item;?>"><?php echo $key;?></a></span>
            <?php }?>
            <?php }?>
            <?php }?>
            <?php if($this->view->pager['page_last']){?><span>…</span><span><a href="<?php echo $this->view->pager['page_last'];?>"><?php echo $this->view->pager['page_count']?></a></span><?php }?>
            <span><a href="<?php if($this->view->pager['page_next']){ echo $this->view->pager['page_next']; }else{?>javascript:;<?php }?>">下一页<i class="f-tran f-tran-next">&gt;</i></a></span>
            <span class="f-mar-left">共<em><?php echo $this->view->pager['page_count']?></em>页，去第</span>
            <span><input type="text" value="<?php echo $this->view->pager['page']?>">页</span>
            <span class="f-mar-left"><a id="btnGotoPage" href="javascript:;" title="确定">确定</a></span>
        </div>
        <!--翻页结束-->
    </div>
</div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/post.js"></script>