<link rel="stylesheet" type="text/css" href="datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="datepicker/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="/CSS/pageDialog.css" />
<link rel="stylesheet" type="text/css" href="css/member_q.css" />
<input type="hidden" id="pageID" value="collectlist">
<div class="sidebar_main clrfix fr">
    <div class="g-purchase-title">
    <span class="gray3">我的关注</span>
        <a id="a_clear" href="javascript:;" style="display: none;" class="n-clear gray9">清空失效商品</a>
    </div>
    <div id="div_collectlist" class="n-pro-inner clrfix">
        <!-- 有数据 -->
        <ul>
            <!-- <li issale="1">
                <div class="n-pro-img">
                    <a target="_blank" title="花果山 云南深山蒙自甜石榴 2500g" href="<?php echo $this->view->baseUrl?>member/index/detail.html">
                        <img src="http://goodsimg.1yyg.com/GoodsPic/pic-200-200/20151012135905441.jpg"><s></s>
                    </a>
                </div>
                <div class="n-info-wrapper n-info-wrapper01" style="display: block;">
                    <p class="gray3">花果山 云南深山蒙自甜石榴 2500g</p>
                    <div class="n-pro-num">第<span class="orange">1180</span>云&nbsp;进行中<span class="dotting"></span></div>
                </div>
                <div class="n-info-wrapper n-info-wrapper02" style="display: none;">
                    <div class="n-line-wrapper">
                        <div class="n-line-inner" title="完成3.08%">
                            <div class="line" style="width:3.08%"></div>
                        </div>
                    </div>
                    <a href="javascript:;" codeid="1821862" class="n-pro-add">加入购物车</a>
                    <a href="javascript:;" goodsid="22563" class="n-btn-del u-personal"></a>
                </div>
            </li> -->
        </ul>
        <!-- 无数据 -->
        <div class="null-data" style="display:none;"><b class="gth-icon transparent-png"></b>暂无记录！</div>
    </div>
    <div class="g-pagination" id="g-pagination" style="display:none;"></div>
</div>