<?php $siteSettings=\Webcms\Site\Helpers\SiteHelper::getSettings();?>
<link rel="stylesheet" type="text/css" href="css/member_q.css" />
<link rel="stylesheet" type="text/css" href="css/pageDialog.css" />
<link rel="stylesheet" type="text/css" href="/yungou/css/share_style2_16.css" />
<input type="hidden" id="pageID" value="orderdetail">
<div class="buy-detail clrfix">
    <div class="g-cur-location">
        您的位置：<a href="<?php echo $this->view->baseUrl?>">首页</a><em class="f-tran">&gt;</em><a href="<?php echo $this->view->baseUrl?>member/index/index">我的1元云购</a><em class="f-tran">&gt;</em> <a href="<?php echo $this->view->baseUrl?>member/index/orderlist">获得的商品</a><em class="f-tran">&gt;</em>订单详情
    </div>
    
    
    <div class="g-buyCon clrfix">
        <h3 class="gray3">获得的商品 - 订单详情</h3>
        <div class="m-get-process">
            <ul>
                <!--订单导航步骤-->
                <li class="z-old"><span class="f-hdsp"><i class="u-personal"></i>获得商品</span><s class="u-personal"></s></li>
                <li class="<?php if($this->view->orderInfo['order_state'] > \Webcms\Order\Models\Goods::ORDER_STATE1){?>z-old<?php }else{?><?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE1){?>z-cur<?php }?><?php }?>"><span><i class="u-personal"></i>确认收货地址</span><s class="u-personal"></s><em class="u-personal"></em></li>
                <li class="<?php if($this->view->orderInfo['order_state'] > \Webcms\Order\Models\Goods::ORDER_STATE2){?>z-old<?php }else{?><?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE2){?>z-cur<?php }?><?php }?>"><span><i class="u-personal"></i>商家发货</span><s class="u-personal"></s></li>
                <li class="<?php if($this->view->orderInfo['order_state'] > \Webcms\Order\Models\Goods::ORDER_STATE3){?>z-old<?php }else{?><?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE3){?>z-cur<?php }?><?php }?>"><span><i class="u-personal"></i>确认收货</span><s class="u-personal"></s></li>
                <li class="f-sdnjl <?php if($this->view->orderInfo['order_state'] > \Webcms\Order\Models\Goods::ORDER_STATE4){?>z-old<?php }else{?><?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE4){?>z-cur<?php }?><?php }?>"><span class="f-sdnjl"><i class="u-personal"></i>晒单拿奖励</span><s class="u-personal"></s></li>
            </ul>
        </div>

        <!-- 确认地址 -->
        <div class="m-statusCon clrfix">
            <!--订单状态及提示-->
            <div class="cur-status gray9">
                <?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE1){?>
                    <!-- 状态一  待确认地址-->
                    <p><b>当前状态：等待提交收货地址</b></p>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询订单相关信息。 
                <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE2){?>
                    <!-- 状态二 确认地址后 -->
                    <p><b>当前状态：等待商家发货</b></p>已收到您填写的配送地址信息，我们会尽快处理，请您耐心等候！<br>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询发货信息。
                <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE3){?>
                    <!-- 状态三 已经发货 -->
                    <p><b>当前状态：商家已发货，等待收货</b></p>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询订单物流信息。<br>
                    <a id="btnConfirmReceipt" href="javascript:;">确认收货</a>
                <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE4){?>
                    <!-- 状态四 确认收货-->
                    <?php if(empty($this->view->postInfo) || $this->view->postInfo['state'] == \Webcms\Post\Models\Post::STATE_NONE ){?>
                    <p><b>当前状态：等待晒单</b></p><span>您可通过晒单获得相应福分奖励哦。<br>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询晒单相关信息。</span><br>
                    <a href="<?php echo $this->view->baseUrl?>member/index/postsingleadd?goods_id=<?php echo $this->view->orderInfo['goods_id']?>">立即晒单</a> 
                    <?php }elseif($this->view->postInfo['state'] != \Webcms\Post\Models\Post::STATE2){?>
                    <p><b>当前状态：等待审核</b></p><span>您可通过晒单获得相应福分奖励哦。<br>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询晒单相关信息。</span><br>
                    <a href="<?php echo $this->view->baseUrl?>member/index/postsingleedit?goods_id=<?php echo $this->view->orderInfo['goods_id']?>">编辑晒单</a> 
                    <?php }else{}?>
                <?php }?>
            </div>


            <?php if($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE1){?>
                <!--收货地址列表(待确认收货)-->
                <div class="f-addList clrfix">
                    <cite class="gray3">请您确认收货地址</cite>
                    <ul id="ul_addrlist">
                        <?php 
                            $consigneeList = \Webcms\Member\Helpers\MemberHelper::getConsigneeList($this->view->orderInfo['buyer_id']);
                            foreach ($consigneeList as $id => $consignee) {
                        ?>
                        <li id="<?php echo $id?>" class="<?php if(!empty($consignee['is_default'])){?>z-che<?php }?>" name="<?php echo $consignee['name']?>" tel="<?php echo $consignee['mobile']?>" address="<?php echo \Webcms\System\Helpers\AreaHelper::getAddress($consignee['province'],$consignee['city'],$consignee['district'],$consignee['address'])?>" code="" provinceID="<?php echo $consignee['province']?>" cityID="<?php echo $consignee['city']?>" districtID="<?php echo $consignee['district']?>">
                            <p><span><?php echo $consignee['name']?></span><?php echo $consignee['mobile']?></p>
                            <i><?php echo \Webcms\System\Helpers\AreaHelper::getAddress($consignee['province'],$consignee['city'],$consignee['district'],$consignee['address'])?></i><a href="javascript:;" class="z-alter" id="<?php echo $id?>">修改</a><s class="u-personal"></s>
                        </li>
                        <?php }?>
                        <li class="new-address"><a href="javascript:;"><b class="u-personal"></b><em>使用新地址</em></a></li>
                    </ul>
                </div>
                <!--订单备注(待确认收货)-->
                <div class="f-del-information clrfix">
                    <ul id="ul_confirm">
                        <li class="info-text"><em class="gray3">添加备注信息</em> 请填写商品的信息，如商品为手机充值卡可以填写要充值的手机号码等</li>
                        <li class="info-edit">
                            <textarea id="txtRemark" rows="3" cols="10" class="gray3"></textarea>
                        </li>
                        <li class="info-btn"><a id="btnSubmit" href="javascript:;">确认提交</a></li>
                    </ul>
                </div>
            <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE2){?>
                <!--物流信息及收货人信息-->
                <div class="delivery-mes gray6">  
                    <?php $consignee = $this->view->orderInfo['consignee_info'];?>                  
                    <p><span>配送信息：</span><i><?php echo $consignee['name']?></i><i><?php echo $consignee['mobile']?></i><?php echo \Webcms\System\Helpers\AreaHelper::getAddress($consignee['province'],$consignee['city'],$consignee['district'],$consignee['address'])?>，<?php echo $consignee['zipcode']?></p>
                    <p><span><em>备</em>注：</span>工作日配送</p>
                    <div id="div_delivery" class="logistics-info-wrap"></div>
                </div>
            <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE3 || $this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE4 ){?>
                <!--物流信息及收货人信息-->
                <div class="delivery-mes gray6">
                    <?php 
                        $consignee = $this->view->orderInfo['consignee_info'];
                        $deliveryInfo = $this->view->orderInfo['delivery_info'];
                    ?>                  
                    <p class="f-logistics">
                        <span>快递信息：</span>
                        <a href="http://www.sto.cn" target="_blank" class="orange"><?php echo $deliveryInfo['name']?></a>&nbsp;&nbsp;&nbsp;
                        <span class="orange"><i><?php echo $deliveryInfo['delivery_sn']?></i></span>
                    </p>
                    <p><span>配送信息：</span><i><?php echo $consignee['name']?></i><i><?php echo $consignee['mobile']?></i><?php echo \Webcms\System\Helpers\AreaHelper::getAddress($consignee['province'],$consignee['city'],$consignee['district'],$consignee['address'])?>，<?php echo $consignee['zipcode']?></p>
                    <p><span><em>备</em>注：</span>工作日配送</p>
                </div>
            <?php }elseif($this->view->orderInfo['order_state'] == \Webcms\Order\Models\Goods::ORDER_STATE10){?>
                <!--晒单后-->
                <div class="cur-status gray9">
                    <p><b>当前状态：晒单审核已通过</b></p><span>您的晒单审核通过，已获得相应福分奖励啦。<br>客服工作时间为（周一至周日 09:00-21:00），在此期间您可以致电 <?php echo $siteSettings['tel400']?> 客服热线随时咨询晒单相关信息。</span>
                </div>  
            <?php }?>


            <!--订单处理步骤-->
            <div class="operating-mes">
              <ul>
              <?php if(!empty($this->view->logList)){?>
              <?php foreach ($this->view->logList as $logInfo) {?>
                  <li><span><?php echo date('Y-m-d H:i:s',$logInfo['log_time']->sec)?></span><span class="ope-text"><?php echo $logInfo['msg']?></span><span class="gray9"><?php echo \Webcms\Order\Helpers\OrderHelper::getLogName($logInfo)?></span></li>
              <?php }?>
              <?php }?>
              </ul>
            </div>


        </div>
        
        <div class="m-goods-title clrfix">
            <cite class="gray3"> 获得的商品</cite>
            <!--获得的商品信息-->
            <div class="goods-obtCon clrfix">
              <ul class="goods-title">
                  <li class="f-com-name">商品</li>
                  <li class="f-value">价值</li>
                  <li class="f-quantity">数量</li>
                  <li class="f-number">订单号</li>
              </ul>
              <ul>
                  <li class="f-com-name">
                      <span>
                          <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $this->view->orderInfo['goods_commonid']?>">
                              <img src="<?php echo \Webcms\Goods\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl, $this->view->orderInfo['goods_image'])?>">
                          </a>
                      </span>
                      <p class="gray9">
                          <em>
                              <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $this->view->orderInfo['goods_commonid']?>" class="gray3">
                                  (第<?php echo $this->view->orderInfo['goods_period']?>云)<?php echo $this->view->orderInfo['goods_name']?>
                              </a>
                          </em>
                          幸运云购码：<?php echo $this->view->orderInfo['prize_code']?>
                          <br>
                          揭晓时间：<?php echo getMilliTime4Show($this->view->orderInfo['prize_time'])?>
                      </p>
                  </li>
                  <li>
                      ￥<?php echo number_format($this->view->orderInfo['goods_value'],2)?>
                  </li>
                  <li>
                      1
                  </li>
                  <li class="f-number">
                      <?php echo $this->view->orderInfo['order_no']?>
                  </li>
              </ul>
          </div>
        </div>
        <div class="g-wx-banner">
            <img alt="" src="../yungou/images/wx-banner.jpg">
        </div>
    </div>
</div>

<script type="text/template" id="shiAddress">  
    <div class="shi-address-box">
        <h2 class="gray3">添加收货地址</h2>
        <ul>
            <li class="select-list">
                <label>所在地区：</label>
                <div class="fl clrfix" id="div_area">
                    <span class="u-select-con" id="selProvinceID">
                        <a href="javascript:;" class="gray6 select-xiala">---请选择---<s class="u-personal"></s></a>
                        <div class="select-state" style="display: none;">
                            <?php
                            $provinceList = \Webcms\System\Helpers\AreaHelper::getProvinceList();
                            foreach ($provinceList as $code => $name) {
                            ?>
                            <a href="javascript:;" value="<?php echo $code?>"><?php echo $name?></a>
                            <?php }?>
                        </div>
                        <input type="hidden">
                    </span>
                    <span class="u-select-con" id="selCityID">
                        <a href="javascript:;" class="gray6 select-xiala">---请选择---<s class="u-personal"></s></a>
                        <div class="select-state">
                        </div>
                        <input type="hidden"> 
                    </span>
                    <span class="u-select-con" id="selCountyID">
                        <a href="javascript:;" class="gray6 select-xiala">---请选择---<s class="u-personal"></s></a>
                        <div class="select-state"></div>
                        <input type="hidden">
                    </span>
                    <span class="u-select-con" id="selAddressID" style="display:none;">
                        <a href="javascript:;" class="gray6 select-xiala">---请选择---<s class="u-personal"></s></a>
                        <div class="select-state"></div>
                        <input type="hidden">
                    </span>
                </div>
                <em class="f-tran">*</em>
                <p class="orange"><b class="u-personal"></b>必填</p>
            </li>
            <li class="z-address">
                <label>详细地址：</label>
                <input id="txtAddress" type="text" maxlength="200">
                <em class="f-tran">*</em>
                <p class="orange"><b class="u-personal"></b>必填</p>
                <cite class="gray9">无需重复填写所在地区</cite>
            </li>
            <li>
                <label>邮政编码：</label>
                <input id="txtPostCode" type="text" maxlength="10">
                <p class="orange"><b class="u-personal"></b>请填写正确的邮政编码</p>
            </li>
            <li>
                <label>收<i>货</i>人：</label>
                <input id="txtConsignee" type="text" maxlength="5">
                <em class="f-tran">*</em>
                <p class="orange"><b class="u-personal"></b>必填</p>
                <cite class="gray9">请填写真实有效的姓名，否则将无法进行配送</cite>
            </li>
            <li>
                <label>固定电话：</label>
                <input id="txtTel" type="text" maxlength="20">
                <p class="orange"><b class="u-personal"></b>请填写真实有效的固定电话或手机号码</p>
            </li>
            <li>
                <label>手机号码：</label>
                <input id="txtMobile" type="text" maxlength="11">
                <p class="orange"><b class="u-personal"></b>请填写真实有效的手机号码或固定电话</p>
            </li>
            <li class="set-default">
                <a href="javascript:;" id="a_default" class="gray9" value="0"><i><s class="u-personal"></s></i>设为默认地址</a>
            </li>
            <li class="z-save-btn">
                <a id="btnSaveAddress" href="javascript:;" class="save" style="float: left;margin-right: 10px;">保存</a>
                <a id="btnCancel" href="javascript:;" class="close" onclick="gotoClick()" style="float: left;">取消</a>
            </li>
        </ul>
    </div>
</script> 
