<link rel="stylesheet" type="text/css" href="css/base.css" />
<link rel="stylesheet" type="text/css" href="css/member_q.css" />
<input type="hidden" id="pageID" value="">
<div class="buy-detail clrfix">
    <div class="g-cur-location">
        您的位置：<a href="<?php echo $this->view->baseUrl?>">首页</a><em class="f-tran">&gt;</em><a href="<?php echo $this->view->baseUrl?>member/index/index">我的1元集资购</a><em class="f-tran">&gt;</em><a href="<?php echo $this->view->baseUrl?>member/index/userbuylist">集资购记录</a><em class="f-tran">&gt;</em>集资购记录详情
    </div>
    <div class="g-buyCon clrfix">
        <h3 class="gray3">集资购记录详情</h3>


        <div class="m-mer-info clrfix">
            <ul>
            <?php 
            $goods = $this->view->goodsInfo;
            $ret = \App\Order\Views\Helpers\OrderHelper::getUserBuyList($_SESSION['member_id'], $goods['_id']);
            $buyList = $ret['buyList'];
            $total_buy_num = $ret['total_buy_num'];
            $total_lottery_code_num = $ret['total_lottery_code_num'];            
            ?>
                <li class="mer-pic">
                    <a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $goods['goods_commonid']?>">
                        <img src="<?php echo \App\Goods\Views\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl,$goods['image'])?>">
                    </a>
                </li>
                <?php if($goods['sale_state'] == \App\Goods\Models\Goods::SALE_STATE3){?>
                <!-- 已经揭晓 -->
                <li class="other-winner">
                    <p>
                        <a class="gray3" target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/detail?id=<?php echo $goods['_id']?>">
                            (第<?php echo $goods['period']?>云)<?php echo $goods['name']?>
                        </a>
                    </p>
                    <cite>
                        价值：￥<?php echo showPrice($goods['price'],2)?>
                    </cite>
                    <span>
                        您已参与<i class="orange"><?php echo $total_buy_num?></i>人次</span>获得者：
                    <a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $goods['prize_buyer_id']?>" target="_blank" class="blue">
                        <?php echo getBuyerName($goods['prize_buyer_name'], $goods['prize_buyer_register_by'])?>
                    </a>
                    <br>幸运集资购码：<?php echo $goods['prize_code']?><br>揭晓时间：<?php echo getMilliTime4Show($goods['prize_time'])?>
                </li>
                <?php }elseif($goods['period'] == \App\Goods\Models\Goods::SALE_STATE2){?>
                <!-- 正在揭晓 -->
                <li>
                    <p><a class="gray3" target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/detail?id=<?php echo $goods['_id']?>">(第<?php echo $goods['period']?>云)<?php echo $goods['name']?></a></p>
                    <cite>价值：￥<?php echo showPrice($goods['price'],2)?></cite><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $goods['goods_commonid']?>" class="z-announcedIng">正在揭晓…</a><span>您已参与<i class="orange"><?php echo $total_buy_num?></i>人次</span>
                </li>
                <?php }else{?>
                <!-- 还未结束正在进行 -->
                <li>
                    <p><a class="gray3" target="_blank" href="<?php echo $this->view->baseUrl?>yungou/product/detail?id=<?php echo $goods['_id']?>">(第<?php echo $goods['period']?>云)<?php echo $goods['name']?></a></p>
                    <cite>价值：￥<?php echo showPrice($goods['price'],2)?></cite>
                    <div class="g-progress">
                        <dl class="m-progress">
                            <dt title="完成<?php echo number_format($goods['complete_percent'],2)?>%"><b style="width: 137px;"></b></dt>
                            <dd>
                                <span class="orange fl"><em><?php echo $goods['purchase_person_time']?></em>已参与</span>
                                <span class="gray6 fl"><em><?php echo $goods['total_person_time']?></em>总需人次</span>
                                <span class="blue fr"><em><?php echo $goods['remain_person_time']?></em>剩余</span>
                            </dd>
                        </dl>
                    </div>
                    <span>您已参与<i class="orange"><?php echo $total_buy_num?></i>人次</span>
                </li>
                <?php }?>

            </ul>
            <?php if($goods['sale_state'] == \App\Goods\Models\Goods::SALE_STATE1){?>
            <!-- 还未结束正在进行 -->
            <div class="pos-buttons">
                <a href="javascript:;" codeid="<?php echo $goods['_id']?>" class="z-add-btn">追加集资购</a>
                <a href="javascript:;" goodsid="<?php echo $goods['goods_commonid']?>" goodsname="<?php echo $goods['name']?>" goodspic="<?php echo \App\Goods\Views\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl, $goods['image'])?>" class="z-share-btn">一键分享</a>
            </div>
            <?php }?>

        </div>

        <div class="m-buy-num clrfix">
            <dl>
                <dt class="gray6">本云商品您总共参与<i class="orange"><?php echo $total_buy_num?></i>人次<em class="f-mar-left">拥有<i class="orange"><?php echo $total_lottery_code_num?></i>个集资购码</em></dt>
                <?php if(!empty($buyList)){?>
                <?php foreach ($buyList as $item) {?>
                <dd><p><?php echo getMilliTime4Show($item['purchase_time'])?><em class="f-mar-left"><?php echo $item['buy_num']?>人次</em></p><span><?php echo $item['lottery_code']?></span> </dd>
                <?php }?>
                <?php }?>
            </dl>
        </div>



    </div>
</div>