<script>
    var FormComponents = function() {

        return {
            //main function to initiate the module
            init: function() {
                <?php
                $schemas4Form = $this->view->schemas;
                $this->partial('partials/js/formelement');
                ?>

                <?php if ($this->view->actionName == 'edit') { ?>
                    $('.5e217e4051348-delete').unbind('click').click(function() {
                        var id = "<?php echo $this->view->row['_id'] ?>";
                        var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/remove';
                        var redirectUrl = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/list';

                        swal({
                            title: "确认删除?",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "确认",
                            showLoaderOnConfirm: true,
                            cancelButtonText: "取消",
                            preConfirm: function() {
                                return new Promise(function(resolve) {
                                    $.ajax({
                                        type: 'post',
                                        url: url,
                                        dataType: "json",
                                        data: {
                                            id: id,
                                            _method: 'delete',
                                            _token: LA.token,
                                        },
                                        success: function(data) {
                                            $.pjax({
                                                container: '#pjax-container',
                                                url: redirectUrl
                                            });
                                            // $.admin.redirect(redirectUrl);
                                            resolve(data);
                                        }
                                    });
                                });
                            }
                        }).then(function(result) {
                            console.log(result);
                            var data = result.value;
                            if (typeof data === 'object') {
                                if (!data.error) {
                                    swal(data.message, '', 'success');
                                } else {
                                    swal(data.message, '', 'error');
                                }
                            }
                        });
                    });

                    <?php foreach ($this->view->formTools as $key => $tool) { ?>
                        <?php if (!empty($tool['is_show'])) { ?>
                            $('.form-tool-<?php echo $key ?>').off('click').on('click', function(e) {
                                e.preventDefault();
                                var id = "<?php echo $this->view->row['_id'] ?>";
                                var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>?id=' + id;
                                // alert('ssssssss');
                                <?php if (empty($tool['process_without_modal'])) { ?>
                                    App.process4Modal(url, this);
                                <?php } else { ?>
                                    App.process4NoModal(url, this);
                                <?php } ?>
                            });
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            },
            // 提交
            submit: function() {
                //alert("submit！");
                var formData = new FormData(document.getElementById("form_sample_2")); //
                $.ajax({
                    //几个参数需要注意一下
                    type: "POST", //方法类型
                    dataType: "json", //预期服务器返回的数据类型
                    url: "<?php echo $this->view->form_act ?>",
                    contentType: false, //这里
                    processData: false, //这两个一定设置为false
                    data: formData,
                    //data: $('#form_sample_2').serialize(),
                    success: function(result) {
                        console.log(result); //打印服务端返回的数据(调试用)
                        // 如果发生了错误的话
                        // var form2 = $('#form_sample_2');
                        // var error2 = $('.alert-error', form2);
                        // var success2 = $('.alert-success', form2);

                        if (result.error == 1) {
                            alert(result.message);
                            // $('#resultId4Form').html(result.message);
                            // success2.hide();
                            // error2.show();
                            // App.scrollTo(error2, -200);
                        } else {
                            // alert(result.message);
                            // location.href = result.content;
                            location.href = "<?php echo $this->view->list_url ?>"
                        }
                    },
                    error: function() {
                        alert("异常！");
                        //$('.alert-error', $('#form_sample_2')).show();
                    }
                });
            }
        };

    }();
</script>