<script>
    var FormComponents = function() {

        return {
            //main function to initiate the module
            init: function() {
                <?php
                $schemas4Form = $this->view->schemas;
                $this->partial('partials/js/formelement');
                ?>

                <?php if ($this->view->actionName == 'edit') { ?>
                    $('.5e217e4051348-delete').unbind('click').click(function() {
                        var id = "<?php echo $this->view->row['_id'] ?>";
                        var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/remove';
                        var redirectUrl = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/list';

                        swal({
                            title: "确认删除?",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "确认",
                            showLoaderOnConfirm: true,
                            cancelButtonText: "取消",
                            preConfirm: function() {
                                return new Promise(function(resolve) {
                                    $.ajax({
                                        type: 'post',
                                        url: url,
                                        dataType: "json",
                                        data: {
                                            id: id,
                                            _method: 'delete',
                                            _token: LA.token,
                                        },
                                        success: function(data) {
                                            $.pjax({
                                                container: '#pjax-container',
                                                url: redirectUrl
                                            });
                                            // $.admin.redirect(redirectUrl);
                                            resolve(data);
                                        }
                                    });
                                });
                            }
                        }).then(function(result) {
                            console.log(result);
                            var data = result.value;
                            if (typeof data === 'object') {
                                if (!data.error) {
                                    swal(data.message, '', 'success');
                                } else {
                                    swal(data.message, '', 'error');
                                }
                            }
                        });
                    });

                    <?php foreach ($this->view->formTools as $key => $tool) { ?>
                        <?php if (!empty($tool['is_show'])) { ?>
                            $('.form-tool-<?php echo $key ?>').off('click').on('click', function(e) {
                                e.preventDefault();
                                var id = "<?php echo $this->view->row['_id'] ?>";
                                var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>?id=' + id;
                                // alert('ssssssss');
                                <?php if (empty($tool['process_without_modal'])) { ?>
                                    App.process4Modal(url, this);
                                <?php } else { ?>
                                    App.process4NoModal(url, this);
                                <?php } ?>
                            });
                        <?php } ?>
                    <?php } ?>
                <?php } ?>

                var form2 = $('#form_sample_2');
                form2.validate({
                    errorElement: 'span', //default input error message container
                    errorClass: 'control-label', // default input error message class
                    focusInvalid: false, // do not focus the last invalid input
                    ignore: "",
                    rules: {
                        <?php foreach ($this->view->schemas as $key => $field) { ?>
                            <?php if (!empty($field['validation']['required']) && !empty($field['form']['is_show'])) { ?>
                                <?php echo $key ?>: {
                                    //minlength: 2,
                                    required: true,
                                },
                            <?php } ?>
                        <?php } ?>
                    },

                    messages: { // custom messages for radio buttons and checkboxes
                        <?php foreach ($this->view->schemas as $key => $field) { ?>
                            <?php if (!empty($field['validation']['required']) && !empty($field['form']['is_show'])) { ?>
                                <?php echo $key ?>: {
                                    required: '<i class="fa fa-times-circle-o"></i>【<?php echo $field['form']['name'] ?>】字段是必填项.'
                                },
                            <?php } ?>
                        <?php } ?>
                    },

                    errorPlacement: function(error, element) { // render error placement for each input type
                        // var ele1 = $(element).closest('.input-group');
                        // // $(error).prepend('<i class="fa fa-times-circle-o"></i>');
                        // error.insertBefore(ele1);
                        error.insertBefore(element.closest('.input-group')); // for other inputs, just perform default behavoir

                    },

                    invalidHandler: function(event, validator) { //display error alert on form submit   
                        //success2.hide();
                        //error2.show();
                        // App.scrollTo(error2, -200);
                    },

                    highlight: function(element) { // hightlight error inputs
                        $(element)
                            .closest('.form-group').removeClass('success').addClass('has-error'); // set error class to the control group
                    },

                    unhighlight: function(element) { // revert the change dony by hightlight
                        $(element)
                            .closest('.form-group').removeClass('has-error'); // set error class to the control group
                    },

                    success: function(label) {
                        label
                            .closest('.form-group').removeClass('has-error').addClass('success'); // set success class to the control group
                    },

                    submitHandler: function(form) {
                        //success2.show();
                        //error2.hide();
                        $('#app-admin-alerts-errs').html("");
                        // $('#app-admin-alerts-div').hide();
                        alert("OK");
                        //form.submit();
                        FormComponents.submit();
                    }

                });

            },
            // 提交
            submit: function() {
                //alert("submit！");
                var formData = new FormData(document.getElementById("form_sample_2")); //
                formData.append("_token", LA.token);
                $.ajax({
                    //几个参数需要注意一下
                    type: "POST", //方法类型
                    dataType: "json", //预期服务器返回的数据类型
                    url: "<?php echo $this->view->form_act ?>",
                    contentType: false, //这里
                    processData: false, //这两个一定设置为false
                    data: formData,
                    //data: $('#form_sample_2').serialize(),
                    success: function(result) {
                        // console.log(result); //打印服务端返回的数据(调试用)
                        // 如果发生了错误的话
                        // var form2 = $('#form_sample_2');
                        // var error2 = $('.alert-error', form2);
                        // var success2 = $('.alert-success', form2);

                        if (result.error == 1) {
                            // alert(result.message);
                            var str = result.message;
                            var arr = str.split('||');
                            $errmsg = "";
                            $.each(arr, function(i, n) {
                                $errmsg += ("<p>" + n + "</p>");
                            });
                            $errmsg = '<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><h4><i class="icon fa fa-ban"></i>系统发生错误</h4>' + $errmsg + '</div>';
                            $('#app-admin-alerts-errs').html($errmsg);
                            // $('#app-admin-alerts-div').show();

                            // $('#resultId4Form').html(result.message);
                            // success2.hide();
                            // error2.show();
                            // App.scrollTo(error2, -200);
                        } else {
                            // alert(result.message);
                            // location.href = result.content;
                            location.href = "<?php echo $this->view->list_url ?>"
                        }
                    },
                    error: function(errormsg) {
                        // alert("异常！");
                        $errmsg += ("<p>" + errormsg + "</p>");
                        $errmsg = '<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><h4><i class="icon fa fa-ban"></i>系统发生错误</h4>' + errormsg + '</div>';
                        $('#app-admin-alerts-errs').html($errmsg);
                        // $('#app-admin-alerts-div').show();
                        //$('.alert-error', $('#form_sample_2')).show();
                    }
                });
            },
            validateAndSubmit: function() {
                if ($('#form_sample_2').validate().form()) {
                    FormComponents.submit();
                }
            }
        };

    }();
</script>