<script>
	var List = function() {

		return {
			url: '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>',
			imagepath: '<?php echo $this->view->baseUrl ?>backend/',
			compileFilter: function() {
				var data = new Object;
				/**
				for (var i in List.filter)
				{
					if (typeof(List.filter[i]) != "function" && typeof(List.filter[i]) != "undefined")
					{
						data[i] = encodeURIComponent(List.filter[i]);
					}
				}**/

				return data;
			},
			remove: function(id, cfm, opt) {
				opt = "remove";

				if (confirm(cfm)) {
					var data = List.compileFilter();
					data.id = encodeURIComponent(id);
					$.ajax({
						type: 'POST',
						url: List.url + "/" + opt,
						data: data,
						success: function(result) {
							if (result.message) {
								alert(result.message);
							}
							if (result.error == 0) {
								$('#example').DataTable().draw();
							}
						},
						dataType: "json"
					});
				}
			},
			toggle: function(obj, act, id, fieldname) {
				val = ($(obj).text() == 'yes') ? 0 : 1;

				var data = {};
				data.fieldname = encodeURIComponent(val);
				data.id = encodeURIComponent(id);

				$.ajax({
					type: 'POST',
					url: List.url + "/" + act,
					data: data,
					success: function(result) {
						if (result.message) {
							alert(result.message);
						}
						if (result.error == 0) {
							text = (result.content > 0) ? 'yes' : 'no';
							css = (result.content > 0) ? 'success' : 'danger';
							$(obj).text(text);
							$(obj).attr('class', 'label label-' + css);
						}
					},
					dataType: "json"
				});
			},
			edit: function(obj, act, id, fieldname) {
				var tag = obj.firstChild.tagName;
				if (typeof(tag) != "undefined" && tag.toLowerCase() == "input") {
					return;
				}

				/* 保存原始的内容 */
				var org = $(obj).html();
				var val = $(obj).text();

				/* 创建一个输入框 */
				var txt = $('<input type = "text" />');
				txt.val(val);
				txt.css("width", (obj.offsetWidth + 12) + "px");
				/* 编辑区输入事件处理函数 */
				txt.keypress(function(event) {
					if (event.which == 13) //enter
					{
						$(event.target).blur();
						return false;
					}
					if (event.which == 27) //esc
					{
						$(event.target).parent().html(org);
					}
				});
				/* 编辑区失去焦点的处理函数 */
				txt.blur(function(event) {
					var newval = $.trim($(event.target).val());
					if (newval.length > 0 && newval != val) {
						var data = new Object;
						data[fieldname] = encodeURIComponent(newval);
						data.id = encodeURIComponent(id);

						$.ajax({
							type: 'POST',
							url: List.url + "/" + act,
							data: data,
							success: function(res) {
								if (res.message) {
									alert(res.message);
								}
								$(event.target).parent().html((res.error == 0) ? res.content : org);
							},
							dataType: "json"
						});
					} else {
						$(event.target).parent().html(org);
					}
				});
				/* 隐藏对象中的内容，并将输入框加入到对象中 */
				$(obj).empty();
				$(obj).append(txt);
				txt.focus();
			},
			call: function(id, cfm, opt) {

				if (confirm(cfm)) {
					var data = List.compileFilter();
					data.id = encodeURIComponent(id);
					$.ajax({
						type: 'POST',
						url: List.url + "/" + opt,
						data: data,
						success: function(result) {
							console.info(result);
							if (result.message) {
								alert(result.message);
							}
							if (result.error == 0) {
								$('#example').DataTable().draw();
							}
						},
						dataType: "json"
					});
				}
			},
			//main function to initiate the module
			init: function() {

				$('.5e280b9811ada-filter-btn').unbind('click');
				$('.5e280b9811ada-filter-btn').click(function(e) {
					if ($('#filter-box').is(':visible')) {
						$('#filter-box').addClass('hide');
					} else {
						$('#filter-box').removeClass('hide');
					}
				});

				<?php foreach ($this->view->headerTools as $key => $tool) { ?>
					<?php if (!empty($tool['is_show']) && empty($tool['is_export'])) { ?>
						$('.header-tool-<?php echo $key ?>').off('click').on('click', function(e) {
							e.preventDefault();
							var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>';
							List.process4Modal(url, this);
						});
					<?php } ?>
				<?php } ?>

				//https://datatables.net/reference/option/#Features
				$('#example').dataTable({
					//"dom": '<"top"i>rt<"bottom"flp><"clear">',
					//"jQueryUI": true,
					"dom": 'rt<"bottom"ilp>',
					//dom: 'Bfrtip',
					//dom": '<"H"lfr>t<"F"ip>',
					// "buttons": ['csv', 'excel', 'pdf', 'print'],
					"autoWidth": true,
					"scrollX": true,
					"processing": true,
					"serverSide": true,
					"searching": false,
					"paging": true,
					"ordering": true,
					"order": [<?php echo $orderIdx ?>, '<?php echo $orderBy ?>'],
					"displayStart": 0,
					"lengthMenu": [1, 5, 10, 15, 100],
					"lengthChange": true,
					"pageLength": 30,
					"pagingType": "full_numbers",
					"ajax": {
						"url": "<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/query",
						"type": 'POST',
						"data": function(d) {
							// alert('datatable ajax');
							d = Search.getConditions(d);
							console.log(d);
						}
					},
					"columns": [
						<?php foreach ($this->view->schemas as $key => $field) { ?>
							<?php if (!empty($field['list']['is_show'])) { ?> {
									"data": "<?php echo isset($field['list']['list_data_name']) ? $field['list']['list_data_name'] : $key ?>",
									"name": "<?php echo $key ?>",
									<?php if ($field['data']['type'] == "boolean" && isset($field['list']['list_type']) && $field['list']['list_type'] == 1) { ?> "render": function(data, type, full, meta) {
											//console.info(data);
											if (data == 1) {
												return '<span <?php if (isset($field['list']['ajax'])) { ?>onclick="List.toggle(this, \'<?php echo $field['list']['ajax'] ?>\', \'' + full['_id'] + '\', \'<?php echo $key ?>\')"<?php } ?>class="label label-success">是</span>';
											} else {
												return '<span <?php if (isset($field['list']['ajax'])) { ?>onclick="List.toggle(this, \'<?php echo $field['list']['ajax'] ?>\', \'' + full['_id'] + '\', \'<?php echo $key ?>\')"<?php } ?>class="label label-danger">否</span>';
											};
										}
									<?php } elseif (($field['data']['type'] == "file" || $field['data']['type'] == "image") && isset($field['list']['render']) && $field['list']['render'] == 'img') { ?> "render": function(data, type, full, meta) {
											//console.info(data);
											<?php
											$path = "";
											if (!empty($field['data'][$field['data']['type']])) {
												$fileInfo = $field['data'][$field['data']['type']];
												$path = empty($fileInfo['path']) ? '' : trim($fileInfo['path'], '/') . '/';
											}
											?>
											return '<img src="<?php echo $this->view->baseUrl ?>service/file/index?upload_path=<?php echo trim($path, '/') ?>&id=' + data + '&w=50&h=50" style="max-height: 50px;" alt="">';
										}
									<?php } elseif (isset($field['list']['items'])) { ?> "render": function(data, type, full, meta) {
											//console.info(data);
											if (false) {
												return '<span class="label label-info"></span>';
												<?php
												$items = is_callable($field['list']['items']) ? $field['list']['items']() : $field['list']['items'];
												?>
												<?php foreach ($items as $itemKey => $item) { ?>
													<?php if (isset($item['value'])) { ?>
											} else if (data == '<?php echo $item['value'] ?>') {
												return '<span class="label label-info"><?php echo $item['name'] ?></span>';
											<?php } else { ?>
											} else if (data == '<?php echo $itemKey ?>') {
												return '<span class="label label-info"><?php echo $item ?></span>';
											<?php } ?>
											<?php } ?>
											} else {
												return '<span class="label label-info"></span>';
											};
										}
									<?php } elseif (isset($field['list']['ajax'])) { ?> "render": function(data, type, full, meta) {
											return '<span onclick="List.edit(this, \'<?php echo $field['list']['ajax'] ?>\', \'' + full['_id'] + '\', \'<?php echo $key ?>\')" >' + data + '</span>';
										}
									<?php } ?>
								},
							<?php } ?>
						<?php } ?> {
							"data": "operation",
							"orderable": false,
							"searchable": false,
							"render": function(data, type, full, meta) {
								var id = full['_id'];
								var editOp = '<a class="btn btn-sm btn-primary" href="<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/edit?id=' + id + '"><i class="fa fa-edit"></i>编辑</a>';
								var deleteOp = '<a class="btn btn-sm btn-danger" href="javascript:;" onclick="List.remove(\'' + id + '\', \'你确定要删除这条记录吗？\')"><i class="fa fa-trash"></i>删除</a>';
								var toolOps = [];
								<?php foreach ($this->view->rowTools as $key => $tool) { ?>
									<?php if (!empty($tool['is_show'])) { ?>
										var url = '<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>?id=' + id;
										var toolOp = '<a class="btn btn-sm btn-primary row-tool-<?php echo $key ?>" record_id="' + id + '" href="javascript:;" onclick="List.process4Modal(\'' + url + '\',this)" ><i class="fa fa-edit"></i><?php echo $tool['title'] ?></a>';
										toolOps.push(toolOp);
									<?php } ?>
								<?php } ?>
								var ops = '';
								$.each(toolOps, function(i, n) {
									ops += ("&nbsp;" + n);
								});

								return editOp + '&nbsp;' + deleteOp + '&nbsp;' + ops;
							}
						}
					]
				});
			},
			actionResolver: function(data) {
				var response = data[0];
				var target = data[1];

				if (typeof response !== 'object') {
					return $.admin.swal({
						type: 'error',
						title: 'Oops!'
					});
				}

				var then = function(then) {
					alert(then.action);
					if (then.action == 'refresh') {
						$.admin.reload();
					}

					if (then.action == 'download') {
						window.open(then.value, '_blank');
					}

					if (then.action == 'redirect') {
						$.admin.redirect(then.value);
					}
				};

				if (typeof response.html === 'string') {
					target.html(response.html);
				}

				if (typeof response.swal === 'object') {
					$.admin.swal(response.swal);
				}

				if (typeof response.toastr === 'object') {
					$.admin.toastr[response.toastr.type](response.toastr.content, '', response.toastr.options);
				}

				if (response.then) {
					then(response.then);
				}
			},
			actionCatcher: function(request) {
				if (request && typeof request.responseJSON === 'object') {
					$.admin.toastr.error(request.responseJSON.message, '', {
						positionClass: "toast-bottom-center",
						timeOut: 10000
					}).css("width", "500px")
				}
			},
			process4Modal: function(url, element) {
				var data = $(element).data();
				var target = $(element);
				var process = new Promise(function(resolve, reject) {
					// alert('click');
					Object.assign(data, {
						//_token: $.admin.token,
						_action: '<?php echo $tool['action'] ?>',
					});

					var formData1 = new FormData();
					for (var key in data) {
						formData1.append(key, data[key]);
					}

					$.ajax({
						type: 'GET',
						url: url,
						data: formData1,
						cache: false,
						contentType: false,
						processData: false,
						success: function(data) {
							// alert('success');
							console.log(data); //打印服务端返回的数据(调试用)
							if (!data.error) {
								resolve([data, target]);
								$('#app-admin-controllers-modal').html(data.content.content);
								var modalId = data.content.modal_id;
								$('#' + modalId).modal('show');
								$('#' + modalId + ' form').off('submit').on('submit', function(e) {
									e.preventDefault();
									// alert('form submit');
									var form2 = this;
									var process2 = new Promise(function(resolve, reject) {
										var data1 = [];
										Object.assign(data1, {
											//_token: $.admin.token,
											_action: '<?php echo $tool['action'] ?>',
										});

										var formData2 = new FormData(form2);
										for (var key in data1) {
											formData2.append(key, data1[key]);
										}

										$.ajax({
											type: "POST", //方法类型
											dataType: "json", //预期服务器返回的数据类型
											url: url,
											cache: false,
											contentType: false, //这里
											processData: false, //这两个一定设置为false
											data: formData2,
											success: function(data) {
												console.log(data); //打印服务端返回的数据(调试用)
												if (!data.error) {
													//{"status":true,
													//"then":{"action":"download","value":"http:\/\/190821fg0463demo.jdytoy.com\/admin\/admin-build\/download-file?file_id=20200203192717.csv"},
													//"toastr":{"type":"success","content":"Success\uff01","options":{"positionClass":"toast-top-center"}}}
													var request = {};
													request.status = true;
													// request.then = {};
													if (data.content.then) {
														request.then = data.content.then;
													}
													request.toastr = {};
													request.toastr.type = "success";
													request.toastr.content = data.message;
													request.toastr.options = {
														"positionClass": "toast-top-center"
													};
													resolve([request, target]);
													$('#' + modalId).modal('hide');
												} else {
													var request = {};
													request.responseJSON.message = data.message;
													reject(request);
												}
											},
											error: function(request) {
												reject(request);
											}
										});
									});
									process2.then(List.actionResolver).catch(List.actionCatcher);
								});
							} else {
								var request = {};
								request.responseJSON.message = data.message;
								reject(request);
							}
						},
						error: function(request) {
							console.log(request); //打印服务端返回的数据(调试用)
							alert(request);
							reject(request);
						}
					});
				});
				process.then(List.actionResolver).catch(List.actionCatcher);
			}

		};

	}();
</script>