<script>
    var ModalComponents = function() {

        return {
            //main function to initiate the module
            init: function() {

                <?php
                $schemas4Form = $this->view->fields;
                $this->partial('partials/js/formelement');
                // 输出一个换行符
                echo "\n";
                ?>
            }
        };

    }();
</script>