<script>
    var Search = function() {
        return {
            //main function to initiate the module
            init: function() {
                <?php foreach ($this->view->schemas as $key => $field) { ?>
                    <?php
                    $field['name'] = empty($field['search']['name']) ? $field['name'] : $field['search']['name'];
                    $field['search']['placeholder'] = empty($field['search']['placeholder']) ? "输入 " . $field['name'] : $field['search']['placeholder'];
                    $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                    $field['search']['items'] = empty($field['search']['items']) ? (!empty($field['form']['items']) ? $field['form']['items'] : array()) : $field['search']['items'];
                    $field['search']['is_show'] = !isset($field['search']['is_show']) ? $field['form']['is_show'] : $field['search']['is_show'];
                    $field['search']['cascadeSettings'] = empty($field['search']['cascadeSettings']) ? (!empty($field['form']['cascadeSettings']) ? $field['form']['cascadeSettings'] : array()) : $field['search']['cascadeSettings'];

                    ?>
                    <?php if (!empty($field['search']['is_show']) && !empty($field['search']['input_type'])) { ?>

                        <?php if ($field['search']['input_type'] == "datetimepicker") { ?>
                            $('#search_<?php echo $key ?>_from').datetimepicker({
                                "format": "YYYY-MM-DD HH:mm:ss",
                                "locale": "zh-CN"
                            });
                            $('#search_<?php echo $key ?>_to').datetimepicker({
                                "format": "YYYY-MM-DD HH:mm:ss",
                                "locale": "zh-CN",
                                "useCurrent": false
                            });
                            $("#search_<?php echo $key ?>_from").on("dp.change", function(e) {
                                $('#search_<?php echo $key ?>_to').data("DateTimePicker").minDate(e.date);
                            });
                            $("#search_<?php echo $key ?>_to").on("dp.change", function(e) {
                                $('#search_<?php echo $key ?>_from').data("DateTimePicker").maxDate(e.date);
                            });
                        <?php } elseif ($field['search']['input_type'] == "select" || $field['search']['input_type'] == "radio") { ?>
                            $('.<?php echo $key ?>').select2({
                                "allowClear": true,
                                "placeholder": {
                                    "id": "",
                                    "text": "<?php echo $field['name'] ?>"
                                }
                            });
                            <?php if ($field['search']['input_type'] == "select" && !empty($field['search']['cascadeSettings'])) { ?>
                                $('.<?php echo $field['search']['cascadeSettings']['source'] ?>').change(function() {
                                    var cascadeSelect = $('.<?php echo $key ?>');
                                    var selectedValue = $('.<?php echo $field['search']['cascadeSettings']['source'] ?>').val();
                                    cascadeSelect.empty();
                                    var data1 = [];
                                    Object.assign(data1, {
                                        _token: LA.token,
                                        <?php echo !empty($field['search']['cascadeSettings']['param_name'])?$field['search']['cascadeSettings']['param_name']:$field['search']['cascadeSettings']['source'] ?>: selectedValue,
                                    });
                                    var formData1 = {};
                                    for (var key in data1) {
                                        // formData1.append(key, data1[key]);
                                        formData1[key] = data1[key];
                                    }

                                    $.ajax({
                                        type: "<?php echo $field['search']['cascadeSettings']['type'] ?>", //方法类型
                                        url: '/<?php echo $field['search']['cascadeSettings']['url'] ?>',
                                        data: formData1,
                                        dataType: "json", //预期服务器返回的数据类型
                                        success: function(response) {
                                            console.log(response); //打印服务端返回的数据(调试用)
                                            if (!response.error) {
                                                // create the option and append to Select2
                                                var firstData = {
                                                    id: 0,
                                                    text: '请选择...'
                                                };
                                                response.content.unshift(firstData);
                                                response.content.forEach(item=>{
                                                    var option = new Option(item.text, item.id, false, false);
                                                    cascadeSelect.append(option);                                    
                                                });
                                                cascadeSelect.trigger('change');
                                                // manually trigger the `select2:select` event
                                                cascadeSelect.trigger({
                                                    type: 'select2:select',
                                                    params: {
                                                        data: response.content[0]
                                                    }
                                                });                                
                                            } else {
                                                
                                            }
                                        },
                                        error: function(request) {
                                            
                                        }
                                    });
                                });
                            <?php } ?>

                        <?php } elseif ($field['search']['input_type'] == "number") { ?>
                            $('.<?php echo $key ?>:not(.initialized)')
                                .addClass('initialized')
                                .bootstrapNumber({
                                    upClass: 'success',
                                    downClass: 'primary',
                                    center: true
                                });
                        <?php } ?>
                    <?php } ?>
                <?php } ?>

                //iCheck for checkbox and radio inputs
                $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                    checkboxClass: 'icheckbox_minimal-blue',
                    radioClass: 'iradio_minimal-blue'
                })
                //Red color scheme for iCheck
                $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                    checkboxClass: 'icheckbox_minimal-red',
                    radioClass: 'iradio_minimal-red'
                })
                //Flat red color scheme for iCheck
                $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                    checkboxClass: 'icheckbox_flat-green',
                    radioClass: 'iradio_flat-green'
                })

                $('#btnSearch').click(function(e) {
                    e.preventDefault();
                    $('#example').DataTable().draw();
                });

                $('#btnExport').click(function(e) {
                    e.preventDefault();
                    var d = Search.getConditions({});
                    var p = "";
                    $.each(d, function(i, n) {
                        p += ("&" + i + "=" + n);
                    });
                    var herf = "<?php echo $this->myTag->getUrl($this->view, 'export',array('m'=>'csv'));?>" + p;
                    //alert(herf);
                    window.location.href = herf;
                    //window.open(herf, '_blank');
                });

                <?php foreach ($this->view->headerTools as $key => $tool) { ?>
                    <?php if (!empty($tool['is_show']) && !empty($tool['is_export'])) { ?>
                        $('#btnExport-<?php echo $key ?>').click(function(e) {
                            e.preventDefault();
                            var d = Search.getConditions({});
                            var p = "";
                            $.each(d, function(i, n) {
                                p += ("&" + i + "=" + n);
                            });
                            var herf = "<?php echo $this->myTag->getUrl($this->view, $tool['action'],array('m'=>'csv'));?>" + p;
                            window.location.href = herf;
                            //window.open(herf, '_blank');
                        });
                    <?php } ?>
                <?php } ?>

            },
            getConditions: function(d) {
                <?php foreach ($this->view->schemas as $key => $field) { ?>
                    <?php
                    $field['search']['is_show'] = !isset($field['search']['is_show']) ? $field['form']['is_show'] : $field['search']['is_show'];
                    ?>
                    <?php if (!empty($field['search']['is_show'])) { ?>
                        <?php
                        $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                        if ($field['search']['input_type'] == "hidden") {
                            $field['search']['condition_type'] = 'period';
                        } elseif ($field['search']['input_type'] == "datetimepicker") {
                            $field['search']['condition_type'] = 'period';
                        } elseif ($field['search']['input_type'] == "number") {
                            $field['search']['condition_type'] = 'period';
                        }
                        ?>
                        <?php if (!empty($field['search']['condition_type']) && $field['search']['condition_type'] == 'period') { ?>
                            var searchkeyValue = ($('#search_<?php echo $key ?>_from').val() ? $('#search_<?php echo $key ?>_from').val() : "") + '|' + ($('#search_<?php echo $key ?>_to').val() ? $('#search_<?php echo $key ?>_to').val() : "");
                        <?php } else { ?>
                            var searchkeyValue = ($('#search_<?php echo $key ?>').val() ? $('#search_<?php echo $key ?>').val() : "");
                        <?php } ?>
                        // 如果是空值或|就不用传递参数
                        if(searchkeyValue !="" && searchkeyValue !='|'){
                            d.<?php echo $key ?> = encodeURIComponent(searchkeyValue);
                        }
                    <?php } ?>
                <?php } ?>
                return d;
            }
        };
    }();
</script>