<script>
    var Search = function() {
        return {
            //main function to initiate the module
            init: function() {
                <?php foreach ($this->view->schemas as $key => $field) { ?>
                    <?php
                    $field['name'] = empty($field['search']['name']) ? $field['name'] : $field['search']['name'];
                    $field['search']['placeholder'] = empty($field['search']['placeholder']) ? "输入 " . $field['name'] : $field['search']['placeholder'];
                    $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                    $field['search']['items'] = empty($field['search']['items']) ? $field['form']['items'] : $field['search']['items'];
                    ?>
                    <?php if (!empty($field['search']['is_show']) && !empty($field['search']['input_type'])) { ?>

                        <?php if ($field['search']['input_type'] == "datetimepicker") { ?>
                            $('#search_<?php echo $key ?>_from').datetimepicker({
                                "format": "YYYY-MM-DD HH:mm:ss",
                                "locale": "zh-CN"
                            });
                            $('#search_<?php echo $key ?>_to').datetimepicker({
                                "format": "YYYY-MM-DD HH:mm:ss",
                                "locale": "zh-CN",
                                "useCurrent": false
                            });
                            $("#search_<?php echo $key ?>_from").on("dp.change", function(e) {
                                $('#search_<?php echo $key ?>_to').data("DateTimePicker").minDate(e.date);
                            });
                            $("#search_<?php echo $key ?>_to").on("dp.change", function(e) {
                                $('#search_<?php echo $key ?>_from').data("DateTimePicker").maxDate(e.date);
                            });
                        <?php } elseif ($field['search']['input_type'] == "select" || $field['search']['input_type'] == "radio") { ?>
                            $('.<?php echo $key ?>').select2({
                                "allowClear": true,
                                "placeholder": {
                                    "id": "",
                                    "text": "<?php echo $field['name'] ?>"
                                }
                            });
                        <?php } elseif ($field['search']['input_type'] == "ueditor") { ?>
                            UE.delEditor("<?php echo $key ?>");
                            var ue_<?php echo $key ?> = UE.getEditor('<?php echo $key ?>');
                        <?php } elseif ($field['search']['input_type'] == "ckeditor") { ?>
                            CKEDITOR.replace('<?php echo $key ?>');
                        <?php } elseif ($field['search']['input_type'] == "number") { ?>
                            $('.<?php echo $key ?>:not(.initialized)')
                                .addClass('initialized')
                                .bootstrapNumber({
                                    upClass: 'success',
                                    downClass: 'primary',
                                    center: true
                                });
                        <?php } ?>
                    <?php } ?>
                <?php } ?>

                //iCheck for checkbox and radio inputs
                $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                    checkboxClass: 'icheckbox_minimal-blue',
                    radioClass: 'iradio_minimal-blue'
                })
                //Red color scheme for iCheck
                $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                    checkboxClass: 'icheckbox_minimal-red',
                    radioClass: 'iradio_minimal-red'
                })
                //Flat red color scheme for iCheck
                $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                    checkboxClass: 'icheckbox_flat-green',
                    radioClass: 'iradio_flat-green'
                })

                $('#btnSearch').click(function(e) {
                    e.preventDefault();
                    $('#example').DataTable().draw();
                });

                $('#btnExport').click(function(e) {
                    e.preventDefault();
                    var d = Search.getConditions({});
                    var p = "";
                    $.each(d, function(i, n) {
                        p += ("&" + i + "=" + n);
                    });
                    window.location.href = "<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/export?m=csv" + p;
                    //window.open("<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/export?m=csv" + p, '_blank');
                });

                <?php foreach ($this->view->headerTools as $key => $tool) { ?>
                    <?php if (!empty($tool['is_show']) && !empty($tool['is_export'])) { ?>
                        $('#btnExport-<?php echo $key ?>').click(function(e) {
                            e.preventDefault();
                            var d = Search.getConditions({});
                            var p = "";
                            $.each(d, function(i, n) {
                                p += ("&" + i + "=" + n);
                            });
                            window.location.href = "<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>?m=csv" + p;
                            //window.open("<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/<?php echo $tool['action'] ?>?m=csv" + p, '_blank');
                        });
                    <?php } ?>
                <?php } ?>

            },
            getConditions: function(d) {
                <?php foreach ($this->view->schemas as $key => $field) { ?>
                    <?php if (!empty($field['search']['is_show'])) { ?>
                        <?php
                        $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                        if ($field['search']['input_type'] == "hidden") {
                            $field['search']['condition_type'] = 'period';
                        } elseif ($field['search']['input_type'] == "datetimepicker") {
                            $field['search']['condition_type'] = 'period';
                        } elseif ($field['search']['input_type'] == "number") {
                            $field['search']['condition_type'] = 'period';
                        }
                        ?>
                        <?php if (!empty($field['search']['condition_type']) && $field['search']['condition_type'] == 'period') { ?>
                            d.<?php echo $key ?> = encodeURIComponent(($('#search_<?php echo $key ?>_from').val() ? $('#search_<?php echo $key ?>_from').val() : "") + '|' + ($('#search_<?php echo $key ?>_to').val() ? $('#search_<?php echo $key ?>_to').val() : ""));
                        <?php } else { ?>
                            d.<?php echo $key ?> = encodeURIComponent(($('#search_<?php echo $key ?>').val() ? $('#search_<?php echo $key ?>').val() : ""));
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
                return d;
            }
        };
    }();
</script>