<input type="hidden" id="pageID" value="security">
<input type="hidden" id="subpage" value="emailcheckingok">
<div class="sidebar_main clrfix fr">
    <div class="g-purchase-title bor-bot">
        <span class="gray3">新邮箱验证</span>
    </div>
    <!-- 绑定成功 -->
    <div class="z-content">
        <div class="suc-wrap">
            <div class="s-man"></div>
            <div class="s-info">
                <b class="orange">验证成功！</b>
                <p>您现在可以使用您的新手机号<b class="orange">15821039514</b>或者邮箱账号<b class="orange">dhtnuieeq@qq.com</b>进行登录！</p>
                <p>
                    您还可以：<a href="/" class="blue">开始集资购</a>
                    <a href="SecurityIndex.html" class="blue">去账户安全中心</a>
                </p>
                <p>如果没有任何操作，系统将在<b class="orange" id="spanNum" onload="checkingokFun()">10</b>秒后自动跳转到账户安全中心！</p>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>