<input type="hidden" id="pageID" value="updatepassword">
<div class="sidebar_main clrfix fr">
    <div class="g-purchase-title bor-bot">
        <span class="gray3">修改密码</span>
    </div>
    <div class="z-content">
        <div class="person-wrap change-code">
            <ul class="person-list">
                <li>
                    <span class="l-side">原始密码：</span>
                    <span class="r-side">
                        <div class="inp-wrap">
                            <input id="OldPass" maxlength="20" type="password" class="code-inner">
                            <span class="get-code-btn">请输入原始密码</span>
                        </div>
                    </span>
                    <div id="div_tips1"></div>
                </li>
                <li>
                    <span class="l-side">新密码：</span>
                    <span class="r-side">
                        <div class="inp-wrap">
                            <input id="NewPass" maxlength="20" type="password" class="code-inner">
                            <span class="get-code-btn">密码由8-20位字母、数字或符号两种或以上组合</span>
                        </div>
                        <span id="pwdStrength" style="display: none;"></span>
                    </span>
                    <div id="div_tips2"></div>
                </li>
                <li>
                    <span class="l-side">再次输入密码：</span>
                    <span class="r-side">
                        <div class="inp-wrap">
                            <input id="NewPassAgain" maxlength="20" type="password" class="code-inner">
                            <span class="get-code-btn">请输入确认密码</span>
                        </div>
                    </span>
                    <div id="div_tips3"></div>
                </li>
                <li>
                    <span class="l-side"></span>
                    <span class="r-side">
                        <a id="btnSubmitSave" href="javascript:;" class="set-save-btn">保存</a>
                    </span>
                </li>
            </ul>
        </div>

    </div>
    <a href="javascript:history.go(-1);" class="return-btn">返回</a>
</div>