<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">Environment</h3>

    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
      </button>
      <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
    </div>
  </div>

  <!-- /.box-header -->
  <div class="box-body">
    <div class="table-responsive">
      <table class="table table-striped">

        <?php foreach ($this->view->envs as $env) { ?>
          <tr>
            <td width="120px"><?php echo $env['name'] ?></td>
            <td><?php echo $env['value'] ?></td>
          </tr>
        <?php } ?>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.box-body -->
</div>