<div class="row">
    <div class="col-md-12">
        <?php if ($this->view->view1 == 'table') { ?>
            <style>
                .files>li {
                    float: left;
                    width: 150px;
                    border: 1px solid #eee;
                    margin-bottom: 10px;
                    margin-right: 10px;
                    position: relative;
                }

                .file-icon {
                    text-align: left;
                    font-size: 25px;
                    color: #666;
                    display: block;
                    float: left;
                }

                .action-row {
                    text-align: center;
                }

                .file-name {
                    font-weight: bold;
                    color: #666;
                    display: block;
                    overflow: hidden !important;
                    white-space: nowrap !important;
                    text-overflow: ellipsis !important;
                    float: left;
                    margin: 7px 0px 0px 10px;
                }

                .file-icon.has-img>img {
                    max-width: 100%;
                    height: auto;
                    max-height: 30px;
                }
            </style>
        <?php } else { ?>
            <style>
                .files>li {
                    float: left;
                    width: 150px;
                    border: 1px solid #eee;
                    margin-bottom: 10px;
                    margin-right: 10px;
                    position: relative;
                }

                .files>li>.file-select {
                    position: absolute;
                    top: -4px;
                    left: -1px;
                }

                .file-icon {
                    text-align: center;
                    font-size: 65px;
                    color: #666;
                    display: block;
                    height: 100px;
                }

                .file-info {
                    text-align: center;
                    padding: 10px;
                    background: #f4f4f4;
                }

                .file-name {
                    font-weight: bold;
                    color: #666;
                    display: block;
                    overflow: hidden !important;
                    white-space: nowrap !important;
                    text-overflow: ellipsis !important;
                }

                .file-size {
                    color: #999;
                    font-size: 12px;
                    display: block;
                }

                .files {
                    list-style: none;
                    margin: 0;
                    padding: 0;
                }

                .file-icon.has-img {
                    padding: 0;
                }

                .file-icon.has-img>img {
                    max-width: 100%;
                    height: auto;
                    max-height: 92px;
                }
            </style>
        <?php } ?>

        <div class="row">
            <!-- /.col -->
            <div class="col-md-12">
                <div class="box box-primary">

                    <div class="box-body no-padding">

                        <div class="mailbox-controls with-border">
                            <div class="btn-group">
                                <a href="" type="button" class="btn btn-default btn media-reload" title="Refresh">
                                    <i class="fa fa-refresh"></i>
                                </a>
                                <a type="button" class="btn btn-default btn file-delete-multiple" title="Delete">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </div>
                            <!-- /.btn-group -->
                            <label class="btn btn-default btn">
                                <i class="fa fa-upload"></i>&nbsp;&nbsp;上传
                                <form action="" method="post" class="file-upload-form" enctype="multipart/form-data">
                                    <input type="file" name="files[]" class="hidden file-upload" multiple="">
                                    <input type="hidden" name="dir" value="<?php echo $this->view->path1 ?>">
                                    <input type="hidden" name="view" value="<?php echo $this->view->view1 ?>">
                                    <input type="hidden" name="_token" value="<?php echo $this->view->csrf_token ?>">
                                </form>
                            </label>

                            <!-- /.btn-group -->
                            <a class="btn btn-default btn" data-toggle="modal" data-target="#newFolderModal">
                                <i class="fa fa-folder"></i>&nbsp;&nbsp;新建文件夹
                            </a>

                            <div class="btn-group">
                                <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('view' => 'table', 'path' => $this->view->path1)); ?>" class="btn btn-default active"><i class="fa fa-list"></i></a>
                                <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('view' => 'list', 'path' => $this->view->path1)); ?>" class="btn btn-default"><i class="fa fa-th"></i></a>
                            </div>


                            <div class="input-group input-group-sm pull-right goto-url" style="width: 250px;">
                                <input type="text" name="path" class="form-control pull-right" value="<?php echo $this->view->path1 ?>">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-arrow-right"></i></button>
                                </div>
                            </div>


                        </div>

                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <ol class="breadcrumb" style="margin-bottom: 10px;">
                            <li><a href="<?php echo $this->myTag->getUrl($this->view, 'list', array()); ?>"><i class="fa fa-th-large"></i> </a></li>
                            <?php $pathname2 = ""; ?>
                            <?php foreach ($this->view->pathArr as $pathname) {
                                $pathname2 = ltrim($pathname2 . '/' . $pathname, '/');
                            ?>
                                <li><a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('path' => $pathname2)); ?>"> <?php echo $pathname; ?></a></li>
                            <?php } ?>
                        </ol>

                        <?php if ($this->view->view1 == 'table') { ?>
                            <table class="table table-hover">
                                <tbody>
                                    <tr>
                                        <th width="40px;">
                                            <span class="file-select-all">
                                                <input type="checkbox" value="" />
                                            </span>
                                        </th>
                                        <th>名称</th>
                                        <th></th>
                                        <th width="200px;">时间</th>
                                        <th width="100px;">大小</th>
                                    </tr>
                                    <?php foreach ($this->view->files as $fileInfo) { ?>
                                        <tr>
                                            <td style="padding-top: 15px;">
                                                <span class="file-select">
                                                    <input type="checkbox" value="<?php echo $fileInfo['path']; ?>" />
                                                </span>
                                            </td>
                                            <td>
                                                <?php if ($fileInfo['is_dir']) { ?>
                                                    <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('path' => $fileInfo['path'])); ?>"><span class="file-icon text-aqua"><i class="fa fa-folder"></i></span></a>

                                                    <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('path' => $fileInfo['path'])); ?>" class="file-name" title="<?php echo $fileInfo['path']; ?>">
                                                        <?php echo $fileInfo['name']; ?>
                                                    </a>
                                                <?php } else { ?>
                                                    <?php if ($fileInfo['has_img']) { ?>
                                                        <span class="file-icon has-img">
                                                            <a href="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>" class="grid-popup-link">
                                                                <img src="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>" style="max-width:50px;max-height:50px" class="img img-thumbnail" alt="Attachment">
                                                            </a>
                                                        </span>
                                                    <?php } else { ?>
                                                        <span class="file-icon"><i class="fa <?php echo $fileInfo['file_icon']; ?>"></i></span>
                                                    <?php } ?>
                                                    <a target="_blank" href="<?php echo $this->myTag->getUrl($this->view, 'download', array('file' => $fileInfo['path'], '__SHOWBYIFRAME__' => 0)); ?>" class="file-name" title="<?php echo $fileInfo['path']; ?>">
                                                        <?php echo $fileInfo['name']; ?>
                                                    </a>
                                                <?php } ?>
                                            </td>

                                            <td class="action-row">
                                                <div class="btn-group btn-group-xs hide">
                                                    <a class="btn btn-default file-rename" data-toggle="modal" data-target="#moveModal" data-name="<?php echo $fileInfo['path']; ?>"><i class="fa fa-edit"></i></a>
                                                    <a class="btn btn-default file-delete" data-path="<?php echo $fileInfo['path']; ?>"><i class="fa fa-trash"></i></a>
                                                    <?php if (!$fileInfo['is_dir']) { ?>
                                                        <a target="_blank" href="<?php echo $this->myTag->getUrl($this->view, 'download', array('file' => $fileInfo['path'], '__SHOWBYIFRAME__' => 0)); ?>" class="btn btn-default"><i class="fa fa-download"></i></a>
                                                    <?php } ?>
                                                    <a class="btn btn-default" data-toggle="modal" data-target="#urlModal" data-url="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>"><i class="fa fa-internet-explorer"></i></a>
                                                </div>

                                            </td>

                                            <td><?php echo $fileInfo['modified']; ?>&nbsp;</td>
                                            <td><?php echo $fileInfo['size']; ?>&nbsp;</td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        <?php } else { ?>
                            <ul class="files clearfix">
                                <?php foreach ($this->view->files as $fileInfo) { ?>
                                    <li>
                                        <span class="file-select">
                                            <input type="checkbox" value="<?php echo $fileInfo['path']; ?>" />
                                        </span>
                                        <?php if ($fileInfo['is_dir']) { ?>
                                            <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('view' => 'list', 'path' => $fileInfo['path'])); ?>"><span class="file-icon text-aqua"><i class="fa fa-folder"></i></span></a>
                                        <?php } else { ?>
                                            <?php if ($fileInfo['has_img']) { ?>
                                                <span class="file-icon has-img">
                                                    <a href="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>" class="grid-popup-link">
                                                        <img src="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>" style="max-width:50px;max-height:50px" class="img img-thumbnail" alt="Attachment">
                                                    </a>
                                                </span>
                                            <?php } else { ?>
                                                <span class="file-icon"><i class="fa <?php echo $fileInfo['file_icon']; ?>"></i></span>
                                            <?php } ?>
                                        <?php } ?>

                                        <div class="file-info">
                                            <?php if ($fileInfo['is_dir']) { ?>
                                                <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('view' => 'list', 'path' => $fileInfo['path'])); ?>" class="file-name" title="<?php echo $fileInfo['path']; ?>">
                                                    <?php echo $fileInfo['name']; ?>
                                                </a>
                                            <?php } else { ?>
                                                <a target="_blank" href="<?php echo $this->myTag->getUrl($this->view, 'download', array('file' => $fileInfo['path'], '__SHOWBYIFRAME__' => 0)); ?>" class="file-name" title="files/class.Diff.php">
                                                    <?php echo $fileInfo['name']; ?>
                                                </a>
                                            <?php } ?>

                                            <span class="file-size">
                                                <?php echo $fileInfo['size']; ?>&nbsp;

                                                <div class="btn-group btn-group-xs pull-right">
                                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                        <span class="sr-only">Toggle Dropdown</span>
                                                    </button>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#" class="file-rename" data-toggle="modal" data-target="#moveModal" data-name="<?php echo $fileInfo['path']; ?>">Rename &amp; Move</a></li>
                                                        <li><a href="#" class="file-delete" data-path="<?php echo $fileInfo['path']; ?>">Delete</a></li>
                                                        <?php if (!$fileInfo['is_dir']) { ?>
                                                            <li><a target="_blank" href="<?php echo $this->myTag->getUrl($this->view, 'download', array('file' => $fileInfo['path'], '__SHOWBYIFRAME__' => 0)); ?>">Download</a></li>
                                                        <?php } ?>
                                                        <li class="divider">
                                                        </li>
                                                        <li><a href="#" data-toggle="modal" data-target="#urlModal" data-url="<?php echo $this->myTag->getUploadFilePath(trim($fileInfo['path'], '/')) ?>">Url</a></li>
                                                    </ul>
                                                </div>
                                            </span>
                                        </div>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                    <!-- /.box-footer -->
                    <!-- /.box-footer -->
                </div>
                <!-- /. box -->
            </div>
            <!-- /.col -->
        </div>

        <div class="modal fade" id="moveModal" tabindex="-1" role="dialog" aria-labelledby="moveModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title" id="moveModalLabel">Rename &amp; Move</h4>
                    </div>
                    <form id="file-move">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Path:</label>
                                <input type="text" class="form-control" name="new">
                            </div>
                            <input type="hidden" name="path">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="modal fade" id="urlModal" tabindex="-1" role="dialog" aria-labelledby="urlModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title" id="urlModalLabel">Url</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="newFolderModal" tabindex="-1" role="dialog" aria-labelledby="newFolderModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title" id="newFolderModalLabel">New folder</h4>
                    </div>
                    <form id="new-folder">
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control" name="name">
                            </div>
                            <input type="hidden" name="dir" value="<?php echo $this->view->path1 ?>">
                            <input type="hidden" name="_token" value="<?php echo $this->view->csrf_token ?>">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $('.file-delete').click(function() {

            var path = $(this).data('path');

            swal({
                title: "确认删除?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "确认",
                showLoaderOnConfirm: true,
                closeOnConfirm: false,
                cancelButtonText: "取消",
                preConfirm: function() {
                    return new Promise(function(resolve) {

                        $.ajax({
                            method: 'delete',
                            url: '<?php echo $this->myTag->getUrl($this->view, 'delete', array('__SHOWBYIFRAME__' => 0)); ?>',
                            data: {
                                'files': path,
                                _token: LA.token
                            },
                            success: function(data) {
                                $.pjax.reload('#pjax-container');

                                resolve(data);
                            }
                        });

                    });
                }
            }).then(function(result) {
                var data = result;
                if (typeof data === 'object') {
                    if (!data.error) {
                        swal(data.message, '', 'success');
                    } else {
                        swal(data.message, '', 'error');
                    }
                }
            });
        });

        $('#moveModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget);
            var name = button.data('name');

            var modal = $(this);
            modal.find('[name=path]').val(name)
            modal.find('[name=new]').val(name)
        });

        $('#urlModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget);
            var url = button.data('url');

            $(this).find('input').val(url)
        });

        $('.file-upload-form').on('submit', function(event) {

            event.preventDefault();

            var formData = new FormData(this);

            $.ajax({
                method: 'POST',
                url: '<?php echo $this->myTag->getUrl($this->view, 'upload', array('__SHOWBYIFRAME__' => 0)); ?>',
                data: formData,
                async: false,
                success: function(data) {
                    $.pjax.reload('#pjax-container');
                    if (typeof data === 'object') {
                        if (!data.error) {
                            // console.log(data);
                            // console.log(typeof data);
                            toastr.success(data.message);
                        } else {
                            toastr.error(data.message);
                        }
                    }
                },
                cache: false,
                contentType: false,
                processData: false
            });
        });

        $('#file-move').on('submit', function(event) {

            event.preventDefault();

            var form = $(this);

            var path = form.find('[name=path]').val();
            var name = form.find('[name=new]').val();

            $.ajax({
                method: 'put',
                url: '<?php echo $this->myTag->getUrl($this->view, 'move', array('__SHOWBYIFRAME__' => 0)); ?>',
                data: {
                    path: path,
                    'new': name,
                    _token: LA.token,
                },
                success: function(data) {
                    $.pjax.reload('#pjax-container');

                    if (typeof data === 'object') {
                        if (!data.error) {
                            toastr.success(data.message);
                        } else {
                            toastr.error(data.message);
                        }
                    }
                }
            });

            closeModal();
        });

        $('.file-upload').on('change', function() {
            $('.file-upload-form').submit();
        });

        $('#new-folder').on('submit', function(event) {

            event.preventDefault();

            var formData = new FormData(this);

            $.ajax({
                method: 'POST',
                url: '<?php echo $this->myTag->getUrl($this->view, 'folder', array('__SHOWBYIFRAME__' => 0)); ?>',
                data: formData,
                async: false,
                success: function(data) {
                    $.pjax.reload('#pjax-container');

                    if (typeof data === 'object') {
                        if (!data.error) {
                            toastr.success(data.message);
                        } else {
                            toastr.error(data.message);
                        }
                    }
                },
                cache: false,
                contentType: false,
                processData: false
            });

            closeModal();
        });

        function closeModal() {
            $("#moveModal").modal('toggle');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
        }

        $('.media-reload').click(function() {
            $.pjax.reload('#pjax-container');
        });

        $('.goto-url button').click(function() {
            var path = $('.goto-url input').val();
            $.pjax({
                container: '#pjax-container',
                url: '<?php echo $this->myTag->getUrl($this->view, 'list', array()); ?>&path=' + path
            });
        });

        $('.files-select-all').on('ifChanged', function(event) {
            if (this.checked) {
                $('.grid-row-checkbox').iCheck('check');
            } else {
                $('.grid-row-checkbox').iCheck('uncheck');
            }
        });

        $('.file-select input').iCheck({
            checkboxClass: 'icheckbox_minimal-blue'
        }).on('ifChanged', function() {
            if (this.checked) {
                $(this).closest('tr').css('background-color', '#ffffd5');
            } else {
                $(this).closest('tr').css('background-color', '');
            }
        });

        $('.file-select-all input').iCheck({
            checkboxClass: 'icheckbox_minimal-blue'
        }).on('ifChanged', function() {
            if (this.checked) {
                $('.file-select input').iCheck('check');
            } else {
                $('.file-select input').iCheck('uncheck');
            }
        });

        $('.file-delete-multiple').click(function() {
            var files = $(".file-select input:checked").map(function() {
                return $(this).val();
            }).toArray();

            if (!files.length) {
                return;
            }

            swal({
                title: "确认删除?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "确认",
                showLoaderOnConfirm: true,
                closeOnConfirm: false,
                cancelButtonText: "取消",
                preConfirm: function() {
                    return new Promise(function(resolve) {

                        $.ajax({
                            method: 'delete',
                            url: '<?php echo $this->myTag->getUrl($this->view, 'delete', array('__SHOWBYIFRAME__' => 0)); ?>',
                            data: {
                                'files': files.toString(),
                                _token: LA.token
                            },
                            success: function(data) {
                                $.pjax.reload('#pjax-container');

                                resolve(data);
                            }
                        });

                    });
                }
            }).then(function(result) {
                var data = result;
                if (typeof data === 'object') {
                    if (!data.error) {
                        swal(data.message, '', 'success');
                    } else {
                        swal(data.message, '', 'error');
                    }
                }
            });
        });

        $('table>tbody>tr').mouseover(function() {
            $(this).find('.btn-group').removeClass('hide');
        }).mouseout(function() {
            $(this).find('.btn-group').addClass('hide');
        });

        $('.grid-popup-link').magnificPopup({
            "type": "image",
            "gallery": {
                "enabled": true,
                "preload": [0, 2],
                "navigateByImgClick": true,
                "arrowMarkup": "<button title=\"%title%\" type=\"button\" class=\"mfp-arrow mfp-arrow-%dir%\"><\/button>",
                "tPrev": "Previous (Left arrow key)",
                "tNext": "Next (Right arrow key)",
                "tCounter": "<span class=\"mfp-counter\">%curr% of %total%<\/span>"
            },
            "mainClass": "mfp-with-zoom",
            "zoom": {
                "enabled": true,
                "duration": 300,
                "easing": "ease-in-out"
            }
        });

    });
</script>