<link rel="stylesheet" type="text/css" href="css/Comm.css" />
<link rel="stylesheet" type="text/css" href="css/ygRecord.css" />
<script type="text/javascript" src="/member/datepicker/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/member/datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="/member/datepicker/css/bootstrap.css" />
<input type="hidden" id="pageID" value="newestbuyrecords">
<script type="text/javascript" src="js/buyrecords.js"></script>
<div class="ygRecord">
    <h3>
        <span>最新云购记录</span><p style="color:#333333;">本页显示最新云购记录<strong class="num100"></strong>条 <a href="/yungou/index/historybuyrecords">查看历史云购记录&gt;&gt;</a></p>
    </h3>
    <ul class="Record_title">
        <li class="time">云购时间</li>
        <li class="nem">会员账号</li>
        <li class="name">云购商品名称</li>
        <li class="much">云购人次</li>
    </ul>
    <div id="recordList"></div>
    <div class="endpage" style="color:#333333;">本页显示最新云购记录<strong class="num100"></strong>条 <a href="/yungou/index/historybuyrecords" rel="nofollow">查看历史云购记录&gt;&gt;</a></div>
</div>