<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Basic info</h3>
                <div class="box-tools pull-right">
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body" style="display: block;">
                <form method="POST" action="https://demo.laravel-admin.org/_handle_form_" class="form-horizontal" accept-charset="UTF-8" pjax-container="1">
                    <div class="box-body fields-group">

                        <div class="form-group  ">

                            <label for="username" class="col-sm-2  control-label">Username</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>

                                    <input type="text" id="username" name="username" value="" class="form-control username" placeholder="输入 Username" />


                                </div>


                            </div>
                        </div>
                        <div class="form-group  ">

                            <label for="email" class="col-sm-2  control-label">Email</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>

                                    <input type="email" id="email" name="email" value="" class="form-control email" placeholder="输入 Email" />


                                </div>


                            </div>
                        </div>
                        <input type="hidden" name="_url" value="https://demo.laravel-admin.org/forms/register" class="_url" />

                        <input type="hidden" name="_current" value="info" class="_current" />

                        <input type="hidden" name="_steps" value="info,profile,password" class="_steps" />

                        <hr>
                        <div class="form-group">
                            <label class="col-sm-2  control-label"></label>
                            <div class="col-sm-8">
                                <button class="btn btn-info pull-right">下一步</button>
                            </div>
                        </div>
                        <input type="hidden" name="_form_" value="App\Admin\Forms\Steps\Info" class="_form_" />


                    </div>

                    <input type="hidden" name="_token" value="Fz08SJJEVxup3rBDxFmqY2BA0A6F29TzsEEq0c5V">

                    <!-- /.box-body -->
                </form>

            </div><!-- /.box-body -->
        </div>

        <script>

        </script>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Input profile</h3>
                <div class="box-tools pull-right">
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="display: block;">
                <form method="POST" action="https://demo.laravel-admin.org/_handle_form_" class="form-horizontal" accept-charset="UTF-8" pjax-container="1" enctype="multipart/form-data">
                    <div class="box-body fields-group">

                        <div class="form-group  ">

                            <label for="mobile" class="col-sm-2  control-label">Mobile</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-phone fa-fw"></i></span>

                                    <input style="width: 150px" type="text" id="mobile" name="mobile" value="" class="form-control mobile" placeholder="输入 Mobile">
                                </div>


                            </div>
                        </div>
                        <div class="form-group  ">

                            <label for="avatar" class="col-sm-2  control-label">Avatar</label>

                            <div class="col-sm-8">


                                <input type="file" class="avatar" name="avatar">
                            </div>
                        </div>

                        <div class="form-group  ">

                            <label for="address" class="col-sm-2 asterisk control-label">Address</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-pencil fa-fw"></i></span>

                                    <input required="1" type="text" id="address" name="address" value="" class="form-control address" placeholder="输入 Address">
                                </div>


                            </div>
                        </div>
                        <input type="hidden" name="_url" value="https://demo.laravel-admin.org/forms/register" class="_url"><input type="hidden" name="_current" value="profile" class="_current"><input type="hidden" name="_steps" value="info,profile,password" class="_steps">
                        <hr>
                        <div class="form-group">
                            <label class="col-sm-2  control-label"></label>
                            <div class="col-sm-8">
                                <a href="https://demo.laravel-admin.org/forms/register?step=info" class="btn btn-warning pull-left">上一步</a><button class="btn btn-info pull-right">下一步</button>
                            </div>
                        </div>
                        <input type="hidden" name="_form_" value="App\Admin\Forms\Steps\Profile" class="_form_">
                    </div>

                    <input type="hidden" name="_token" value="Fz08SJJEVxup3rBDxFmqY2BA0A6F29TzsEEq0c5V"><!-- /.box-body -->
                </form>

            </div>
            <!-- /.box-body -->
        </div>

        <script>

        </script>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Input password</h3>
                <div class="box-tools pull-right">
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="display: block;">
                <form method="POST" action="https://demo.laravel-admin.org/_handle_form_" class="form-horizontal" accept-charset="UTF-8" pjax-container="1">
                    <div class="box-body fields-group">

                        <div class="form-group  ">

                            <label for="password" class="col-sm-2  control-label">Password</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-eye-slash fa-fw"></i></span>

                                    <input type="password" id="password" name="password" value="" class="form-control password" placeholder="输入 Password">
                                </div>


                            </div>
                        </div>
                        <div class="form-group  ">

                            <label for="password_confirmation" class="col-sm-2  control-label">Password confirmation</label>

                            <div class="col-sm-8">


                                <div class="input-group">

                                    <span class="input-group-addon"><i class="fa fa-eye-slash fa-fw"></i></span>

                                    <input type="password" id="password_confirmation" name="password_confirmation" value="" class="form-control password_confirmation" placeholder="输入 Password confirmation">
                                </div>


                            </div>
                        </div>
                        <input type="hidden" name="_url" value="https://demo.laravel-admin.org/forms/register" class="_url"><input type="hidden" name="_current" value="password" class="_current"><input type="hidden" name="_steps" value="info,profile,password" class="_steps">
                        <hr>
                        <div class="form-group">
                            <label class="col-sm-2  control-label"></label>
                            <div class="col-sm-8">
                                <a href="https://demo.laravel-admin.org/forms/register?step=profile" class="btn btn-warning pull-left">上一步</a><button class="btn btn-info pull-right">提交</button>
                            </div>
                        </div>
                        <input type="hidden" name="_form_" value="App\Admin\Forms\Steps\Password" class="_form_">
                    </div>

                    <input type="hidden" name="_token" value="Fz08SJJEVxup3rBDxFmqY2BA0A6F29TzsEEq0c5V"><!-- /.box-body -->
                </form>

            </div>
            <!-- /.box-body -->
        </div>

        <script>

        </script>
    </div>
</div>