    <?php $siteSettings=\App\Site\Views\Helpers\SiteHelper::getSettings();?>
    <div class="g-footer">
        <div class="w1190">
         <div class="g-guide clrfix">
             <dl>
                 <dt>新手指南</dt>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/about" title="了解1元集资购">了解1元集资购</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/questiondetail" title="常见问题">常见问题</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/userexperience" title="会员福分经验值">会员福分经验值</a></dd>
             </dl>
             <dl>
                 <dt>集资购保障</dt>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/genuinetwo" title="1元集资购保障体系">1元集资购保障体系</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/securepayment" title="安全支付">安全支付</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/suggestion" title="投诉建议">投诉建议</a></dd>
             </dl>
             <dl>
                 <dt>商品配送</dt>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/deliveryfees" title="配送费用">配送费用</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/prodcheck" title="商品验货与签收">商品验货与签收</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/shiptwo" title="长时间未收到商品">长时间未收到商品</a></dd>
             </dl>
             <dl>
                 <dt>关于1元集资购</dt>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/about" title="1元集资购介绍">1元集资购介绍</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/fund" title="集资购公益">集资购公益</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/contactus" title="联系我们">联系我们</a></dd>
             </dl>
             <dl>
                 <dt>携手1元集资购</dt>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/business" title="商务合作">商务合作</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/referauth" title="邀请">邀请</a></dd>
                 <dd><a target="_blank" href="<?php echo $this->view->baseUrl?>yungou/help/qqgroup" title="官方QQ群交流">官方QQ群交流</a></dd>
             </dl>
         </div>

         <div class="g-service">
             <div class="m-ser u-ser1">
                 <ul>
                     <li><s class="u-icons"></s></li>
                     <li>
                         <dl>
                             <dt>下载手机客户端</dt>
                             <dd><b class="u-icons"></b></dd>
                             <dd><a target="_blank" href="javascript:;" title="立即下载">立即下载</a></dd>
                         </dl>
                     </li>
                 </ul>
             </div>
             <div class="m-ser u-ser2">
                 <ul>
                     <li><a href="javascript:;">
                         <img src="images/1yyg-wx.png" /></a></li>
                     <li>
                         <dl>
                             <dt><a target="_blank" href="javascript:;"><i class="u-icons"></i>关注官方微信</a></dt>
                             <dd><a target="_blank" href="javascript:;"><b class="u-icons"></b></a></dd>
                         </dl>
                     </li>
                 </ul>
             </div>
             <div class="m-ser u-ser3">
                 <ul>
                     <li><s class="u-icons"></s></li>
                     <li>
                         <dl>
                             <dt>服务器时间</dt>
                             <dd id="pServerTime">
                                 <span>00</span>
                                 <em>:</em>
                                 <span>00</span>
                                 <em>:</em>
                                 <span>00</span>
                             </dd>
                         </dl>
                     </li>
                 </ul>
             </div>
             <div class="m-ser u-ser4">
                 <ul>
                     <li><s class="u-icons"></s></li>
                     <li>
                         <dl>
                             <dt>集资购公益基金</dt>
                             <dd><a target="_blank" href="javascript:;" id="spFundTotal">￥0000000.00</a></dd>
                         </dl>
                     </li>
                 </ul>
             </div>
             <div class="m-ser u-ser5">
                 <ul>
                     <li><s class="u-icons"></s></li>
                     <li>
                         <dl>
                             <dt>服务热线</dt>
                             <dd class="orange u-tel"><?php echo $siteSettings['tel400']?></dd>
                             <dd><a id="btnBtmQQ" href="javascript:;" class="u-service-off u-service"><i></i>在线客服</a></dd>
                         </dl>
                     </li>
                 </ul>
             </div>
         </div>

         <div class="g-special clrfix">
             <ul>
                 <li>
                     <a href="<?php echo $this->view->baseUrl?>yungou/help/genuinetwo" target="_blank" title="100%公平公正">
                        <em class="u-spc-icon1"></em>
                        <span>100%公平公正</span>
                        参与过程公开透明，用户可随时查看
                     </a>
                 </li>
                 <li>
                     <a href="<?php echo $this->view->baseUrl?>yungou/help/genuine" target="_blank" title="100%正品保证">
                        <em class="u-spc-icon2"></em>
                        <span>100%正品保证</span>
                        精心挑选优质商家，100%品牌正品
                     </a>
                 </li>
                 <li>
                     <a href="<?php echo $this->view->baseUrl?>yungou/help/deliveryfees" target="_blank" title="全国免运费">
                        <em class="u-spc-icon3"></em>
                        <span>全国免运费</span>
                        全场商品全国包邮（港澳台地区除外）
                     </a>
                 </li>
             </ul>
         </div>
        </div>
    </div>
    <script type="text/javascript" src="/dist/js/servertime.js"></script>