<li class="dropdown user user-menu">
	<!-- Menu Toggle Button -->
	<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
		<!-- The user image in the navbar-->		
		<img src="<?php echo empty($_SESSION['admin_user_info']['headimgurl']) ? $this->view->adminConfig->admin->default_avatar : $this->view->baseUrl . "service/file/index?upload_path=systemuser&id={$_SESSION['admin_user_info']['headimgurl']}&w=50&h=50"; ?>" class="user-image" alt="User Image">
		<!-- hidden-xs hides the username on small devices so only the image appears. -->
		<span class="hidden-xs"><?php echo $_SESSION['admin_name'] ?></span>
	</a>
	<ul class="dropdown-menu">
		<!-- The user image in the menu -->
		<li class="user-header">
			<img src="<?php echo empty($_SESSION['admin_user_info']['headimgurl']) ? $this->view->adminConfig->admin->default_avatar : $this->view->baseUrl . "service/file/index?upload_path=systemuser&id={$_SESSION['admin_user_info']['headimgurl']}&w=50&h=50"; ?>" class="img-circle" alt="User Image">
			<p>
				<?php echo $_SESSION['admin_name'] ?>

				<small> 上次登录时间: <?php echo $_SESSION['admin_user_info']['lasttime'] ?></small>
			</p>
		</li>
		<li class="user-footer">
			<div class="pull-left">
				<a href="<?php echo $this->view->baseUrl . 'admin/system/user/edit?id=' . $_SESSION['admin_id'] ?>" class="btn btn-default btn-flat">设置</a>
			</div>
			<div class="pull-right">
				<a href="<?php echo $this->view->baseUrl . 'admin/index/logout' ?>" class="btn btn-default btn-flat">登出</a>
			</div>
		</li>
	</ul>
</li>