<?php if (empty($this->view->__SHOWBYIFRAME__)) { ?>
  <!DOCTYPE html>
  <html>
  <?php
  if (!$this->request->isAjax() || $this->request->isGet()) {
    $this->view->csrf_token = createRandCode(40);
    $_SESSION['csrf_token'] = $this->view->csrf_token;
  }
  ?>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="<?php echo $this->view->csrf_token ?>">

    <title><?php echo  $this->view->adminConfig->admin->title ?> | <?php echo  $this->view->formName ?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <?php $this->partial("partials/styles") ?>

  </head>

  <body class="hold-transition <?php echo  $this->view->adminConfig->admin->skin ?> <?php echo  $this->view->adminConfig->admin->layout ?>">
    <noscript>
      <div style=" position:absolute; z-index:100000; height:2046px;top:0px;left:0px; width:100%; background:white; text-align:center;">
        <h3>您所用的浏览器未启用脚本，系统无法正常工作！</h3>
      </div>
    </noscript>
    <?php if ($this->view->adminConfig->admin->top_alert) { ?>
      <div style="text-align: center;min-height: 50px;font-size: 12px;background-color: #ffffd5;color: #ff0000;">
        <?php echo  $this->view->adminConfig->admin->top_alert ?>
      </div>
    <?php } ?>

    <div class="wrapper">

      <?php $this->partial("partials/header") ?>

      <!-- Left side column. contains the logo and sidebar -->
      <?php $this->partial("partials/sidebar") ?>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" id="pjax-container" style="min-height: 421px;padding-top: 0px;">
        <?php if ($this->view->adminConfig->admin->is_tab_iframe_used) { ?>
          <!--bootstrap tab风格 多标签页-->
          <div class="content-tabs">
            <button class="roll-nav roll-left tabLeft" onclick="scrollTabLeft()">
              <i class="fa fa-backward"></i>
            </button>
            <nav class="page-tabs menuTabs tab-ui-menu" id="tab-menu">
              <div class="page-tabs-content" style="margin-left: 0px;">

              </div>
            </nav>
            <button class="roll-nav roll-right tabRight" onclick="scrollTabRight()">
              <i class="fa fa-forward" style="margin-left: 3px;"></i>
            </button>
            <div class="btn-group roll-nav roll-right">
              <button class="dropdown tabClose" data-toggle="dropdown">
                页签操作<i class="fa fa-caret-down" style="padding-left: 3px;"></i>
              </button>
              <ul class="dropdown-menu dropdown-menu-right" style="min-width: 128px;">
                <li><a class="tabReload" href="javascript:refreshTab();">刷新当前</a></li>
                <li><a class="tabCloseCurrent" href="javascript:closeCurrentTab();">关闭当前</a></li>
                <li><a class="tabCloseAll" href="javascript:closeOtherTabs(true);">全部关闭</a></li>
                <li><a class="tabCloseOther" href="javascript:closeOtherTabs();">除此之外全部关闭</a></li>
              </ul>
            </div>
            <button class="roll-nav roll-right fullscreen" onclick="AppIframe.handleFullScreen()">
              <i class="fa fa-arrows-alt"></i>
            </button>
          </div>
          <div class="content-iframe " style="background-color: #ffffff; ">
            <div class="tab-content " id="tab-content">

            </div>
          </div>
        <?php } else { ?>
          <div id="app">
            <!-- Content Header (Page header) -->
            <section class="content-header">
              <?php //$this->partial("partials/container/page/page_container/page_header/page_title") 
              ?>
              <?php $this->partial("partials/container/page/page_container/page_header/breadcrumb") ?>
            </section>

            <!-- Main content -->
            <section class="content">
              <div id="app-admin-alerts-errs"></div>
              <!-- @include('admin::partials.alerts')
                    @include('admin::partials.exception')
                    @include('admin::partials.toastr') -->
              <div style="display: block;" id="app-admin-controllers-modal"></div>
              <?php echo $this->getContent(); ?>
            </section>
            <!-- /.content -->
          </div>
        <?php } ?>
      </div>
    </div>
    <!-- /.content-wrapper -->
    <?php $this->partial("partials/footer") ?>

    <!-- Control Sidebar -->
    <?php //$this->partial("partials/container/control_sidebar") 
    ?>
    <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <button id="totop" title="Go to top" style="display: none;"><i class="fa fa-chevron-up"></i></button>

    <?php $this->partial("partials/js") ?>

    <script>
      function keepLogin() {
        LA.sessionImage.src = '<?php echo $this->view->baseUrl ?>admin/index/keeplogin?_=' + Math.random()
      }

      $(function() {
        setInterval(keepLogin, 1000 * 60 * 5);
      })
    </script>

    <?php if ($this->view->adminConfig->admin->is_tab_iframe_used) { ?>
      <script type="text/javascript">
        $(function() {
          // console.log(window.location);
          // AppIframe.setbasePath("../");
          // AppIframe.setGlobalImgPath("dist/img/");
          addTabs({
            id: "index",
            title: "首页",
            url: "/admin/index/index",
            targetType: "iframe-tab",
            icon: "fa fa-circle-o",
            close: false,
            urlType: 'abosulte' //relative
          });
          AppIframe.fixIframeCotent();
        });
      </script>
    <?php } ?>

  </body>

  </html>

<?php } else { ?>
  <?php $this->partial("indexinframe") ?>
<?php } ?>