<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/Ionicons/css/ionicons.min.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/jvectormap/jquery-jvectormap.css">
  <!-- daterange picker -->
  <!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-daterangepicker/daterangepicker.css">-->
  <!-- bootstrap datepicker -->
  <!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">-->
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/iCheck/all.css">
  <!-- Bootstrap Color Picker -->
  <!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">-->
  <!-- Bootstrap time Picker -->
  <!-- <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/timepicker/bootstrap-timepicker.min.css">-->
  <!-- Select2 -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/select2/dist/css/select2.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/AdminLTE.min.css">

  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/_all-skins.min.css">
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.css">
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/css/fileinput.min.css?v=4.5.2">
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.css">
  <link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.css">
  <!-- 
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.css">
 -->
  <!-- 
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">

 -->
  <!--
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/select2/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.skinNice.css">
 -->
  <!-- 
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/fontawesome-iconpicker/dist/css/fontawesome-iconpicker.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-duallistbox/dist/bootstrap-duallistbox.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>dist/css/skins/skin-blue.min.css">
<link rel="stylesheet" href="<?php echo $this->view->resourceUrl ?>bootstrap/css/bootstrap.min.css">

<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/nprogress/nprogress.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/nestable/nestable.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/toastr/build/toastr.min.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap3-editable/css/bootstrap-editable.css">
<link rel="stylesheet" href="http://qhdemo.jdytoy.com/vendor/laravel-admin/google-fonts/fonts.css">
-->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style>
    .form-group>label.asterisk:before {
      content: " *";
      color: red;
    }

    .fa-refresh:before {
      content: "\f021";
    }
  </style>
</head>

<body class="hold-transition <?php echo  $this->view->adminConfig->admin->skin ?> <?php echo  $this->view->adminConfig->admin->layout ?>">
  <div class="wrapper">

    <?php $this->partial("partials/header") ?>

    <!-- Left side column. contains the logo and sidebar -->
    <?php $this->partial("partials/sidebar") ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <?php //$this->partial("partials/container/page/page_container/page_header/page_title") 
        ?>
        <?php $this->partial("partials/container/page/page_container/page_header/breadcrumb") ?>
      </section>

      <!-- Main content -->
      <section class="content">
        <!-- @include('admin::partials.alerts')
        @include('admin::partials.exception')
        @include('admin::partials.toastr') -->
        <?php echo $this->getContent(); ?>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php $this->partial("partials/footer") ?>

    <!-- Control Sidebar -->
    <?php //$this->partial("partials/container/control_sidebar") 
    ?>
    <!-- /.control-sidebar -->

  </div>
  <!-- ./wrapper -->
  <button id="totop" title="Go to top" style="display: none;"><i class="fa fa-chevron-up"></i></button>

  <!-- jQuery 3 -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery/dist/jquery.min.js"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- Select2 -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- InputMask -->
  <script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.extensions.js"></script>
  <!-- date-range-picker -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/moment/min/moment.min.js"></script>

  <!-- <script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>-->
  <!-- bootstrap datepicker -->
  <!-- <script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>-->
  <!-- bootstrap color picker -->
  <!-- <script src="<?php echo $this->view->resourceUrl ?>bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>-->
  <!-- bootstrap time picker -->
  <!-- <script src="<?php echo $this->view->resourceUrl ?>plugins/timepicker/bootstrap-timepicker.min.js"></script>-->
  <!-- SlimScroll -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- DataTables -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <!-- iCheck 1.0.1 -->
  <script src="<?php echo $this->view->resourceUrl ?>plugins/iCheck/icheck.min.js"></script>
  <!-- FastClick -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE App -->
  <script src="<?php echo $this->view->resourceUrl ?>dist/js/adminlte.min.js"></script>
  <!-- Sparkline -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
  <!-- jvectormap  -->
  <script src="<?php echo $this->view->resourceUrl ?>plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
  <!-- ChartJS -->
  <script src="<?php echo $this->view->resourceUrl ?>bower_components/chart.js/Chart.js"></script>

  <script src="<?php echo $this->view->resourceUrl ?>../eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../toastr/build/toastr.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../number-input/bootstrap-number-input.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../jquery-validation/jquery.validate.min.js"></script>

  <script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/canvas-to-blob.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/fileinput.min.js?v=4.5.2"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../bootstrap-fileinput/js/plugins/sortable.min.js?v=4.5.2"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../sweetalert2/dist/sweetalert2.min.js"></script>
  <script src="<?php echo $this->view->resourceUrl ?>../laravel-admin/laravel-admin.js"></script>
  <!-- ckeditor start -->
  <script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ckeditor/ckeditor.js"></script>
  <!-- ckeditor end -->

  <!-- ueditor start -->
  <script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/third-party/zeroclipboard/ZeroClipboard.js"></script>
  <script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.config.js"></script>
  <script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/ueditor.all.min.js"> </script>
  <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
  <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
  <script type="text/javascript" charset="utf-8" src="<?php echo $this->view->commonResourceUrl ?>ueditor/lang/zh-cn/zh-cn.js"></script>
  <!-- ueditor end -->

  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <!-- <script src="<?php echo $this->view->resourceUrl ?>dist/js/pages/dashboard2.js"></script> -->
  <!-- AdminLTE for demo purposes -->
  <!-- <script src="<?php echo $this->view->resourceUrl ?>dist/js/demo.js"></script>-->

  <!-- REQUIRED JS SCRIPTS -->
  <!-- 
<script src="<?php echo $this->view->resourceUrl ?>dist/js/app.min.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/jquery-pjax/jquery.pjax.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/nprogress/nprogress.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/nestable/jquery.nestable.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap3-editable/js/bootstrap-editable.min.js"></script>


 -->
  <!-- 
<script src="<?php echo $this->view->resourceUrl ?>plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
<script src="<?php echo $this->view->resourceUrl ?>plugins/input-mask/jquery.inputmask.bundle.min.js"></script>
 -->
  <!-- 
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/moment/min/moment-with-locales.min.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

 -->
  <!-- 
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/number-input/bootstrap-number-input.js"></script>
 -->
  <!-- 
<script src="<?php echo $this->view->resourceUrl ?>plugins/ionslider/ion.rangeSlider.min.js"></script>
-->
  <!-- 
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/fontawesome-iconpicker/dist/js/fontawesome-iconpicker.min.js"></script>

<script src="http://qhdemo.jdytoy.com/vendor/laravel-admin/bootstrap-duallistbox/dist/jquery.bootstrap-duallistbox.min.js"></script>
 -->
  <!-- page script -->
  <?php $this->partial("partials/js/app") ?>

  <script>
    $(function() {

      if (typeof App == 'object') {
        App.init();
      }
      //FormValidation.init();
      if (typeof FormComponents == 'object') {
        FormComponents.init();
      }
      if (typeof Search == 'object') {
        Search.init();
      }
      if (typeof List == 'object') {
        List.init();
      }
    })
  </script>
  <?php $this->partial("partials/toastr") ?>
</body>

</html>