<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <?php $this->partial("partials/styles") ?>
  
</head>

<body class="hold-transition <?php echo  $this->view->adminConfig->admin->skin ?> <?php echo  $this->view->adminConfig->admin->layout ?>">
  <div class="wrapper">

    <?php $this->partial("partials/header") ?>

    <!-- Left side column. contains the logo and sidebar -->
    <?php $this->partial("partials/sidebar") ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <?php //$this->partial("partials/container/page/page_container/page_header/page_title") 
        ?>
        <?php $this->partial("partials/container/page/page_container/page_header/breadcrumb") ?>
      </section>

      <!-- Main content -->
      <section class="content">
        <!-- @include('admin::partials.alerts')
        @include('admin::partials.exception')
        @include('admin::partials.toastr') -->
        <?php echo $this->getContent(); ?>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php $this->partial("partials/footer") ?>

    <!-- Control Sidebar -->
    <?php //$this->partial("partials/container/control_sidebar") 
    ?>
    <!-- /.control-sidebar -->

  </div>
  <!-- ./wrapper -->
  <button id="totop" title="Go to top" style="display: none;"><i class="fa fa-chevron-up"></i></button>

  <?php $this->partial("partials/js") ?>
</body>

</html>