<?php
function lang($lang_key, $force = true)
{
    $di = \Phalcon\DI::getDefault();
    $install_config = $di->get('install_config');
    $lang = isset($install_config['lang']) ? $install_config['lang'] : array();
    return isset($lang[$lang_key]) ? $lang[$lang_key] : ($force ? $lang_key : '');
}
?>
				<div class="row-fluid">

					<div class="span12">

						<div class="portlet box blue" id="form_wizard_1">

							<div class="portlet-title">

								<div class="caption">

									<i class="icon-reorder"></i> <span class="step-title">Step 1 of 4</span>

								</div>

								<div class="tools hidden-phone">

									<a href="javascript:;" class="collapse"></a>

									<a href="#portlet-config" data-toggle="modal" class="config"></a>

									<a href="javascript:;" class="reload"></a>

									<a href="javascript:;" class="remove"></a>

								</div>

							</div>

							<div class="portlet-body form">

								<form action="#" class="form-horizontal" id="submit_form">

									<div class="form-wizard">

										<div class="navbar steps">

											<div class="navbar-inner">

												<ul class="row-fluid">

													<li class="span3">

														<a href="#tab1" data-toggle="tab" class="step active">

														<span class="number">1</span>

														<span class="desc"><i class="icon-ok"></i> 检查安装环境</span>   

														</a>

													</li>

													<li class="span3">

														<a href="#tab2" data-toggle="tab" class="step">

														<span class="number">2</span>

														<span class="desc"><i class="icon-ok"></i> 设置运行环境</span>   

														</a>

													</li>

													<li class="span3">

														<a href="#tab3" data-toggle="tab" class="step">

														<span class="number">3</span>

														<span class="desc"><i class="icon-ok"></i> 创建数据库</span>   

														</a>

													</li>

													<li class="span3">

														<a href="#tab4" data-toggle="tab" class="step">

														<span class="number">4</span>

														<span class="desc"><i class="icon-ok"></i> 确认安装</span>   

														</a> 

													</li>

												</ul>

											</div>

										</div>

										<div id="bar" class="progress progress-success progress-striped">

											<div class="bar"></div>

										</div>

										<div class="tab-content">

											<div class="alert alert-error hide">

												<button class="close" data-dismiss="alert"></button>

												You have some form errors. Please check below.

											</div>

											<div class="alert alert-success hide">

												<button class="close" data-dismiss="alert"></button>

												Your form validation is successful!

											</div>

											<div class="tab-pane active" id="tab1">
											
												<h3 class="block">环境检查</h3>
												
												<table class="table table-hover">
													
                									<thead>
                
                										<tr>
                
                											<th>项目</th>
                
                											<th>当前服务器</th>
                
                											<th>所需配置</th>
                
                											<th class="hidden-480">最佳</th>
                
                											<th>Status</th>
                
                										</tr>
                
                									</thead>
                
                									<tbody>
                										<?php foreach ($this->view->env_items as $key => $item) {?>
                										<tr>
                
                											<td><?php echo lang($key)?></td>
                
                											<td><?php echo $item['current']?></td>
                
                											<td><?php echo lang($item['r'])?></td>
                
                											<td class="hidden-480"><?php echo lang($item['b'])?></td>
                
                											<td><span class="label label-success"><?php echo $item['check_status']?></span></td>
                
                										</tr>
                										<?php }?>                
                									</tbody>
                
                								</table>

											</div>
											
											<div class="tab-pane active" id="tab2">
											
												<h3 class="block">数据库脚本检查</h3>
												
												<table class="table table-hover">
													
                									<thead>
                
                										<tr>
                
                											<th>脚本文件</th>
                
                
                											<!--<th>当前状态</th>-->
                
                										</tr>
                
                									</thead>
                
                									<tbody>
                										<?php foreach ($this->view->dirfile_items as $key => $item) {?>
                										<tr>
                
                											<td><?php echo $item['file']?></td>
                
                
                											<!--<td><span class="label label-success"><?php echo $item['status'] == 1 ? lang('writeable') : ($item['status'] == -1 ? lang('nodir') : lang('unwriteable'))?></span></td>-->
                
                										</tr>
                										<?php }?>                
                									</tbody>
                
                								</table>

											</div>
											
											<div class="tab-pane active" id="tab3">
											
												<h3 class="block">填写数据库信息</h3>
																
												<div class="control-group">

													<label class="control-label">数据库服务器地址<span class="required">*</span></label>

													<div class="controls">

														<input type="text" class="span6 m-wrap" name="dbhost" value="<?php echo $this->view->dbhost?>" />

														<span class="help-inline"></span>

													</div>

												</div>
												
												<div class="control-group">

													<label class="control-label">数据库名<span class="required">*</span></label>

													<div class="controls">

														<input type="text" class="span6 m-wrap" name="dbname" value="<?php echo $this->view->dbname?>" />

														<span class="help-inline"></span>

													</div>

												</div>
												
												<div class="control-group">

													<label class="control-label">数据库用户名<span class="required">*</span></label>

													<div class="controls">

														<input type="text" class="span6 m-wrap" name="username" value="<?php echo $this->view->dbuser?>" />

														<span class="help-inline"></span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">数据库密码<span class="required">*</span></label>

													<div class="controls">

														<input type="password" class="span6 m-wrap" name="password" id="submit_form_password" value="<?php echo $this->view->dbpw?>" />

														<span class="help-inline"></span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">确认密码<span class="required">*</span></label>

													<div class="controls">

														<input type="password" class="span6 m-wrap" name="rpassword" value="<?php echo $this->view->dbpw?>" />

														<span class="help-inline"></span>

													</div>

												</div>

											</div>

											<div class="tab-pane" id="tab4">

												<h3 class="inbox-loading">安装中...</h3>
																								
												<h4 class="form-section">确认数据库设置</h4>
												
												<div class="control-group">

													<label class="control-label">数据库服务器地址:</label>

													<div class="controls">

														<span class="text display-value" data-display="dbhost"></span>

													</div>

												</div>
												
												<div class="control-group">

													<label class="control-label">数据库名:</label>

													<div class="controls">

														<span class="text display-value" data-display="dbname"></span>

													</div>

												</div>
												
												<div class="control-group">

													<label class="control-label">数据库用户名:</label>

													<div class="controls">

														<span class="text display-value" data-display="username"></span>

													</div>

												</div>
												
												<div class="control-group">

													<label class="control-label">数据库密码:</label>

													<div class="controls">

														<span class="text display-value" data-display="password"></span>

													</div>

												</div>
												
											</div>

										</div>

										<div class="form-actions clearfix">

											<a href="javascript:;" class="btn button-previous">

											<i class="m-icon-swapleft"></i> Back 

											</a>

											<a href="javascript:;" class="btn blue button-next">

											Continue <i class="m-icon-swapright m-icon-white"></i>

											</a>

											<a href="javascript:;" class="btn green button-submit">

											Submit <i class="m-icon-swapright m-icon-white"></i>

											</a>

										</div>

									</div>

								</form>

							</div>

						</div>

					</div>

				</div>
				
<script>
var FormWizard = function () {


    return {
        //main function to initiate the module
        init: function () {
            if (!jQuery().bootstrapWizard) {
                return;
            }

            function format(state) {
                if (!state.id) return state.text; // optgroup
                return "<img class='flag' src='assets/img/flags/" + state.id.toLowerCase() + ".png'/>&nbsp;&nbsp;" + state.text;
            }

            $("#country_list").select2({
                placeholder: "Select",
                allowClear: true,
                formatResult: format,
                formatSelection: format,
                escapeMarkup: function (m) {
                    return m;
                }
            });

            var form = $('#submit_form');
            var error = $('.alert-error', form);
            var success = $('.alert-success', form);
			var loading = $('.inbox-loading', form);
			loading.hide();
			
            form.validate({
                doNotHideMessage: true, //this option enables to show the error/success messages on tab switch.
                errorElement: 'span', //default input error message container
                errorClass: 'validate-inline', // default input error message class
                focusInvalid: false, // do not focus the last invalid input
                rules: {
                    //database
                    dbhost: {
                        minlength: 5,
                        required: true
                    },
                    dbname: {
                        minlength: 3,
                        required: true
                    },
                    username: {
                        minlength: 3,
                        required: true
                    },
                    password: {
                        minlength: 5,
                        required: true
                    },
                    rpassword: {
                        minlength: 5,
                        required: true,
                        equalTo: "#submit_form_password"
                    }
                },

                messages: { // custom messages for radio buttons and checkboxes
                    'payment[]': {
                        required: "Please select at least one option",
                        minlength: jQuery.format("Please select at least one option")
                    }
                },

                errorPlacement: function (error, element) { // render error placement for each input type
                    if (element.attr("name") == "gender") { // for uniform radio buttons, insert the after the given container
                        error.addClass("no-left-padding").insertAfter("#form_gender_error");
                    } else if (element.attr("name") == "payment[]") { // for uniform radio buttons, insert the after the given container
                        error.addClass("no-left-padding").insertAfter("#form_payment_error");
                    } else {
                        error.insertAfter(element); // for other inputs, just perform default behavoir
                    }
                },

                invalidHandler: function (event, validator) { //display error alert on form submit   
                    success.hide();
                    error.show();
                    App.scrollTo(error, -200);
                },

                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.help-inline').removeClass('ok'); // display OK icon
                    $(element)
                        .closest('.control-group').removeClass('success').addClass('error'); // set error class to the control group
                },

                unhighlight: function (element) { // revert the change dony by hightlight
                    $(element)
                        .closest('.control-group').removeClass('error'); // set error class to the control group
                },

                success: function (label) {
                    if (label.attr("for") == "gender" || label.attr("for") == "payment[]") { // for checkboxes and radip buttons, no need to show OK icon
                        label
                            .closest('.control-group').removeClass('error').addClass('success');
                        label.remove(); // remove error label here
                    } else { // display success icon for other inputs
                        label
                            .addClass('valid ok') // mark the current input as valid and display OK icon
                        .closest('.control-group').removeClass('error').addClass('success'); // set success class to the control group
                    }
                },

                submitHandler: function (form) {
                    success.show();
                    error.hide();
                    //add here some ajax code to submit your form or just call form.submit() if you want to submit the form without ajax
                }

            });

            var displayConfirm = function() {
                $('.display-value', form).each(function(){
                    var input = $('[name="'+$(this).attr("data-display")+'"]', form);
                    if (input.is(":text") || input.is("textarea")) {
                        $(this).html(input.val());
                    } else if (input.is("select")) {
                        $(this).html(input.find('option:selected').text());
                    } else if (input.is(":radio") && input.is(":checked")) {
                        $(this).html(input.attr("data-title"));
                    } else if ($(this).attr("data-display") == 'card_expiry') {
                        $(this).html($('[name="card_expiry_mm"]', form).val() + '/' + $('[name="card_expiry_yyyy"]', form).val());
                    } else if ($(this).attr("data-display") == 'payment') {
                        var payment = [];
                        $('[name="payment[]"]').each(function(){
                            payment.push($(this).attr('data-title'));
                        });
                        $(this).html(payment.join("<br>"));
                    }
                });
            }

            var buildEnv = function () {
				
				var dbhost = $('[name="dbhost"]').val();
            	var dbname = $('[name="dbname"]').val();
				var dbuser = $('[name="username"]').val();
				var dbpw = $('[name="password"]').val();
				
            	var data = {
					dbhost:dbhost,
					dbname:dbname,
					dbuser:dbuser,
					dbpw:dbpw,
				};
				                
                loading.show();
				
				$.ajax({
					url: '/install/index/build',
					type:'POST',
					data: data,
					success: function(res){
						//console.log(res);
						//{"success":false,"error_code":-1,"error_msg":"\u6570\u636e\u5e93\u670d\u52a1\u5668\u5730\u5740\u4e3a\u7a7a","errorCode":-1,"errorMsg":"\u6570\u636e\u5e93\u670d\u52a1\u5668\u5730\u5740\u4e3a\u7a7a"}
						if(!res.success){
							alert(res.error_msg);
						}else{
							window.location.href = "/admin/index/login"
						}
					},
					error: function(res){
						//alert(res);
						console.error(res);
					},
					complete: function(res){
						loading.hide();
						App.fixContentHeight();
						App.initUniform();
					},
					dataType: 'json'
				});
            }
            
            // default form wizard
            $('#form_wizard_1').bootstrapWizard({
                'nextSelector': '.button-next',
                'previousSelector': '.button-previous',
                onTabClick: function (tab, navigation, index) {
                    alert('on tab click disabled');
                    return false;
                },
                onNext: function (tab, navigation, index) {
                    success.hide();
                    error.hide();

                    if (form.valid() == false) {
                        return false;
                    }

                    var total = navigation.find('li').length;
                    var current = index + 1;
                    // set wizard title
                    $('.step-title', $('#form_wizard_1')).text('Step ' + (index + 1) + ' of ' + total);
                    // set done steps
                    jQuery('li', $('#form_wizard_1')).removeClass("done");
                    var li_list = navigation.find('li');
                    for (var i = 0; i < index; i++) {
                        jQuery(li_list[i]).addClass("done");
                    }

                    if (current == 1) {
                        $('#form_wizard_1').find('.button-previous').hide();
                    } else {
                        $('#form_wizard_1').find('.button-previous').show();
                    }

                    if (current >= total) {
                        $('#form_wizard_1').find('.button-next').hide();
                        $('#form_wizard_1').find('.button-submit').show();
                        displayConfirm();
                    } else {
                        $('#form_wizard_1').find('.button-next').show();
                        $('#form_wizard_1').find('.button-submit').hide();
                    }
                    App.scrollTo($('.page-title'));
                },
                onPrevious: function (tab, navigation, index) {
                    success.hide();
                    error.hide();

                    var total = navigation.find('li').length;
                    var current = index + 1;
                    // set wizard title
                    $('.step-title', $('#form_wizard_1')).text('Step ' + (index + 1) + ' of ' + total);
                    // set done steps
                    jQuery('li', $('#form_wizard_1')).removeClass("done");
                    var li_list = navigation.find('li');
                    for (var i = 0; i < index; i++) {
                        jQuery(li_list[i]).addClass("done");
                    }

                    if (current == 1) {
                        $('#form_wizard_1').find('.button-previous').hide();
                    } else {
                        $('#form_wizard_1').find('.button-previous').show();
                    }

                    if (current >= total) {
                        $('#form_wizard_1').find('.button-next').hide();
                        $('#form_wizard_1').find('.button-submit').show();
                    } else {
                        $('#form_wizard_1').find('.button-next').show();
                        $('#form_wizard_1').find('.button-submit').hide();
                    }

                    App.scrollTo($('.page-title'));
                },
                onTabShow: function (tab, navigation, index) {
                    var total = navigation.find('li').length;
                    var current = index + 1;
                    var $percent = (current / total) * 100;
                    $('#form_wizard_1').find('.bar').css({
                        width: $percent + '%'
                    });
                }
            });

            $('#form_wizard_1').find('.button-previous').hide();
            $('#form_wizard_1 .button-submit').click(function () {
                buildEnv();
            }).hide();
        }

    };

}();
</script>