<?php $siteSettings=\Webcms\Site\Helpers\SiteHelper::getSettings();?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $siteSettings['title']?></title>
    <base href="<?php echo $this->view->resourceUrl?>" />
    <link rel="stylesheet" type="text/css" href="css/header.css" />
    <script type="text/javascript">
        function removejscssfile(filename){
            function indexOfFun(con) {
                return window.location.href.indexOf(con)!=-1
            };
            if( indexOfFun("/group/news")||indexOfFun("/historybuyrecords")||indexOfFun("/newestbuyrecords") ){}else return;
            var targetelement = "link"; //判断文件类型 
            var targetattr = "href"; //判断文件名 
            var allsuspects=document.getElementsByTagName(targetelement); 
            //遍历元素， 并删除匹配的元素 
            for (var i=allsuspects.length; i>=0; i--){ 
                if (allsuspects[i] && allsuspects[i].getAttribute(targetattr)!=null && allsuspects[i].getAttribute(targetattr).indexOf(filename)!=-1) allsuspects[i].parentNode.removeChild(allsuspects[i]); 
            } 
        }
        removejscssfile("css/header.css"); 
    </script>
    <link rel="stylesheet" type="text/css" href="/CSS/pagination.css" />
</head>
<body>
<div class="wrapper">
    <!--顶部-->
    <?php $this->partial("partials/header") ?>
	
	<?php echo $this->getContent(); ?>	

    <!--版权-->
    <?php $this->partial("partials/footer") ?>
</div>




<!-- 弹层开始 -->
<link rel="stylesheet" type="text/css" href="/CSS/pageDialog.css" /> 
<div class="pageDialogBG" id="pageDialogBG"></div>
<!-- <div class="pageDialogBorder" id="pageDialogBorder"></div> -->
<div class="pageDialog" id="pageDialog">
    <div class="pageDialogClose" id="pageDialogClose" title="关闭"></div>
    <div class="pageDialogMain" id="pageDialogMain">
        <div class="content"></div>
    </div>
</div>

</body>
</html>




