<?php $siteSettings=\App\Site\Helpers\SiteHelper::getSettings();?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>微信扫码支付</title>
    <base href="<?php echo $this->view->resourceUrl?>" />
    <link rel="stylesheet" type="text/css" href="css/Comm.css" />
    <link rel="stylesheet" type="text/css" href="css/WeixinPay.css" />
</head>
<body>
    <div class="wx_header">
        <div class="wx_logo">
            <img title="微信支付" alt="微信支付标志" src="images/wxlogo_pay.png?v=1" />
        </div>
    </div>
    <div class="weixin">
        <div class="weixin2">
            <b class="wx_box_corner left pngFix"></b><b class="wx_box_corner right pngFix"></b>
            <div class="wx_box pngFix">
                <div class="wx_box_area">
                    <div class="pay_box qr_default">
                        <div class="area_bd">
                            <span class="wx_img_wrapper" id="qr_box">
                                <img id="payQRImg" class="qrcode" src="<?php echo $this->view->baseUrl?>service/qrcode/create?url=<?php echo urlencode($this->view->orderPayInfo['memo']['code_url'])?>" alt="二维码" style="border-width:0px;" />
                                <img style="left: 50%; opacity: 0; display: none; margin-left: -101px;" class="guide pngFix" src="images/wxwebpay_guide.png" alt="" id="guide" />
                            </span>
                            <div class="msg_default_box"><i class="icon_wx pngFix"></i>
                                <p>
                                    请使用微信<br />
                                    扫一扫完成支付
                                </p>
                            </div>
                            <div class="msg_box"><i class="icon_wx pngFix"></i>
                                <p><strong>扫描成功</strong>请在手机确认支付</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wx_hd">
                    <div class="wx_hd_img icon_wx"></div>
                </div>
                <div class="wx_money"><span>￥</span><?php echo empty($this->view->orderPayInfo['pay_amount'])?0.00:showPrice($this->view->orderPayInfo['pay_amount'],2)?></div>
                <!--支付订单号-->
                <div class="wx_pay">
                    <p><span class="wx_left">支付订单号</span><span class="wx_right"><?php echo $this->view->orderPayInfo['_id']?></span></p>
                </div>
                <div class="wx_kf">
                    <div class="wx_kf_img icon_wx"></div>
                    <div class="wx_kf_wz">
                        <p>客服</p>
                        <p><?php echo $siteSettings['tel400']?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--版权-->
    <?php $this->partial("partials/footer") ?>
    <script type="text/javascript" src="/dist/js/common.js"></script>
    <script type="text/javascript" src="/dist/js/cart.js"></script>
</body>
</html>
