<link rel="stylesheet" type="text/css" href="css/LotteryDetail.css" />
<input type="hidden" id="pageID" value="lotteryDetail">
<div class="ng-wrap">
    <div id="ng_pt_line" class="ng-pt-line"></div>
    <div id="divMain" class="ng-main-wrapper">
        <?php $this->partial("partials/period_list") ?>
        
        <!--商品揭晓-->
        <div id="div_ngresult" class="ng-result-wrapper clearfix  ">
            <!--图片展示-->
            <div class="ng-result-img">
                <div class="result-img-wrapper">
                        <a href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $this->view->goodsInfo['goods_commonid']?>" title="<?php echo $this->view->goodsInfo['name']?>"><img width="242" height="242" alt="<?php echo $this->view->goodsInfo['name']?>" src="<?php echo \App\Goods\Helpers\GoodsHelper::getGoodsImage($this->view->baseUrl, $this->view->goodsInfo['image'],242,242)?>"></a>
                </div>
                <a href="<?php echo $this->view->baseUrl?>yungou/product/index?id=<?php echo $this->view->goodsInfo['goods_commonid']?>" class="result-more">查看商品详情</a>
            </div>
            <!--揭晓结果-->
            <div class="ng-result-detail">
                <div class="result-con-wrapper">
                    <h2 class="title"><span class="num">(第<?php echo $this->view->goodsInfo['period']?>云)</span><?php echo $this->view->goodsInfo['name']?></h2>
                    <p class="price">
                        价值：￥<?php echo showPrice($this->view->goodsInfo['price'],2)?>
                    </p>
                    
                    <div class="result-main">
                        <div class="result-con-info">
                            <p class="r-name">
                                <span><a href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->goodsInfo['prize_buyer_id']?>" target="_blank" title="<?php echo getBuyerName($this->view->goodsInfo['prize_buyer_name'],$this->view->goodsInfo['prize_buyer_register_by'])?>"><?php echo getBuyerName($this->view->goodsInfo['prize_buyer_name'],$this->view->goodsInfo['prize_buyer_register_by'])?></a></span>(<em><?php echo convertIp($this->view->goodsInfo['prize_buyer_ip'])?></em>)
                            </p>
                            <p>本云参与：<span class="r-num"><?php echo count(explode(',', $this->view->goodsInfo['prize_buyer_lottery_code']))?></span>人次<a id="a_luckynum" href="javascript:;" class="r-look">点击查看</a></p>
                            <p>揭晓时间：<span><?php echo getMilliTime4Show($this->view->goodsInfo['prize_time'])?></span></p>
                            <p>云购时间：<span><?php echo getMilliTime4Show($this->view->goodsInfo['prize_buyer_purchase_time'])?></span></p>
                            <div class="result-head-pic">
                                <div class="rh-wrap"><img width="110" height="110" src="<?php echo \App\Member\Helpers\MemberHelper::getImagePath($this->view->baseUrl, $this->view->goodsInfo['prize_buyer_avatar'])?>"></div><a rel="nofollow" href="<?php echo $this->view->baseUrl?>yungou/member/index?id=<?php echo $this->view->goodsInfo['prize_buyer_id']?>" target="_blank" title="<?php echo getBuyerName($this->view->goodsInfo['prize_buyer_name'],$this->view->goodsInfo['prize_buyer_register_by'])?>" class="ng-result-head transparent-png"><span class="name">获得者</span></a>
                            </div>
                        </div>
                        <div class="result-con-code">
                            <p class="code-name">— 幸运云购码 —</p>
                            <span class="code-num">
                                <?php echo $this->view->goodsInfo['prize_code']?></span>
                        </div>
                    </div>
                    <div class="result-how">
                        <h6>如何计算?</h6>
                        <p>1、取该商品最后购买时间前网站所有商品的最后100条购买时间记录；</p>
                        <p>2、按时、分、秒、毫秒排列取值之和，除以该商品总参与人次后取余数；</p>
                        <p>3、余数加上10000001 即为“幸运云购码”；</p>
                        <p>4、余数是指整数除法中被除数未被除尽部分， 如7÷3 = 2 ......1，1就是余数。</p>
                    </div>
                </div>
            </div>
            <!--查看分期-->
            <div class="ng-result-select">
                <ul class="r-select">
                    <?php $nextAndPrevPeriod = \App\Goods\Helpers\GoodsHelper::getNextAndPrevPeriod($this->view->goodsInfo)?>
                    <li>
                    <?php if(!empty($nextAndPrevPeriod['next'])){?>
                         <a href="<?php echo $this->view->baseUrl?>yungou/product/detail?id=<?php echo $nextAndPrevPeriod['next']?>"><i class="ng-result-bg up transparent-png"></i><span></span></a>
                    <?php }else{?>
                         <a href="javascript:;"><i class="ng-result-bg up transparent-png"></i><span></span></a>
                    <?php }?>
                    </li>                    
                    <li>
                    <?php if(!empty($nextAndPrevPeriod['prev'])){?>
                         <a href="<?php echo $this->view->baseUrl?>yungou/product/detail?id=<?php echo $nextAndPrevPeriod['prev']?>"><i class="ng-result-bg down transparent-png"></i><span></span></a>
                    <?php }else{?>
                         <a href="javascript:;"><i class="ng-result-bg down transparent-png"></i><span></span></a>
                    <?php }?>
                    </li>
                </ul>
            </div>
            <!--清除浮动-->
            <div class="clear"></div>
        </div>
    </div>
    <!--3块导航-->
    <div class="ng-main clearfix">
        <div class="ng-data-wrapper">
            <div class="ng-data-m">
                <ul id="ul_menu" class="ng-data-nav clearfix">
                    <li class="current"><a href="javascript:;">计算详情</a></li>
                    <li><a href="javascript:;">参与记录</a></li>
                    <li><a href="javascript:;">商品晒单</a></li>
                </ul>
                <div id="midNavLine" class="m-line"></div>
            </div>

            <!--计算详情-->
            <div id="div_evaldata" class="ng-data-inner div-data-box-a">
                <div class="ng-data-info">
                    <div class="ng-data-head">
                        <span class="time">云购时间</span>
                        <span class="data">转换数据</span>
                        <span class="user">会员</span>
                        <span class="num">参与人次</span>
                        <span class="product">商品名称</span>
                    </div>
                </div>

                <div class="ng-data-detail">
                    <div class="ng-data-step">
                        <p class="title">
                            截止该商品最后购买时间【<?php echo getMilliTime4Show($this->view->goodsInfo['last_purchase_time'])?>】网站所有商品的最后100条购买时间(时、分、秒、毫秒)记录
                        </p>
                        <div class="step">
                            <ul class="step-inner clearfix">
                                <li class="s-r1"><p>计算结果</p></li>
                                <li class="s-t">=</li>
                                <li class="s-t">(</li>
                                <li class="s-r2"><p><?php echo $this->view->goodsInfo['prize_total_time']?></p><span>以下100条时间取值之和</span></li>
                                <li id="li_mod" class="s-t mod"><i>%</i><span class="txt">(取余)</span></li>
                                <li class="s-r3"><p><?php echo $this->view->goodsInfo['total_person_time']?></p><span>总需参与人次</span></li>
                                <li class="s-t">)</li>
                                <li class="s-t">+</li>
                                <li class="s-r4"><p><?php echo $this->view->goodsInfo['lottery_code']?></p><span>固定数值</span></li>
                                <li class="s-t">=</li>
                                <li class="s-r5"><p><?php echo $this->view->goodsInfo['prize_code']?></p><span>最终计算结果</span></li>
                            </ul>
                            <div class="ng-result-bg equals transparent-png">
                            </div>
                        </div>
                        <div id="div_whatmod" class="ng-mod-wrapper" style="display: none;">
                            <div class="ng-mod-inner"><p>余数是指整数除法中被除数未被除尽部分,<br>如7÷3 = 2 ......1，1就是余数。</p></div>
                            <i class="s"><i class="s"></i></i>
                        </div>
                    </div>
                    <div class="ng-table-wrapper">
                        <div id="div_nginner" class="ng-table-inner" style="height: 322px; display: block;">
                            <ul class="ng-table-ul clearfix"></ul>
                            <div class="ng-table-bg01 transparent-png"></div>
                            <div class="ng-table-bg02 transparent-png"></div>
                            <div class="ng-table-bg03 ng-result-bg transparent-png"></div>
                        </div>
                        <div id="div_showmore" class="ng-see-more">
                            <span>展开全部100条数据<b><s></s></b></span>
                        </div>
                    </div>
                </div>

                <ul class="ng-table-ul ng-tc-ul"></ul>
            </div>

            <!--所有参与记录-->
            <div id="div_allrecord" class="ng-all-record div-data-box-b" style="display: none;">
                <div class="record"></div>
                <div class="g-pagination w1190" id="g-pagination-a" style="display:none;"></div>
            </div>

            <!--晒单-->
            <div id="div_postlist" class="ng-share-goods div-data-box-c" style="display: none;">
                <div class="total" style="display:none;">本商品已有<span class="gray6">0</span>位幸运用户晒单 <em class="f-mar-left">总共</em><span class="orange">0</span>条评论</div>
                <div class="ng-share-wrapper ng-share-data"></div>
                <div class="g-pagination" id="g-pagination-b" style="display:none;"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/detail.js"></script>



















      