<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<TITLE>大众点评</TITLE>
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<script src="<?php echo $this->getResourceUrl()?>js/jquery-1.8.0.min.js"></script>
<script src="<?php echo $this->getResourceUrl()?>js/jquery.query.js"></script>
<script src="<?php echo $this->getResourceUrl()?>js/jquery.cookie.js"></script>
<script type="text/javascript">
		var web_path = "<?php echo $this->config['global']['path']?>";
</script>
</HEAD>

<BODY topMargin=0>
<button  id="authorize1" >大众点评授权</button><br/>
</body>

<script language="javascript">
	var App = {
	    init : function(){
	    	 // 用户大众点评授权
	        $("#authorize1").size() && authorizeTest();
		     // 用户大众点评POST
	        $("#post1").size() && postTest();	
		     // 用户大众点评GET
	        $("#get1").size() && getTest();	        
	    }
	};

	$(document).ready(App.init);

	//用户大众点评授权
	function authorizeTest(){
	    $("#authorize1").on("click",
	        function(){
	        	var callbackUrl = encodeURIComponent("http://140604fg0241.umaman.com/dianping/test/index?packageId=3456");
	    		window.location.href = "http://140604fg0241.umaman.com/dianping/sns/index?appid=<?php echo $this->appid?>&state=1234&redirect="+callbackUrl;
	        }
	    )
	}
	

	//用户大众点评Post
	function postTest(){
	    $("#post1").on("click",
	        function(){
	            var params = {};
	            var umaId=$.cookie('dianping[umaId]');	            
	            var user_id=$.cookie('dianping[user_id]');
	            var user_nickname=$.cookie('dianping[user_nickname]');
	            params['umaId'] = umaId;
	            params['url'] = 'statuses/update';
	            params['multi'] = 'false';
	            params['parameters'] = {status:'用户post测试',visible:0};
	    		
	            $.ajax(
	            {
	                url:web_path+'dianping/index/post',
	                type:'POST',
	                data:params,
	                dataType: "json",
	                success:function(data) {
	                    console.info(data);
	                    if(data.success) {
	                    	alert(data.result);
	                    }
	                    else {
	                        alert(data.message);
	                    }
	                }
	            });
	        }
	    )
	}

	//用户大众点评Get
	function getTest(){
	    $("#get1").on("click",
	        function(){
	            var params = {};
	            var umaId=$.cookie('dianping[umaId]');
	            var user_id=$.cookie('dianping[user_id]');
	            var user_nickname=$.cookie('dianping[user_nickname]');
	            params['umaId'] = umaId;
	            params['url'] = 'users/show';
	            params['multi'] = 'false';
	            params['parameters'] = {user_id:'1596822015'};           
	            $.ajax(
	            {
	                url:web_path+'dianping/index/get',
	                type:'POST',
	                data:params,
	                dataType: "json",
	                success:function(data) {
	                    console.info(data);
	                    if(data.success) {
	                    	alert(data.result);
	                    }
	                    else {
	                        alert(data.message);
	                    }
	                }
	            });
	        }
	    )
	}
  </script>
</html>