<script>
	var Login = function() {

		return {
			//main function to initiate the module
			init: function() {
				jQuery('#login_form_error1').hide();
				jQuery('#login_form_group1').removeClass('has-error');

				$('.login-form').validate({
					errorElement: 'input', //default input error message container
					errorClass: 'help-inline', // default input error message class
					focusInvalid: false, // do not focus the last invalid input
					rules: {
						username: {
							required: true
						},
						password: {
							required: true
						},
						remember: {
							required: false
						}
					},

					messages: {
						username: {
							required: "Username is required."
						},
						password: {
							required: "Password is required."
						}
					},

					invalidHandler: function(event, validator) { //display error alert on form submit   
						$('#login_form_error1', $('.login-form')).show();
					},

					highlight: function(element) { // hightlight error inputs
						$(element)
							.closest('.form-group').addClass('has-error'); // set error class to the control group
					},

					success: function(label) {
						label.closest('.form-group').removeClass('has-error');
						//label.remove();
					},

					errorPlacement: function(error, element) {
						error.addClass('help-small no-left-padding').insertAfter(element.closest('.input-icon'));
					},

					submitHandler: function(form) {
						Login.login();
					}
				});

				$('.login-form input').keypress(function(e) {
					if (e.which == 13) {
						if ($('.login-form').validate().form()) {
							Login.login();
						}
						return false;
					}
				});

			},
			// 登录
			login: function() {
				//alert("login！");
				var formData = new FormData(document.getElementById("login_form1")); //

				$.ajax({
					//几个参数需要注意一下
					type: "POST", //方法类型
					dataType: "json", //预期服务器返回的数据类型
					url: "<?php echo $this->view->form_act ?>", //url
					contentType: false, //这里
					processData: false, //这两个一定设置为false
					data: formData,
					//data: $('.login-form').serialize(),
					success: function(result) {
						console.log(result); //打印服务端返回的数据(调试用)
						// 如果发生了错误的话
						if (result.error == 1) {
							$('#login_form_error1').html('<i class="fa fa-times-circle-o"></i>' + result.message);
							jQuery('#login_form_error1').show();
							jQuery('#login_form_group1').addClass('has-error');
						} else {
							// 跳转url
							window.location.href = result.content.redirect;
						}
					},
					error: function() {
						//alert("异常！");
						$('.alert-error', $('.login-form')).show();
					}
				});
			}
		};

	}();
</script>