<?php
$column_width = 6;
$filterID = 'filter-box';
?>
<div class="box-header with-border <?php echo !empty($expand) ? '' : 'hide' ?>" id="<?php echo $filterID ?>">
    <form action="<?php echo empty($action) ? '#' : $action ?>" class="form-horizontal" pjax-container method="get">
        <div class="row">
            <?php foreach ($this->view->schemas as $key => $field) { ?>
                <?php
                $field['search']['is_show'] = !isset($field['search']['is_show']) ? $field['form']['is_show'] : $field['search']['is_show'];
                if (empty($field['search']['is_show'])) {
                    continue;
                }
                $field['name'] = empty($field['search']['name']) ? $field['name'] : $field['search']['name'];
                $field['search']['placeholder'] = empty($field['search']['placeholder']) ? "输入 " . $field['name'] : $field['search']['placeholder'];
                $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                $field['search']['items'] = empty($field['search']['items']) ? $field['form']['items'] : $field['search']['items'];
                if (!isset($field['search']['partial'])) {
                    if ($field['search']['input_type'] == "image") {
                        continue;
                    } elseif ($field['search']['input_type'] == "file") {
                        continue;
                    }
                }
                ?>
                <div class="col-md-<?php echo $column_width ?>">
                    <div class="box-body">
                        <div class="fields-group">
                            <?php
                            if ($field['search']['input_type'] == "hidden") {
                                $this->partial('partials/filter/between');
                            } elseif ($field['search']['input_type'] == "datetimepicker") {
                                $this->partial('partials/filter/betweenDatetime');
                            } elseif ($field['search']['input_type'] == "number") {
                                $this->partial('partials/filter/between');
                            } else {
                                $this->partial('partials/filter/where');
                            }
                            ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <div class="row">
                <div class="col-md-<?php echo $column_width ?>">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'query')) { ?>
                            <div class="btn-group pull-left">
                                <button id="btnSearch" class="btn btn-info submit btn-sm"><i class="fa fa-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        <?php } ?>

                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'export')) { ?>
                            <div class="btn-group pull-left" style="margin-left: 10px;">
                                <button id="btnExport" class="btn btn-info submit btn-sm"><i class="fa fa-download"></i>&nbsp;&nbsp;导出</button>
                            </div>
                        <?php } ?>

                        <?php foreach ($this->view->headerTools as $key => $tool) { ?>
                            <?php if (!empty($tool['is_show']) && !empty($tool['is_export'])) { ?>
                                <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action'])) { ?>
                                    <div class="btn-group pull-left" style="margin-left: 10px;">
                                        <button id="btnExport-<?php echo $key ?>" class="btn btn-info submit btn-sm header-tool-export-<?php echo $key ?>"><i class="fa <?php echo empty($tool['icon']) ? 'fa-download' : $tool['icon'] ?>"></i>&nbsp;&nbsp;<?php echo $tool['title'] ?></button>
                                    </div>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>

                        <?php if (false) { ?>
                            <div class="btn-group pull-left " style="margin-left: 10px;">
                                <a href="<?php echo $this->view->baseUrl ?><?php echo $this->view->moduleName ?>/<?php echo $this->view->controllerName ?>/list?_pjax=%23pjax-container" class="btn btn-default btn-sm"><i class="fa fa-undo"></i>&nbsp;&nbsp;重置</a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>