<?php
$column_width = 6;
$filterID = 'filter-box';
?>
<div class="box-header with-border <?php echo !empty($expand) ? '' : 'hide' ?>" id="<?php echo $filterID ?>">
    <form action="<?php echo empty($action) ? '#' : $action ?>" class="form-horizontal" pjax-container method="get">
        <div class="row">
            <?php foreach ($this->view->schemas as $key => $field) { ?>
                <?php
                $_SESSION['search_filter']['search_' . $key . '_from'] = "";
                $_SESSION['search_filter']['search_' . $key . '_to'] = "";
                $_SESSION['search_filter'][$key] = "";

                $field['search']['is_show'] = !isset($field['search']['is_show']) ? $field['form']['is_show'] : $field['search']['is_show'];
                if (empty($field['search']['is_show'])) {
                    continue;
                }
                $field['name'] = empty($field['search']['name']) ? $field['name'] : $field['search']['name'];
                $field['search']['placeholder'] = empty($field['search']['placeholder']) ? "输入 " . $field['name'] : $field['search']['placeholder'];
                $field['search']['input_type'] = empty($field['search']['input_type']) ? $field['form']['input_type'] : $field['search']['input_type'];
                $field['search']['items'] = empty($field['search']['items']) ? (!empty($field['form']['items']) ? $field['form']['items'] : array()) : $field['search']['items'];
                if ($field['search']['input_type'] == 'checkbox' || $field['search']['input_type'] == 'listbox') {
                    $field['search']['input_type'] = 'select';
                }
                if (empty($field['search']['content_type'])) {
                    if (!empty($field['form']['content_type'])) {
                        $field['search']['content_type'] = $field['form']['content_type'];
                    }
                }
                if (!isset($field['search']['partial'])) {
                    if ($field['search']['input_type'] == "image") {
                        continue;
                    } elseif ($field['search']['input_type'] == "file") {
                        continue;
                    }
                }
                ?>
                <div class="col-md-<?php echo $column_width ?>">
                    <div class="box-body">
                        <div class="fields-group">
                            <?php
                            $prepend = '';
                            $otherclassList = array();
                            if ($field['search']['input_type'] == "hidden") {
                                $this->partial('partials/filter/between');
                            } elseif ($field['search']['input_type'] == "datetimepicker") {
                                $prepend = '<i class="fa fa-calendar"></i>';
                                if (empty($field['search']['content_type'])) {
                                    $otherclassList = array('search-class-datetime');
                                } else {
                                    if ($field['search']['content_type'] == 'datetime') {
                                        $otherclassList = array('search-class-datetime');
                                    } elseif ($field['search']['content_type'] == 'date') {
                                        $otherclassList = array('search-class-date');
                                    } elseif ($field['search']['content_type'] == 'time') {
                                        $otherclassList = array('search-class-time');
                                    }
                                }
                                $this->partial('partials/filter/betweenDatetime');
                            } elseif ($field['search']['input_type'] == "datetimerange") {
                                $prepend = '<i class="fa fa-calendar"></i>';
                                $otherclassList = array('search-class-datetime');
                                $this->partial('partials/filter/betweenDatetime');
                            } elseif ($field['search']['input_type'] == "daterange") {
                                $prepend = '<i class="fa fa-calendar"></i>';
                                $otherclassList = array('search-class-date');
                                $this->partial('partials/filter/betweenDatetime');
                            } elseif ($field['search']['input_type'] == "timerange") {
                                $prepend = '<i class="fa fa-clock-o"></i>';
                                $otherclassList = array('search-class-time');
                                $this->partial('partials/filter/betweenDatetime');
                            } elseif ($field['search']['input_type'] == "number") {
                                $otherclassList = array('search-class-number');
                                $this->partial('partials/filter/between');
                            } elseif ($field['search']['input_type'] == "slider") {
                                $otherclassList = array('search-class-number');
                                $this->partial('partials/filter/between');
                            } elseif ($field['search']['input_type'] == "currency") {
                                $otherclassList = array('search-class-number');
                                $this->partial('partials/filter/between');
                            } else {
                                $this->partial('partials/filter/where');
                            }
                            ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <div class="row">
                <div class="col-md-<?php echo $column_width ?>">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'query')) { ?>
                            <div class="btn-group pull-left">
                                <button id="btnSearch" class="btn btn-info submit btn-sm"><i class="fa fa-search"></i>&nbsp;&nbsp;搜索</button>
                            </div>
                        <?php } ?>

                        <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, 'export') && !$this->view->readonly) { ?>
                            <div class="btn-group pull-left" style="margin-left: 10px;">
                                <button id="btnExport" class="btn btn-info submit btn-sm"><i class="fa fa-download"></i>&nbsp;&nbsp;导出</button>
                            </div>
                        <?php } ?>

                        <?php foreach ($this->view->headerTools as $key => $tool) { ?>
                            <?php if (!empty($tool['is_show']) && !empty($tool['is_export'])) { ?>
                                <?php
                                $is_show4HeaderTool4Export = is_callable($tool['is_show']) ? $tool['is_show']() : true;
                                ?>
                                <?php if (!empty($is_show4HeaderTool4Export)) { ?>
                                    <?php if ($this->myTag->isCanDo($this->view->moduleName, $this->view->controllerName, $tool['action']) && !$this->view->readonly) { ?>
                                        <div class="btn-group pull-left" style="margin-left: 10px;">
                                            <button id="btnExport-<?php echo $key ?>" class="btn btn-info submit btn-sm header-tool-export-<?php echo $key ?>"><i class="fa <?php echo empty($tool['icon']) ? 'fa-download' : $tool['icon'] ?>"></i>&nbsp;&nbsp;<?php echo $tool['title'] ?></button>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>

                        <?php if (false) { ?>
                            <div class="btn-group pull-left " style="margin-left: 10px;">
                                <a href="<?php echo $this->myTag->getUrl($this->view, 'list', array('_pjax' => '%23pjax-container')); ?>" class="btn btn-default btn-sm"><i class="fa fa-undo"></i>&nbsp;&nbsp;重置</a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>