<select class="form-control <?php echo empty($otherclassList)?'':implode(' ',$otherclassList) ?> <?php echo $key ?>" id="<?php echo 'search_' . $key ?>" name="<?php echo 'search_' . $key ?>[]" multiple style="width: 100%;">
    <option value="" <?php if ((empty($_SESSION['search_filter'][$key]))) { ?>selected<?php } ?>></option>
    <?php foreach ($options as $select => $option) { ?>
        <option value="<?php echo $select ?>" <?php if (!empty($_SESSION['search_filter'][$key]) && in_array($select, $_SESSION['search_filter'][$key])) { ?>selected<?php } ?>><?php echo $option ?></option>
    <?php } ?>
</select>