<div class="form-group">
    <label class="col-sm-2 control-label"> <?php echo $field['name'] ?></label>
    <div class="col-sm-8">
        <!--@include($presenter->view())-->
        <?php
        if (!isset($field['search']['partial'])) {
            //print_r($field);die('xxx');
            $type = "text";
            $icon = "pencil";
            $prepend = '<i class="fa fa-pencil"></i>';
            $otherclassList = array();
            $inline = true;
            if ($field['search']['input_type'] == "textarea") {
                $this->partial('partials/filter/text');
            } elseif ($field['search']['input_type'] == "ckeditor") {
                $this->partial('partials/filter/text');
            } elseif ($field['search']['input_type'] == "ueditor") {
                $this->partial('partials/filter/text');
            } elseif ($field['search']['input_type'] == "text") {
                if (!empty($field['search']['content_type'])) {
                    if ($field['search']['content_type'] == 'email') {
                        $prepend = '<i class="fa fa-envelope"></i>';
                    } elseif ($field['search']['content_type'] == 'phone') {
                        $otherclassList = array('search-class-mobile');
                        $prepend = '<i class="fa fa-phone"></i>';
                    } elseif ($field['search']['content_type'] == 'url') {
                        $prepend = '<i class="fa fa-internet-explorer"></i>';
                    } elseif ($field['search']['content_type'] == 'ip') {
                        $otherclassList = array('search-class-ip');
                        $prepend = '<i class="fa fa-laptop"></i>';
                    } elseif ($field['search']['content_type'] == 'color') {
                        $otherclassList = array('search-class-colorpicker');
                        $prepend = '<i></i>';
                    }
                }
                $this->partial('partials/filter/text');
            } elseif ($field['search']['input_type'] == "radio") {
                $options = is_callable($field['search']['items']) ? $field['search']['items']() : $field['search']['items'];
                //$this->partial('partials/filter/radio');
                $otherclassList = array('search-class-select');
                $this->partial('partials/filter/select');
            } elseif ($field['search']['input_type'] == "select") {
                $options = is_callable($field['search']['items']) ? $field['search']['items']() : $field['search']['items'];
                $otherclassList = array('search-class-select');
                $this->partial('partials/filter/select');
            } elseif ($field['search']['input_type'] == "checkbox") {
                $options = is_callable($field['search']['items']) ? $field['search']['items']() : $field['search']['items'];
                //$this->partial('partials/filter/checkbox');
                $otherclassList = array('search-class-select');
                $this->partial('partials/filter/select');
            } elseif ($field['search']['input_type'] == "switch") {
                $options = is_callable($field['search']['items']) ? $field['search']['items']() : $field['search']['items'];
                $otherclassList = array('search-class-select');
                $this->partial('partials/filter/select');
            }
        } else {
            $this->partial($field['search']['partial']);
        }
        ?>
    </div>
</div>