<div class="row">
    <div class="col-md-12">
        <div class="callout callout-info">
            <h4>Json Editor</h4>
            <a href="https://github.com/laravel-admin-extensions/json-editor" target='_blank'>https://github.com/laravel-admin-extensions/json-editor</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Json Editor</h3>
                <div class="box-tools pull-right">
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body" style="display: block;">
                <form method="POST" action="" class="form-horizontal" accept-charset="UTF-8" pjax-container="1">
                    <div class="box-body fields-group">

                        <div class="form-group  ">

                            <label for="content" class="col-sm-2  control-label">Content</label>

                            <div class="col-sm-8">


                                <div id="content" style="width: 100%; height: 100%;"></div>

                                <input type="hidden" id="content_input" name="content" value="{
    &quot;name&quot;: &quot;laravel/laravel&quot;,
    &quot;description&quot;: &quot;The Laravel Framework.&quot;,
    &quot;keywords&quot;: [&quot;framework&quot;, &quot;laravel&quot;],
    &quot;license&quot;: &quot;MIT&quot;,
    &quot;type&quot;: &quot;project&quot;,
    &quot;require&quot;: {
        &quot;php&quot;: &quot;&gt;=7.0.0&quot;,
        &quot;encore/laravel-admin&quot;: &quot;^1.7&quot;,
        &quot;fideloper/proxy&quot;: &quot;~3.3&quot;,
        &quot;intervention/image&quot;: &quot;^2.4&quot;,
        &quot;jxlwqq/code-mirror&quot;: &quot;^1.0&quot;,
        &quot;jxlwqq/json-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/api-tester&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/backup&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/chartjs&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/clike-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/config&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/grid-lightbox&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/grid-sortable&quot;: &quot;v1.0&quot;,
        &quot;laravel-admin-ext/helpers&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/js-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/log-viewer&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/media-manager&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/php-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/phpinfo&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/python-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/reporter&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/scheduling&quot;: &quot;dev-master&quot;,
        &quot;laravel-admin-ext/simplemde&quot;: &quot;^1.0&quot;,
        &quot;laravel-admin-ext/summernote&quot;: &quot;^0.1.0&quot;,
        &quot;laravel-admin-ext/wang-editor&quot;: &quot;^1.0&quot;,
        &quot;laravel/framework&quot;: &quot;5.5.*&quot;,
        &quot;laravel/tinker&quot;: &quot;~1.0&quot;,
        &quot;maatwebsite/excel&quot;: &quot;~2.1.0&quot;,
        &quot;matthiasmullie/minify&quot;: &quot;^1.3&quot;,
        &quot;spatie/eloquent-sortable&quot;: &quot;^3.4&quot;,
        &quot;spatie/laravel-backup&quot;: &quot;^5.0&quot;
    },
    &quot;require-dev&quot;: {
        &quot;barryvdh/laravel-debugbar&quot;: &quot;^3.0&quot;,
        &quot;fzaninotto/faker&quot;: &quot;~1.4&quot;,
        &quot;mockery/mockery&quot;: &quot;0.9.*&quot;,
        &quot;phpunit/phpunit&quot;: &quot;~6.0&quot;
    },
    &quot;autoload&quot;: {
        &quot;classmap&quot;: [
            &quot;database&quot;
        ],
        &quot;psr-4&quot;: {
            &quot;App\\&quot;: &quot;app/&quot;
        }
    },
    &quot;autoload-dev&quot;: {
        &quot;psr-4&quot;: {
            &quot;Tests\\&quot;: &quot;tests/&quot;
        }
    },
    &quot;extra&quot;: {
        &quot;laravel&quot;: {
            &quot;dont-discover&quot;: [
            ]
        }
    },
    &quot;scripts&quot;: {
        &quot;post-root-package-install&quot;: [
            &quot;@php -r \&quot;file_exists(&#039;.env&#039;) || copy(&#039;.env.example&#039;, &#039;.env&#039;);\&quot;&quot;
        ],
        &quot;post-create-project-cmd&quot;: [
            &quot;@php artisan key:generate&quot;
        ],
        &quot;post-autoload-dump&quot;: [
            &quot;Illuminate\\Foundation\\ComposerScripts::postAutoloadDump&quot;,
            &quot;@php artisan package:discover&quot;
        ]
    },
    &quot;config&quot;: {
        &quot;preferred-install&quot;: &quot;dist&quot;,
        &quot;sort-packages&quot;: true,
        &quot;optimize-autoloader&quot;: true
    },
    &quot;minimum-stability&quot;: &quot;dev&quot;,
    &quot;prefer-stable&quot;: true
}
" />

                            </div>
                        </div>


                    </div>

                    <input type="hidden" name="_token" value="JqJ133HxM2c2Nr32GRNHn49NF4KynsKWlE0sY0e5">

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="col-md-2"></div>

                        <div class="col-md-8">
                            <div class="btn-group pull-left">
                                <button type="reset" class="btn btn-warning pull-right">重置</button>
                            </div>

                            <div class="btn-group pull-right">
                                <button type="submit" class="btn btn-info pull-right">提交</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div><!-- /.box-body -->
        </div>

        <script>

        </script>
    </div>
</div>
<script data-exec-on-popstate>
    $(function() {
        // create the editor
        var container = document.getElementById("content");
        var options = null;
        window['editor_content'] = new JSONEditor(container, options);

        // set json
        var json = {
            "name": "laravel/laravel",
            "description": "The Laravel Framework.",
            "keywords": ["framework", "laravel"],
            "license": "MIT",
            "type": "project",
            "require": {
                "php": ">=7.0.0",
                "encore/laravel-admin": "^1.7",
                "fideloper/proxy": "~3.3",
                "intervention/image": "^2.4",
                "jxlwqq/code-mirror": "^1.0",
                "jxlwqq/json-editor": "^1.0",
                "laravel-admin-ext/api-tester": "dev-master",
                "laravel-admin-ext/backup": "dev-master",
                "laravel-admin-ext/chartjs": "^1.0",
                "laravel-admin-ext/clike-editor": "^1.0",
                "laravel-admin-ext/config": "dev-master",
                "laravel-admin-ext/grid-lightbox": "^1.0",
                "laravel-admin-ext/grid-sortable": "v1.0",
                "laravel-admin-ext/helpers": "dev-master",
                "laravel-admin-ext/js-editor": "^1.0",
                "laravel-admin-ext/log-viewer": "dev-master",
                "laravel-admin-ext/media-manager": "^1.0",
                "laravel-admin-ext/php-editor": "^1.0",
                "laravel-admin-ext/phpinfo": "dev-master",
                "laravel-admin-ext/python-editor": "^1.0",
                "laravel-admin-ext/reporter": "dev-master",
                "laravel-admin-ext/scheduling": "dev-master",
                "laravel-admin-ext/simplemde": "^1.0",
                "laravel-admin-ext/summernote": "^0.1.0",
                "laravel-admin-ext/wang-editor": "^1.0",
                "laravel/framework": "5.5.*",
                "laravel/tinker": "~1.0",
                "maatwebsite/excel": "~2.1.0",
                "matthiasmullie/minify": "^1.3",
                "spatie/eloquent-sortable": "^3.4",
                "spatie/laravel-backup": "^5.0"
            },
            "require-dev": {
                "barryvdh/laravel-debugbar": "^3.0",
                "fzaninotto/faker": "~1.4",
                "mockery/mockery": "0.9.*",
                "phpunit/phpunit": "~6.0"
            },
            "autoload": {
                "classmap": [
                    "database"
                ],
                "psr-4": {
                    "App\\": "app/"
                }
            },
            "autoload-dev": {
                "psr-4": {
                    "Tests\\": "tests/"
                }
            },
            "extra": {
                "laravel": {
                    "dont-discover": []
                }
            },
            "scripts": {
                "post-root-package-install": [
                    "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
                ],
                "post-create-project-cmd": [
                    "@php artisan key:generate"
                ],
                "post-autoload-dump": [
                    "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
                    "@php artisan package:discover"
                ]
            },
            "config": {
                "preferred-install": "dist",
                "sort-packages": true,
                "optimize-autoloader": true
            },
            "minimum-stability": "dev",
            "prefer-stable": true
        };
        window['editor_content'].set(json);

        // get json
        $('button[type="submit"]').click(function() {
            var json = window['editor_content'].get()
            $('input[id=content_input]').val(JSON.stringify(json))
        })

    });
</script>