<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>关于我们</h2>
                <style>
                .help-nav ul li a.cur13{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur13 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <div class="about-banner">
                        <img src="/help/images/about_03.jpg">
                    </div>
                    <p class="textindent">
                        1元集资购（www.1yyg.com）是一种全新的互动购物体验方式，是时尚 、潮流的风向标，能满足个性、年轻消费者的购物需求，由深圳市一元集资购网络科技有限公司注入巨资打造的新型购物网。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        1元集资购以“快乐集资购，惊喜无限”为宗旨，力求打造一个100%公平公正、100%正品保障、寄娱乐与购物一体化的新型购物网站。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        随着互联网的发展及网购消费模式的多样化，1元集资购势必成为中国电子商网站中最具活力的生力军及网民最爱的购物网，必将迅速崛起，成为互联网新时代的佼佼者！</p>
                            <p style="height:10px;"></p>
                    <h3>集资购的产生</h3>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        互联网与网络购物的兴起与迅速发展，给各位消费者带来了前所未有的便利。 品类丰富的各类商品不断地充斥着我们的眼球，不断的吸引着我们的欲望；眼花缭乱的商品让我们难以取舍，经济的制约让消费者们一次又一次的忍痛割爱，“鱼与熊掌难以兼得”让很多消费者在体验购物的过 程中也尝受着无奈的痛苦。此时需要有一种新型购物模式在带给消费者购物快乐的同时，也能满足消费者的经济预期，对于每一种吸引眼球的商品，都只需要花费完全可以忽略的成本来得到它，1元集资购应势而生。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        1元集资购是一种全新的、充满乐趣与惊喜的购物模式：通过1元集资购将有共同爱好的人群聚集在一起；通过集资购，将为您的生活带来无法预计的惊喜与刺激；参与集资购，惊喜无限。每件商品您只需投入1元钱，即可获得一个“集资购码”，每件商品可多次参与， 参与次数越多，获得商品机率越大；当然，您也可以一次购买多个“集资购码”；每件商品设有所需参与人数下限，只要参与人数达标，系统即计算出一位幸运者，由这位幸运者获得这件商品。幸运轮流转，每个人都有机会在投入1元钱的成本下获得商品，心动就在眼前。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        自此，更新换代迅速的数码商品、供货紧俏的热门商品、心动却因各种限制而无法得到的商品，在1元集资购，您的所有欲望都将得到满足，那就让我们一起来体验集资购带来的快乐与魔力吧！</p>
                        <br><br>

                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>

<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>