<link rel="stylesheet" type="text/css" href="/help/css/Index.css">
<div class="busCon">
    <div class="busBanner">
        <img src="/help/images/pic_03.jpg">
        <img src="/help/images/pic_05.jpg">
    </div>
    <div class="busJDZ">
        <div class="busAbout">
            <ul>
                <li class="busLi busLi1"><b></b></li>
                <li class="busLi4"><p>1元云购（www.1yyg.com）是一种全新的互动购物体验方式，是时尚、潮流的风向标，能满足个性、年轻消费者的购物需求，由深圳市一元云购网络科技有限公司注入巨资打造的新型购物网…… <a href="/yungou/help/index" target="_blank">更多&gt;&gt;</a></p></li>
            </ul>
        </div>
        <div class="busAbout busMar">
            <ul>
                <li class="busLi busLi2"><b></b></li>
                <li class="busLi4"><p>国内外品牌商、经销商或有正规货源及授权的渠道商，具有合法完整的企业营业执照、企业税务登记证 、品牌授权书（或商标注册证）。欢迎以多样化合作方式进行商务合作。</p></li>
            </ul>
        </div>
        <div class="busAbout">
            <ul>
                <li class="busLi busLi3"><b></b></li>
                <li class="busLi4">
                    邮箱：<a href="mailto:metoo_121@qq.com?subject=商务合作">metoo_121@qq.com</a><br>
                    邮编：518030<br>
                    地址：深圳市福田区红荔路38号<br>
                          <span>群星广场A座24层</span>
                </li>
            </ul>
        </div>
    </div>
    
    <div class="busCore">
        <div class="busCoreT">
            <b></b>
        </div>
        <div class="busCoreB">
            <ul>
                <li class="busCoreB1">
                    <h3>创新模式，潜力巨大，前景广阔</h3>
                    1元云购是一种全新的互动购物体验，集购物、娱乐于一体，引领购物娱乐潮流，是国内最具潜质的综合型B2C电子商务平台，由深圳市一元云购网络科技有限公司投入巨资打造。
                </li>
                <li class="busCoreB2">
                    <h3>高效运营，专业品质管理</h3>
                    强大的互联网营销能力，领先的精准营销手段，线上线下渠道的无缝整合，快速准确地向用户传递最新、最热商品信息。
                </li>
            </ul>
            <ul>
                <li class="busCoreB3">
                    <h3>高端技术支撑，应对庞大流量</h3>
                    1元云购线上、移动App、微信营销平台等带来庞大流量，拥有高端信息技术支撑的网络购物平台，可支持1000万用户同时访问，每天可处理上万订单。
                </li>
                <li class="busCoreB4">
                    <h3>充满激情与活力的团队</h3>
                    青春激扬，这里充满创意与灵感。我们立志成为一家快速成长、充满活力的创业公司，我们更矢志成为一家伟大的、备受社会尊敬的基业长青的企业！
                </li>
            </ul>
        </div>
    </div>
    


    <div class="busCircuit">
        <div class="busCircuitT">
            <b></b>
        </div>
        <div class="busCircuitB">
            <div class="busCircuitB2">
                <ul>
                    <li class="busCir">
                        <p><img src="/help/images/pic_40-15.jpg"></p>
                        <h4>初步接洽，确认合作意向</h4>
                        供应商与1元云购商品运营中心联系<br>双方接洽，确认合作意向
                    </li>
                    <li class="busCir">
                        <p><img src="/help/images/pic_42.jpg"></p>
                        <h4>1元云购进行资格审查</h4>
                        1元云购商品运营中心对供应商<br>提供的资料进行审查
                    </li>
                    <li class="busCir">
                        <p><img src="/help/images/pic_40.jpg"></p>
                        <h4>商讨并确认商品清单</h4>
                        供应商提交商品清单及样品，<br>1元云购确认商品并反馈
                    </li>
                    <li class="busCir busCir4">
                        <p><img src="/help/images/pic_40-14.jpg"></p>
                        <h4>签订合作合同</h4>
                        商讨合同具体细节，签订合同<br>供应商品进行上线销售
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>