<?php $siteSettings=\App\Site\Views\Helpers\SiteHelper::getSettings();?>
<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>联系我们</h2>
                <style>
                .help-nav ul li a.cur16{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur16 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <h3 class="mat0">联系我们</h3>
                    <p>深圳市一元云购网络科技有限公司</p>
                    <p>热 线：<?php echo $siteSettings['tel400']?></p>
                    <p>邮 箱：service@1yyg.com</p>
                    <p>地 址：深圳市福田区红荔路38号群星广场A座24层</p>
                    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;深圳市龙岗区贝尔路2号新天下集团大厦7楼</p>
                    <p class="bottom-space20px">邮 编：518030</p>
                    <h3>投诉建议</h3>
                    
                    <p>电 话：<?php echo $siteSettings['tel400']?>转3</p>
                    <p class="bottom-space20px">邮 箱：service@1yyg.com</p>
                    <h3>商务合作</h3>
                    <p class="textindent">1元云购拥有国内庞大的消费群体及专业高效的电子商务平台，诚意邀请各品牌供应商与我们达成商务合作，共同创造中国电子商务的美好明天。</p>
                    <p class="bottom-space20px">邮 箱：hezuo@1yyg.com</p>
                    <h3>市场推广</h3>
                    <p class="textindent">随着1元云购发展壮大以及全国各地市场的开拓，欢迎拥有市场推广、广告合作资源的您与我们携手共进，共同发展。 携手共进。</p>
                    <p>电 话：0755-33908288</p>
                    <p class="bottom-space20px">邮 箱：qinzh@1yyg.com</p>
                    <h3>媒体关注</h3>
                    <p class="textindent">随着1元云购的发展，欢迎各类媒体前来沟通指导，同时欢迎各类内容合作策划传播，你们的关注和支持，采访以及报道，将成为1元云购成长历程不可或缺的一部分。</p>
                    <p>电 话：0755-33908288</p>
                    <p>邮 箱：zhangling@1yyg.com</p>
                    <br><br>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>