<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
        


    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>配送费用</h2>
                <style>
                .help-nav ul li a.cur10{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur10 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <p>所有商品全国免费配送。（港澳地区除外）</p>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>
