<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>正品保障</h2>
                <style>
                .help-nav ul li a.cur06{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur06 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <p class="textindent">
                        1元云购严格控制供应渠道，全部商品均从品牌官方以及品牌经销商直接采购供货，并取得品牌官方网络销售授权书，如果您认为云购的商品是假货，并能提供国家相关质检机构的证明文件，经确认后，在返还商品金额的同时并提供假一赔十服务保障。为了保障您的利益，对云购的商品，做如下说明：</p>
                            <p style="height:10px;"></p>
                    <p class="bottom-space16px">
                        1、1元云购对所有商品均保证正品行货，正规渠道发货，所有商品都可以享受生产厂家的全国联保服务，按照国家三包政策，针对所售商品履行保修、换货和退货的义务。</p>
                            <p style="height:10px;"></p>
                    <p class="bottom-space16px">
                        2、出现国家三包所规定的功能性故障时，经由生产厂家指定或特约售后服务中心检测确认故障属实，您可以选择换货或者维修；超过15日且在保修期内，您只能在保修期内享受免费维修服务。为了不耽误您使用，缩短故障商品的维修时间，我们建议您直接联系生产厂家售后服务中心进行处理。您也可以直接在商品的保修卡中查找该商品对应的全国各地生产厂家售后服务中心联系处理。</p>
                            <p style="height:10px;"></p>
                    <p class="bottom-space16px">
                        3、1元云购真诚提醒广大幸运者在您收到商品的时候，请尽量亲自签收并当面拆箱验货，如果有问题(运输途中的损坏)请不要签收!与快递员交涉，拒签，退回!</p>
                            <p style="height:10px;"></p>
                    <p class="bottom-space16px">
                        4、在收到商品后发现有质量问题，请您不要私自处理，妥善保留好原包装，第一时间联系1元云购客服人员，由1元云购同发货商城协商在48小时内解决。如有破损或丢失，我们将无法为您办理退货。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        如对协商处理结果存在异议，请您自行到当地生产厂家售后服务中心进行检测，并开据正规检测报告（对于有些生产厂家售后服务中心无法提供检测报告的，需提供维修检验单据），如果检测报告确认属于质量问题，然后将检测报告、问题商品及完整包装附件，一并返还发货商城办理换货手续，产生的相关费用由1元云购追究相关责任方承担。</p>
                            <p style="height:10px;"></p>
                    <p class="textindent">
                        1元云购上的电子产品及配件因为生成工艺或仓储物流原因，可能会存在收到或使用过程中出现故障的几率，1元云购不能保证所有的商品都没有故障，但我们保证所售商品都是全新正品行货，能够提供正规的售后保障。我们保证商品的正规进货渠道和质量，如果您对收到的商品质量表示怀疑，请提供生产厂家或官方出具的书面鉴定，我们会按照国家法律规定予以处理。但对于任何欺诈性行为，1元云购将保留依法追究法律责任的权利。本规则最终解释权由1元云购所有。</p>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>