<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
        


    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>1元云购保障体系</h2>
                <style>
                .help-nav ul li a.cur05{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur05 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <h4 class="mat0">
                        100%正品保证</h4>
                    <p>
                        1元云购精心挑选优质服务品牌商家，保障全场商品100%品牌正品。</p>
                    <h4>
                        100%公平公正</h4>
                    <p>
                        整个过程是完全透明，您可以随时查看每件商品参与人数，参与次数，参与名单及获得者信息等记录。</p>
                    <h4>
                        全国免费快递</h4>
                    <p>
                        1元云购承诺全场所有商品全国免费快递。（港澳台地区除外）</p>
                </div>
            </div>
        </div>
    </div>


    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>