<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>了解1元集资购</h2>
                <style>
                .help-nav ul li a.cur01{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur01 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                .help-content .rule b{ font-weight:bold;}
                </style>
                <div class="help-content">
                    <p class="textindent">
                        深圳市一元集资购网络科技有限公司（www.1yyg.com）是一种全新的互动购物体验方式，是时尚 、潮流的风向标，能满足个性、年轻消费者的购物需求，由深圳市一元集资购网络科技有限公司注入巨资打造的新型购物网。
                    </p>
                    <p style="height:10px;"></p>
                    <p class="textindent">
                        深圳市一元集资购网络科技有限公司以“快乐集资购，惊喜无限”为宗旨，力求打造一个100%公平公正、100%正品保障、寄娱乐与购物一体化的新型购物网站。
                    </p>
                    <p style="height:10px;"></p>
                    <p class="textindent">
                        随着互联网的发展及网购消费模式的多样化，深圳市一元集资购网络科技有限公司势必成为中国电子商网站中最具活力的生力军及网民最爱的购物网，必将迅速崛起，成为互联网新时代的佼佼者！
                    </p>
                    <p style="height:10px;"></p>
                    <p class="textindent">1元集资购是一种新型的网购模式，只需1元就有可能买到一件商品。1元集资购网把一件商品平分成若干“等份”出售，每份1元，当一件商品所有“等份”售出后计算出一名幸运者，该幸运者即可获得此商品。</p>
                    <h3>规则：</h3>
                            <p style="height:10px;"></p>
                    <div class="rule">
                        1、每件商品参考市场价平分成相应“等份”，每份1元，1份对应1个集资购码。
                            <p style="height:10px;"></p>
                        2、同一件商品可以购买多次或一次购买多份。
                            <p style="height:10px;"></p>
                        3、当一件商品所有“等份”全部售出后计算出“幸运集资购码”，拥有“幸运集资购码”者即可获得此商品。
                            <p style="height:10px;"></p>
                        4、幸运集资购码计算方式：
                            <p style="height:10px;"></p>
                        <p style="text-indent:-1em; padding-left:36px;">1）取该商品最后购买时间前网站所有商品100条购买时间记录（限时揭晓商品取截止时间前网站所有商品100条购买时间记录）。</p>
                            <p style="height:10px;"></p>
                        <p style="text-indent:1.6em;">2）时间按时、分、秒、毫秒依次排列组成一组数值。</p>
                            <p style="height:10px;"></p>
                        <p style="text-indent:1.6em;">3）将这100组数值之和除以商品总需参与人次后取余数，余数加上10,000,001即为“幸运集资购码”。</p>
                    </div>
                    <h3>流程：</h3>
                    <div class="rule" style="margin-top:10px;">
                        <b>1、挑选商品</b>
                        <p style="margin-bottom:15px; margin-top:5px;">分类浏览或直接搜索商品，点击“立即1元集资购”。</p>
                        <b>2、支付1元</b>
                        <p style="margin-bottom:10px; margin-top:5px;">通过在线支付平台，支付1元即购买1人次，获得1个“集资购码”。同一件商品可购买多次或一次购买多份，购买的“集资购码”越多，获得商品的几率越大。</p>
                        <b>3、揭晓获得者</b>
                        <p style="margin-bottom:15px; margin-top:5px;">当一件商品达到总参与人次，计算出1名商品获得者，1元集资购网会通过手机短信或邮件通知您领取商品。</p>
                            <h3 style="padding-left:22px; margin-top:0;">注：</h3>
                            <div class="rule" style="margin-bottom:15px;">
                                <p style="margin-bottom:10px; margin-top:5px; text-indent:1.6em;">1）商品揭晓后您可登录"我的1元集资购"查询详情，未获得商品的用户不会收到短信或邮件通知；</p>
                                <p style="margin-bottom:10px; margin-top:5px; text-indent:1.6em;">2）商品揭晓后，请及时登录"我的1元集资购"完善个人资料，以便我们能够准确无误地为您配送商品。</p>
                                <p style="margin-bottom:10px; margin-top:5px; text-indent:1.6em;">3）所有已揭晓商品均不给予退款</p>
                            </div>   
                    
                        <b>4、晒单分享</b><br>
                        <p style="margin-top:5px;">晒出您收到的商品实物图片甚至您的靓照，说出您的集资购心得，让大家一起分享您的快乐。</p>
                        <p>在您收到商品后，您只需登录网站完成晒单，并通过审核，即可获得400-1500福分奖励。在您成功晒单后，您的晒单会出现在网站"晒单分享"区，与大家分享喜悦。</p>
                      </div>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>