<link rel="stylesheet" type="text/css" href="/help/css/link.css" />
<div class="g-wrap w1190">
    <div class="g-links-con clrfix">
        
            <dl class="clrfix">
                <dt class="gray3"><em>文字链接</em></dt>
                <dd>
                    
                            <span><a href="http://guangzhou.baixing.com/ershou/ " title="广州二手网" target="_blank">广州二手网</a></span>
                        
                            <span><a href="http://www.yunmibao.com/" title="云密保一键通 " target="_blank">云密保一键通 </a></span>
                        
                            <span><a href="http://www.yifen.com/" title="一分网" target="_blank">一分网</a></span>
                        
                            <span><a href="http://www.17K.com/" title="17K小说网" target="_blank">17K小说网</a></span>
                        
                            <span><a href="http://www.xianbey.com/" title="鲜贝网" target="_blank">鲜贝网</a></span>
                        
                            <span><a href="http://www.juanpi.com/" title="淘宝返利" target="_blank">淘宝返利</a></span>
                        
                            <span><a href="http://www.okhqb.com/" title="华强北商城" target="_blank">华强北商城</a></span>
                        
                            <span><a href="http://www.pba.cn/" title="化妆品商城" target="_blank">化妆品商城</a></span>
                        
                            <span><a href="http://www.yjyj123.com" title="隐形眼镜" target="_blank">隐形眼镜</a></span>
                        
                            <span><a href="http://www.xiu.com" title="走秀网" target="_blank">走秀网</a></span>
                        
                </dd>
            </dl>
        
        
        <dl class="clrfix">
            <dt class="gray3"><em>联系方式</em></dt>
            <dd>
                <p>电话：0755-33918790</p>
                <p>邮箱：qinzh@1yyg.com</p>
            </dd>
        </dl>
    </div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>