<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>商品验货与签收</h2>
                <style>
                .help-nav ul li a.cur11{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur11 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <p class="bottom-space16px">
                        1、您在签收商品时请慎重，请尽量不要让人代签，并务必先仔细检查商品（外包装是否被开封、商品是否破损、配件是否缺失、功能是否正常），确保无误后再签收，以免产生不必要的纠纷。若有任何疑问，请及时拨打客服电话反馈信息。若因用户未仔细检查商品即签收后产生的纠纷，1元集资购概不负责，仅承担协调处理的义务。
                    </p>
                            <p style="height:10px;"></p>
                    <p class="bottom-space16px">
                        2、若因您的地址填写错误、联系方式填写有误等情况造成商品无法完成投递或被退回，所产生的额外费用及后果由用户负责。</p>
                            <p style="height:10px;"></p>
                    <p>
                        3、如因不可抗拒的自然原因（地震、洪水等等）所造成的商品配送延迟，1元集资购不承担责任。</p>
                            <p style="height:10px;"></p>
                    <h4>
                        温馨提醒</h4>
                    <p class="textindent">
                        若您或您的委托人已签收，则说明订单商品正确无误且不存在影响使用的因素，1元集资购有权不受理因包装或商品破损、商品错漏发、商品表面质量问题、商品附带品及赠品少发为由的换货申请。
                    </p>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>