<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part"><div class="help-right-part">
        <div class="help-in-rihgt-part">
            <h2>常见问题</h2>
            <style>
            .help-nav ul li a.cur02{color:#f60;  position:relative; font-weight:bold;}
            .help-nav ul li a.cur02 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
            </style>
            <div class="help-content">
                <h4 class="mat0">
                    1、怎样查看我参与的商品有没有获得？</h4>
                <p>
                    每件商品揭晓结果公布之后，登录集资购网，进入"我的1元集资购"，在"集资购记录"中即可查询揭晓情况。</p>
                <h4>
                    2、我获得了商品，我还需要支付其他费用吗？</h4>
                <p>
                    不需要支付其他任何费用。</p>
                <h4>
                    3、当我获得商品以后我该做什么？</h4>
                <p class="textindent">
                    在您获得商品后您会收到站内信、短信和电子邮件的通知。在这之后，您必须在“我的1元集资购”正确填写、真实的收货地址，完善或确认您的个人信息。我们会在您获得商品后3个工作日内通过电话方式与您取得联系。</p>
                <h4>
                    4、集资购网的商品是正品吗？怎么保证？</h4>
                <p>
                    集资购网承诺，所有商品100%正品，可享受厂家所提供的全国联保服务，享受商品的保修、换货和退货的义务（国家三包政策）。</p>
                <h4>
                    5、如何晒单分享？</h4>
                <p>
                    在您收到商品后，登录集资购网，进入"我的1元集资购"，在“晒单分享”区发布晒单信息，通过审核后，您还可获得400-1500福分奖励。在您成功晒单后，您的晒单会出现在网站“晒单分享”区，与大家分享喜悦。</p>
                <h4>
                    6、我收到的商品可以换货或者退货吗？</h4>
                <p>
                    非质量问题，不在三包范围内，不给予退换货。</p>
                <h4>
                    7、参与1元集资购需要注意什么？</h4>
                <p>
                    请务必正确填写真实有效的联系电话、收货地址以便在您获得商品时能及时与您取得联系。</p>
                <h4>
                    8、网上银行充值未及时到帐怎么办？</h4>
                <p>
                    网上支付未及时到帐可能有以下几个原因造成：</p>
                <p>
                    第一，由于网速或者支付接口等问题，支付数据没有及时传送到支付系统造成的；</p>
                <p>
                    第二，网速过慢，数据传输超时，使银行后台支付信息不能成功对接，导致银行交易成功而支付后台显示失败；</p>
                <p>
                    第三，在网上支付如果使用某些防火墙软件，有时会屏蔽银行接口的弹出窗口，这时会造成在银行那边被扣费，但在我们网站上显示尚没支付。但请您放心，每天我们都会根据银行系统的帐务明细清单对前一天的订单进行逐笔核对，如遇问题订单，我们会做手工添加。</p>
                <p>
                    建议反馈</p>
                <p>
                    如您对我们“帮助中心”的说明有任何疑问或建议请<a href="http://help.1yyg.com/htm-contactus.html">告诉我们</a></p>
            </div>
        </div>
    </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>