<link rel="stylesheet" type="text/css" href="/help/css/invitation.css" />
<div class="g-main-con clrfix">
    <div class="g-inv-ad clrfix">
        <img alt="" src="/help/images/pic_10.jpg?v=151105">
        <img alt="" src="/help/images/pic_11.jpg?v=151105">
        <img alt="" src="/help/images/pic_12.jpg?v=151105">
    </div>
    <div class="g-inv-con clrfix">
        <?php if(empty($_SESSION['member_id'])){?>
        <!-- 未登录状态 -->
        <div class="not-logged-in">
            <p class="gray9">立即登录邀请好友获取奖励！ <span>没账号？马上注册立享邀请特权！</span></p><a href="<?php echo $this->view->baseUrl?>member/passport/login?forward=rego" class="z-login">登 录</a><a href="<?php echo $this->view->baseUrl?>member/passport/register" class="z-register">注 册</a>
        </div>
        <!-- 未登录状态结束 -->
        <?php }else{?>
        <!-- 登陆后状态 -->
        <div class="share-part1 clrfix">
            <div class="inv-share fl"><p class="gray6">您可以使用以下方式邀请好友，听说成功率更高哦！</p>
                <div class="bdsharebuttonbox m-share-icon clrfix bdshare-button-style2-16" data-bd-bind="1448093836497"><a href="javascript:;" data-cmd="sqq" class="z-qq" title="分享到QQ好友"></a><a href="javascript:;" data-cmd="tsina" class="z-sina" title="分享到新浪微博"></a><a href="javascript:;" data-cmd="qzone" class="z-space" title="分享到QQ空间"></a><a href="javascript:;" data-cmd="weixin" class="z-weixin" title="分享到微信"></a><a href="javascript:;" data-cmd="tqq" class="z-qq-weibo" title="分享到腾讯微博"></a></div>
            </div>
            <div class="inv-link fr"><p class="gray6">您也可以复制专属邀请链接发送给好友！</p>
                <div class="m-link-bor"><textarea rows="3" cols="10" id="copyShareText" class="gray6">1元就能买iPhone 6S，一种很有意思的购物方式，快来看看吧！<?php echo $this->view->webUrl?>yungou/index/index?invited_id=<?php echo $this->view->invitationInfo['_id']?></textarea><a id="btnCopy" href="javascript:;">复制</a></div>
            </div>
        </div>
        <!-- 登陆后状态结束 -->
        <?php }?>
        <div class="raiders-part2 clrfix">
            <p class="gray3 inv-title">赚钱攻略</p>
            <img alt="" src="/help/images/raiders.gif">
            <div class="raid-text gray6">
                <ul>
                    <li class="f-step1">登录验证手机<br>
                        获取您的专属链接</li>
                    <li>分享您的专属链接<br>
                        发送给好友</li>
                    <li>好友成功注册<br>
                        并消费</li>
                    <li class="f-step4">获得奖励<br>
                        50福分+6%现金</li>
                </ul>
            </div>
        </div>

        <div class="rule-part3 clrfix">
            <p class="inv-title gray3">相关规则</p>
            <span>1、每成功邀请一位好友注册并参与云购后，可获得50福分+6%现金提成。在  <a target="_blank" href="/">我的1元云购</a> &gt; <a target="_blank" href="../member/InvitedList.html">邀请管理</a>  可随时查看佣金明细及邀请记录。<br>
                2、佣金永久有效，满1元即可充值到1元云购账户，满100元即可申请提现。<br>
                3、推荐您将专属邀请链接分享至微博、微信朋友圈、QQ空间等社交平台，也可直接复制邀请链接发送给您的好友。<br>
                4、严禁利用非法手段恶意获取佣金，一经查实，将立即冻结账号，扣除所有佣金，清除福分。
            </span>
        </div>
    </div>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>