<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
        


    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>安全支付</h2>
                <style>
                .help-nav ul li a.cur07{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur07 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <p class="textindent">
                        1元集资购作为平安银行、网银在线、快钱、银联在线支付的认证商家，严格遵循网络购物的安全准则，通过网银在线、快钱、银联在线支付等安全度高的支付方式，充分保证您在线支付的安全性。</p>
                </div>
            </div>
        </div>
    </div>



    <?php $this->partial("partials/help/leftpart") ?>
    
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>