<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>长时间未收到商品</h2>
                <style>
                .help-nav ul li a.cur12{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur12 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <p>
                        长时间未收到商品可能出现的问题：</p>
                    <p>
                        1、请您确保您的收货地址、邮编、电话、Email地址等各项信息的准确性，以便商品及时、准确地发出。</p>
                    <p>
                        2、当您的商品送达目的地之后，如快递人员在快件保管期（一般3-7天）未能联系到您，快件将退回，我们会联系您进行二次配送，由此产生的费用将由您自行承担。</p>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>
<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>