<link rel="stylesheet" type="text/css" href="/help/css/Help.css" />
<div class="help-main w1190">         
    <div id="ltlContents" class="help-right-part">
        <div class="help-right-part">
            <div class="help-in-rihgt-part">
                <h2>福分经验值明细表</h2>
                <style>
                .help-nav ul li a.cur04{color:#f60;  position:relative; font-weight:bold;}
                .help-nav ul li a.cur04 b{width:4px; height:4px; overflow:hidden; background:#f60; display:inline-block; position:absolute; left:-10px; top:5px;}
                </style>
                <div class="help-content">
                    <div class="help_class_tab">
                        <h3 class="mat0">等级明细</h3>
                        <table border="0" cellspacing="0" cellpadding="0">
                          <tbody><tr>
                            <th>等级 </th>
                            <th>等级名称 </th>
                            <th>身份标识</th>
                            <th>所需经验值 </th>
                            <th>备注</th>
                          </tr>
                          <tr>
                            <td>一级</td>
                            <td>云购小将</td>
                            <td valign="middle" class="class01"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>10000以下</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>二级</td>
                            <td>云购少将</td>
                            <td valign="middle" class="class02"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>10000</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>三级</td>
                            <td>云购中将</td>
                            <td valign="middle" class="class03"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>50000</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>四级</td>
                            <td>云购上将</td>
                            <td valign="middle" class="class04"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>200000</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>五级</td>
                            <td>云购大将</td>
                            <td valign="middle" class="class05"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>500000</td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>六级</td>
                            <td>云购将军</td>
                            <td valign="middle" class="class06"><b><img src="http://skin.1yyg.com/Member/images/new-class-icon.png"></b></td>
                            <td>1000000</td>
                            <td>&nbsp;</td>
                          </tr>
                        </tbody></table>
                    </div>
                    <div class="help_class_tab help_Experience_tab">
                        <h3>福分经验值明细</h3>
                        <table border="0" cellspacing="0" cellpadding="0">
                          <tbody><tr>
                            <th colspan="2">项目 </th>
                            <th>获得福分</th>
                            <th>获得经验值</th>
                            <th>备注</th>
                          </tr>
                          <tr>
                            <td colspan="2">参与云购每消费1元</td>
                            <td><strong class="orange">1</strong></td>
                            <td><strong class="orange">10</strong></td>
                            <td>生日当月享双倍福分</td>
                          </tr>
                          <tr>
                            <td colspan="2">每成功邀请1位好友并消费</td>
                            <td><strong class="orange">50</strong></td>
                            <td><strong class="orange">50</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="2">成功晒单</td>
                            <td><strong class="orange">400-1500</strong></td>
                            <td><strong class="orange">500</strong></td>
                            <td>限时揭晓商品除外</td>
                          </tr>
                          <tr>
                            <td colspan="2">晒单评论</td>
                            <td><strong class="orange">1</strong></td>
                            <td><strong class="orange">10</strong></td>
                            <td>最多100福分、1000经验值每天</td>
                          </tr>
                          <tr>
                            <td colspan="2">发表话题</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">50</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="2">话题加精</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">50</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="2">回复话题</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">10</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="2">加好友</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">5</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="2">圈主</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">1000</strong></td>
                            <td>每月获得一次</td>
                          </tr>
                          <tr>
                            <td colspan="2">管理员</td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td><strong class="orange">500</strong></td>
                            <td>每月获得一次</td>
                          </tr>
                          <tr>
                            <td rowspan="10">完善个人资料</td>
                            <td>手机验证</td>
                            <td><strong class="orange">20</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>邮箱验证</td>
                            <td><strong class="orange">10</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>昵称</td>
                            <td><strong class="orange">10</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>性别</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>生日</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>现居地</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>家乡</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>QQ</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>月收入</td>
                            <td><strong class="orange">5</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td>签名</td>
                            <td><strong class="orange">10</strong></td>
                            <td><strong class="orange">&nbsp;</strong></td>
                            <td>&nbsp;</td>
                          </tr>
                          <tr>
                            <td colspan="5" height="40" align="center">注：恶意灌水发表回复话题，将会扣除相应双倍经验值！</td>
                          </tr>
                        </tbody></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php $this->partial("partials/help/leftpart") ?>
</div>

<script type="text/javascript" src="/dist/js/common.js"></script>
<script type="text/javascript" src="/dist/js/help.js"></script>
